### DISCUSSION TITLE
Getting logging to work in custom quirk

### DISCUSSION THREAD

**Discussion by hastarin** [zigpy/zha-device-handlers#2511] [Q&A] [answered]
Hi all,

I'm trying to get a custom quirk working #2451 but find I'm rather stuck without logging and I can't get logging to show in the `home-assistant.log`.

I've added logging to the quirk using:
```python
import logging

_LOGGER = logging.getLogger(__name__)
```

And I've tried logging with both debug/warn to no results. For example:
```python
_LOGGER.debug("WindowCovering command %04x", command_id)

_LOGGER.warn("OnOff update attribute %04x to %s", attrid, value)
```

My current logger config is as follows:
```yaml
logger:
  default: warn
  logs:
    # homeassistant.core: debug
    homeassistant.components.zha.cover: debug
    # bellows.zigbee.application: debug
    # bellows.ezsp: debug
    # zigpy: debug
    # zigpy_deconz.zigbee.application: debug
    # zigpy_deconz.api: debug
    # zigpy_xbee.zigbee.application: debug
    # zigpy_xbee.api: debug
    # zigpy_zigate: debug
    # zigpy_znp: debug
    zhaquirks: debug
    custom_zha_quirks: debug
```
I'd tried all the various commented out options as well.

Any advice on how to get logging going would be greatly appreciated.
