### DISCUSSION TITLE
Support for TS0601 TZE200_uiyqstza

### DISCUSSION THREAD

**Discussion by icodetea** [zigpy/zha-device-handlers#2586] [Q&A]
I recetly purchased a radio valve (https://www.hornbach.de/p/essentials-heizkoerperthermostat-zigbee-smart-home-weiss-120144/10540147/) and was hoping, it would just seamless work with ZHA Bridge. Sadly it does not. I can pair it but no usable entities are found. Here the SIgnature:

```json
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4417, maximum_buffer_size=66, maximum_incoming_transfer_size=66, server_mask=10752, maximum_outgoing_transfer_size=66, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": "0x0104",
      "device_type": "0x0051",
      "input_clusters": [
        "0x0000",
        "0x0004",
        "0x0005",
        "0xef00"
      ],
      "output_clusters": [
        "0x000a",
        "0x0019"
      ]
    }
  },
  "manufacturer": "_TZE200_uiyqstza",
  "model": "TS0601",
  "class": "zigpy.device.Device"
}
```

After some reserach I found out that some custom device handlers are missing in my case. But i also see that some similar devices already successfully implemented. I there somewhere an exsisting device handler here which u could use by just appending the manufacturer number in the code or i a new device handler needed. Can I find somewhere help or documantation, howto make it work or write a device handler?

**Comment by MattWestb** [comment]
Its not implemented in ZHA but one of our devs have making one working quirk for it.
Look at https://github.com/jacekk015/zha_quirks#ts0601_trv_maxsmartpy

**Reply by icodetea** [reply]
ok thx,
I downloaded th file an put it into custom configuration folder:
```
DockerStation:/config# ls custom_zha_quirks/
__pycache__             ts0601_trv_maxsmart.py
```

and appended the entry in configuration yaml:
``` 
DockerStation:/config# cat configuration.yaml 

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
zha:
  custom_quirks_path: /config/custom_zha_quirks/
```

after restart HA in UI:` developer-tools->yaml->restart ` and rebinding, still no entities, did I miss sth?
