### ISSUE TITLE
[BUG] hvac_action value of Bitron Termostat is always off

### ISSUE THREAD

**Issue by kovbalazs89** [zigpy/zha-device-handlers#1162]
The HVAC_ACTION attribute of my Bitron Home 902010/32 thermostat is always off , never changes.  The associated sensor in HomeAssistant shows always off too. Because of this, I cant see the hvac status of my thermostat in HomeAssistant.

**To Reproduce**
1. Go to Integrations
2. Click on ZHA
3. Pair the Bitron Thermostat to HomeAssistant
4. See the attributes of the climate entity

**Expected behavior**
Climate state changes in HomeAssistant after the thermostat turned physically the relay on and off.

**Screenshots**
I was able the query the real cluster attribute of this termostat, when the heating is on or off.

![idle](https://user-images.githubusercontent.com/58386184/142646476-e2357338-6f3f-4411-8b2d-1ac58518ec49.png)
![heat](https://user-images.githubusercontent.com/58386184/142646485-1a70d792-d1a2-4afa-ab3b-4530a7a9552e.png)

**Additional context**
I have created an sql query sensor in Home Assistant, to track the state of the running_state attribute. It can show the correct state from zigbee.db file.

```
  - platform: sql
    db_url: sqlite:////config/zigbee.db
    scan_interval: 10
    queries:
      - name: hvac_mode
        query: "SELECT value FROM attributes_cache_v7 where ieee = '00:0d:6f:00:17:0c:df:fc' and cluster = 513 and attrid = 41"
        column: "value" 
```

![image](https://user-images.githubusercontent.com/58386184/142646936-3fb27f38-15f4-4833-bacf-8121749e7da0.png)

I think, we need a replacement in this device_handler to get the real state of the thermostat's hvac_action.
