### ISSUE TITLE
Tuya curtain motors TM616EGZT Calibration feature missing

### ISSUE THREAD

**Issue by PremiumUsername** [zigpy/zha-device-handlers#1194]
There is no way to set the end limits or the direction of the motor with the physical buttons, so calibration needs to be done using zigbee. Would it be possible to add the calibration cluster that exist for some other Tuya  motors (e.g. TS130F) to the TM616EGZT?

**Comment by skygrip** [comment]
Ive had a look at the Tuya IOT builder, and i believe the calibration is controlled using Tuya command "border" with DP ID 16. This command takes a "Enum" data type, is R/W, and has the properties "Enum Value: up, down, up_delete, down_delete, remove_top_bottom"

I haven't had any real experience with writing ZHA quirks to expose these settings, but ill have a look

**Comment by MattWestb** [comment]
I think the defrnition of the commands shall being placed in this part in the INIT:
https://github.com/zigpy/zha-device-handlers/blob/08f99237f165560921845abbc6b810cb5a0cd4d8/zhaquirks/tuya/__init__.py#L96-L102 or some line above that have some that looks like attributes and commands.

The device class is here and more classes below but i dont knowing  how to implementing it then outs out of my skills.
https://github.com/zigpy/zha-device-handlers/blob/08f99237f165560921845abbc6b810cb5a0cd4d8/zhaquirks/tuya/__init__.py#L929-L931

**Comment by skygrip** [comment]
I managed to get the following commands to work using the developer tools > Services to set a "border" in Home Assistant. As you dont usually have to run the calibration often, this might be a good workaround for the moment. Im making use of the custom command function in the ZHA quirk. It worked on my device with firmware TZE200_gubdgai2

Grab the MAC for the device from your devices page, substitute it in the YAML, and then try the below codes. Remember to click "Go To YAML Mode" to paste the code.

Set Upper Bounds

```
service: zha.issue_zigbee_cluster_command
data:
  ieee: INSERT YOUR DEVICE MAC HERE
  endpoint_id: 1
  command_type: server
  cluster_id: 258
  command: 0x6
  args:
      - 0
      - 0
      - 0x0410
      - 0
      - [1,0x0000]
```

Set lower bound

```
service: zha.issue_zigbee_cluster_command
data:
  ieee: INSERT YOUR DEVICE MAC HERE
  endpoint_id: 1
  command_type: server
  cluster_id: 258
  command: 0x6
  args:
      - 0
      - 0
      - 0x0410
      - 0
      - [1,0x0001]
```

Delete upper bounds

```
service: zha.issue_zigbee_cluster_command
data:
  ieee: INSERT YOUR DEVICE MAC HERE
  endpoint_id: 1
  command_type: server
  cluster_id: 258
  command: 0x6
  args:
      - 0
      - 0
      - 0x0410
      - 0
      - [1,0x0002]
```

Delete lower bounds

```
service: zha.issue_zigbee_cluster_command
data:
  ieee: INSERT YOUR DEVICE MAC HERE
  endpoint_id: 1
  command_type: server
  cluster_id: 258
  command: 0x6
  args:
      - 0
      - 0
      - 0x0410
      - 0
      - [1,0x0003]
```

0x04 is data type Enum and then 0x10 is DP ID "Border". The hex in the last argument most likely corresponds to "up, down, up_delete, down_delete, remove_top_bottom"

Im not entirely sure how to make this more user friendly or expose it in the UI just yet, but i thought i would post this code in the hope it might be of interest to others. No guarantee it would work on your device though, test it before you install it so you don't destroy your blinds.

**Comment by PremiumUsername** [comment]
> I managed to get the following commands to work using the developer tools > Services to set a "border" in Home Assistant.

Confirmed solution! ....works brilliantly. Thank you! 

How did you manage to find that command?

**Comment by PremiumUsername** [comment]
> Ive had a look at the Tuya IOT builder. 

I don't have a Tuya developer account and I never found a public API. What other interesting settings are there to play with?
I assume there is a way to reverse the motor direction, so the buttons work the other way around.

**Comment by skygrip** [comment]
Set motor direction Forward

Valid for at least the _TZE200_gubdgai2 variant

```
service: zha.issue_zigbee_cluster_command
data:
ieee: b4:e3:f9:ff:fe:af:58:c1
  endpoint_id: 1
  command_type: server
  cluster_id: 258
  command: 0x6
  args:
      - 0
      - 0
      - 0x0405 # DIP command 5, motor direction
      - 0
      - [1,0x0000] # Forward direction
```

Set Motor Direction Back

```
service: zha.issue_zigbee_cluster_command
data:
  ieee: b4:e3:f9:ff:fe:af:58:c1
  endpoint_id: 1
  command_type: server
  cluster_id: 258
  command: 0x6
  args:
      - 0
      - 0
      - 0x0405 # DIP command 5, motor direction
      - 0
      - [1,0x0001] # Back direction
```
