### ISSUE TITLE
ZemismartSmartCover0601

### ISSUE THREAD

**Issue by Robert126** [zigpy/zha-device-handlers#1282]
I have a question about the following curtain automation made in Home Assistant and making use of Zigbee Home Automation.

I created one automation for closing the curtain and one for opening the curtain.
1) When I run one or the other action (closing or opening the curtain) the curtain motor is turning in the same direction. 
2) Second after triggering run action. The motor is first turning one way after a certain period it is turning the opposite way.

Hopefully, someone can help me out?

Thanks for your help!
Robert 

---------------- 
Running the latest Home Assistant version (Supervised, Host operating system: Debian 11 (bullseye)
ZigBee dongle: CC2652R1
Curtain motor: Tuya DS82 (ZigBee 2.0NM), S4405EU.
- TS061 by TZE200zpzndjez
- Quirk: zhaquirks.tuya.ts0601_cover.TuyaZemismartSmartCover0601

Zigbee device signature:
```
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress|RxOnWhenIdle|MainsPowered|FullFunctionDevice: 142>, manufacturer_code=4098, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0202",
      "in_clusters": [
        "0x0000",
        "0x0004",
        "0x0005",
        "0x000a",
        "0x0102",
        "0xef00"
      ],
      "out_clusters": [
        "0x0019"
      ]
    }
  },
  "manufacturer": "_TZE200_zpzndjez",
  "model": "TS0601",
  "class": "zhaquirks.tuya.ts0601_cover.TuyaZemismartSmartCover0601"
}
```
/confing/automation.yaml
```
- id: '2781373703476'
  alias: Curtain Hallway Closing
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 00:20:00
  condition:
  - condition: device
    device_id: 233767394d30539757780b6d275972cf
    domain: cover
    entity_id: cover.curtain_hallway_window_covering
    type: is_open
  action:
  - device_id: 233767394d30539757780b6d275972cf
    domain: cover
    entity_id: cover.curtain_hallway_window_covering
    type: set_position
    position: 50
  mode: single
- id: '2781373775098'
  alias: Curtain Hallway Opening
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: '0'
  condition:
  - condition: device
    device_id: 233767394d30539757780b6d275972cf
    domain: cover
    entity_id: cover.curtain_hallway_window_covering
    type: is_closed
  - condition: time
    after: 08:07
  action:
  - device_id: 233767394d30539757780b6d275972cf
    domain: cover
    entity_id: cover.curtain_hallway_window_covering
    type: set_position
    position: 40
  mode: single
```
