### ISSUE TITLE
[BUG] Elko Super TR thermostat not working.

### ISSUE THREAD

**Issue by bendikrb** [zigpy/zha-device-handlers#1585]
**Describe the bug**
See attached screenshots.
Related to;
#1520
#999 

**Screenshots**
![Screenshot_20220525_161521](https://user-images.githubusercontent.com/152300/170283701-4f30e497-b9dc-469e-a237-bbbba23c7620.png)
![Screenshot_20220525_161329](https://user-images.githubusercontent.com/152300/170283492-bf35a6dd-7ae7-46d4-aef3-35510d766d71.png)

<details>
<summary>Device signature</summary>

```yaml
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress|RxOnWhenIdle|MainsPowered|FullFunctionDevice: 142>, manufacturer_code=4919, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0301",
      "in_clusters": [
        "0x0000",
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0201",
        "0x0204",
        "0x0b04"
      ],
      "out_clusters": [
        "0x0003",
        "0x0019"
      ]
    }
  },
  "manufacturer": "ELKO",
  "model": "Super TR",
  "class": "zhaquirks.elko.smart_super_thermostat.ElkoSuperTRThermostat"
}
```

</details>

<details>

<summary>Diagnostic information</summary>

```yaml
{
  "home_assistant": {
    "installation_type": "Home Assistant Supervised",
    "version": "2022.5.5",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.9.9",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Oslo",
    "os_name": "Linux",
    "os_version": "5.13.0-41-generic",
    "supervisor": "2022.05.3",
    "host_os": "Ubuntu 21.10",
    "docker_version": "20.10.8",
    "chassis": "desktop",
    "run_as_root": true
  },
  "custom_components": {
    "fontawesome": {
      "version": "2.1.5",
      "requirements": []
    },
    "eventsensor": {
      "version": "3.0.0",
      "requirements": []
    },
    "average": {
      "version": "2.2.3",
      "requirements": []
    },
    "metnowcast": {
      "version": "2.0.2",
      "requirements": []
    },
    "zaptec": {
      "version": "0.0.5",
      "requirements": [
        "azure-servicebus==7.0.1"
      ]
    },
    "priceanalyzer": {
      "version": "0.0.10",
      "requirements": [
        "nordpool>=0.2"
      ]
    },
    "cover_rf_time_based": {
      "version": "1.0.8",
      "requirements": [
        "xknx==0.9.4"
      ]
    },
    "favicon": {
      "version": "10.4",
      "requirements": []
    },
    "attributes": {
      "version": "1.2.0",
      "requirements": []
    },
    "mass": {
      "version": "1.1.16",
      "requirements": [
        "music-assistant==1.1.16"
      ]
    },
    "auto_areas": {
      "version": "1.0.0",
      "requirements": []
    },
    "simpleicons": {
      "version": "v2.0.0",
      "requirements": [
        "simpleicons==6.16.0"
      ]
    },
    "ui_lovelace_minimalist": {
      "version": "v0.0.8",
      "requirements": []
    },
    "google_home": {
      "version": "1.9.10",
      "requirements": [
        "glocaltokens==0.6.3",
        "google-api-python-client==2.38.0"
      ]
    },
    "entities_calendar": {
      "version": "0.0.8",
      "requirements": []
    },
    "reversotts": {
      "version": "1.0.2",
      "requirements": [
        "pyttsreverso==0.4"
      ]
    },
    "unifi_network": {
      "version": "0.4.0",
      "requirements": [
        "pyunifi==2.21"
      ]
    },
    "programmable_thermostat": {
      "version": "8.1",
      "requirements": []
    },
    "browser_mod": {
      "version": "1.5.3",
      "requirements": []
    },
    "scheduler": {
      "version": "v0.0.0",
      "requirements": []
    },
    "watchman": {
      "version": "0.5.1",
      "requirements": [
        "prettytable==3.0.0"
      ]
    },
    "weatherapi": {
      "version": "0.8",
      "requirements": []
    },
    "mjpeg_timelapse": {
      "version": "2021.12.30",
      "requirements": []
    },
    "plex_recently_added": {
      "version": "0.3.8",
      "requirements": []
    },
    "jellyfin": {
      "version": "1.1.0",
      "requirements": [
        "jellyfin-apiclient-python==1.7.2"
      ]
    },
    "hacs": {
      "version": "1.25.1",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
    "tgtg": {
      "version": "4.0.3",
      "requirements": [
        "tgtg>=0.11.3"
      ]
    },
    "pid_controller": {
      "version": "v1.1.3",
      "requirements": []
    },
    "hifiberry": {
      "version": "0.0.3",
      "requirements": [
        "pyhifiberry>=0.1.1"
      ]
    },
    "variable": {
      "version": "2.2.2",
      "requirements": []
    },
    "nordpool": {
      "version": "0.0.7",
      "requirements": [
        "nordpool>=0.2"
      ]
    },
    "mopidy": {
      "version": "1.4.6",
      "requirements": [
        "mopidyapi==1.0.0"
      ]
    },
    "blitzortung": {
      "version": "1.0.1",
      "requirements": [
        "paho-mqtt>=1.5.0"
      ]
    },
    "webrtc": {
      "version": "v2.3.0",
      "requirements": []
    },
    "remote_homeassistant": {
      "version": "3.6",
      "requirements": []
    },
    "energidataservice": {
      "version": "v0.2.0",
      "requirements": [
        "CurrencyConverter==0.16.11"
      ]
    },
    "pyscript": {
      "version": "1.3.3",
      "requirements": [
        "croniter==1.3.4",
        "watchdog==2.1.6"
      ]
    },
    "files": {
      "version": "1.5",
      "requirements": []
    },
    "climate_template": {
      "version": "0.2.0",
      "requirements": []
    },
    "google_keep": {
      "version": "v1.1.4",
      "requirements": [
        "gkeepapi==0.11.16"
      ]
    },
    "spacex": {
      "version": "029",
      "requirements": [
        "spacexpypi==0.0.12"
      ]
    },
    "spotcast": {
      "version": "v3.6.29",
      "requirements": [
        "spotify_token==1.0.0"
      ]
    },
    "sbanken": {
      "version": "2.1.1",
      "requirements": [
        "oauthlib==3.2.0",
        "requests-oauthlib==1.3.1"
      ]
    },
    "zha_toolkit": {
      "version": "v0.8.8",
      "requirements": []
    },
    "openhasp": {
      "version": "0.6.3",
      "requirements": [
        "jsonschema>=3.2.0"
      ]
    },
    "frigate": {
      "version": "2.3",
      "requirements": []
    }
  },
  "integration_manifest": {
    "domain": "zha",
    "name": "Zigbee Home Automation",
    "config_flow": true,
    "documentation": "https://www.home-assistant.io/integrations/zha",
    "requirements": [
      "bellows==0.29.0",
      "pyserial==3.5",
      "pyserial-asyncio==0.6",
      "zha-quirks==0.0.73",
      "zigpy-deconz==0.16.0",
      "zigpy==0.45.1",
      "zigpy-xbee==0.14.0",
      "zigpy-zigate==0.7.4",
      "zigpy-znp==0.7.0"
    ],
    "usb": [
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*2652*",
        "known_devices": [
          "slae.sh cc2652rb stick"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*sonoff*plus*",
        "known_devices": [
          "sonoff zigbee dongle plus"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*zigstar*",
        "known_devices": [
          "ZigStar Coordinators"
        ]
      },
      {
        "vid": "1CF1",
        "pid": "0030",
        "description": "*conbee*",
        "known_devices": [
          "Conbee II"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8A2A",
        "description": "*zigbee*",
        "known_devices": [
          "Nortek HUSBZB-1"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8B34",
        "description": "*bv 2010/10*",
        "known_devices": [
          "Bitron Video AV2010/10"
        ]
      }
    ],
    "codeowners": [
      "@dmulcahey",
      "@adminiuga"
    ],
    "zeroconf": [
      {
        "type": "_esphomelib._tcp.local.",
        "name": "tube*"
      }
    ],
    "after_dependencies": [
      "usb",
      "zeroconf"
    ],
    "iot_class": "local_polling",
    "loggers": [
      "aiosqlite",
      "bellows",
      "crccheck",
      "pure_pcapy3",
      "zhaquirks",
      "zigpy",
      "zigpy_deconz",
      "zigpy_xbee",
      "zigpy_zigate",
      "zigpy_znp"
    ],
    "is_built_in": true
  },
  "data": {
    "ieee": "**REDACTED**",
    "nwk": 10848,
    "manufacturer": "ELKO",
    "model": "Super TR",
    "name": "ELKO Super TR",
    "quirk_applied": true,
    "quirk_class": "zhaquirks.elko.smart_super_thermostat.ElkoSuperTRThermostat",
    "manufacturer_code": 4919,
    "power_source": "Mains",
    "lqi": 255,
    "rssi": -31,
    "last_seen": "2022-05-25T16:06:18",
    "available": true,
    "device_type": "Router",
    "signature": {
      "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress|RxOnWhenIdle|MainsPowered|FullFunctionDevice: 142>, manufacturer_code=4919, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
      "endpoints": {
        "1": {
          "profile_id": 260,
          "device_type": "0x0301",
          "in_clusters": [
            "0x0000",
            "0x0003",
            "0x0004",
            "0x0005",
            "0x0201",
            "0x0204",
            "0x0b04"
          ],
          "out_clusters": [
            "0x0003",
            "0x0019"
          ]
        }
      }
    },
    "entities": [
      {
        "entity_id": "button.elko_super_tr_344b22fe_identify",
        "name": "ELKO Super TR"
      },
      {
        "entity_id": "climate.elko_super_tr_344b22fe_thermostat",
        "name": "ELKO Super TR"
      },
      {
        "entity_id": "sensor.elko_super_tr_344b22fe_electrical_measurement",
        "name": "ELKO Super TR"
      },
      {
        "entity_id": "sensor.elko_super_tr_344b22fe_electrical_measurement_apparent_power",
        "name": "ELKO Super TR"
      },
      {
        "entity_id": "sensor.elko_super_tr_344b22fe_electrical_measurement_rms_current",
        "name": "ELKO Super TR"
      },
      {
        "entity_id": "sensor.elko_super_tr_344b22fe_electrical_measurement_rms_voltage",
        "name": "ELKO Super TR"
      },
      {
        "entity_id": "sensor.elko_super_tr_344b22fe_electrical_measurement_ac_frequency",
        "name": "ELKO Super TR"
      },
      {
        "entity_id": "sensor.elko_super_tr_344b22fe_electrical_measurement_power_factor",
        "name": "ELKO Super TR"
      },
      {
        "entity_id": "sensor.elko_super_tr_344b22fe_thermostat_hvac_action",
        "name": "ELKO Super TR"
      }
    ],
    "neighbors": [
      {
        "device_type": "Coordinator",
        "rx_on_when_idle": "On",
        "relationship": "Parent",
        "extended_pan_id": "**REDACTED**",
        "ieee": "**REDACTED**",
        "nwk": "0x0000",
        "permit_joining": "Unknown",
        "depth": "0",
        "lqi": "255"
      },
      {
        "device_type": "Router",
        "rx_on_when_idle": "On",
        "relationship": "Sibling",
        "extended_pan_id": "**REDACTED**",
        "ieee": "**REDACTED**",
        "nwk": "0x2DEA",
        "permit_joining": "Unknown",
        "depth": "15",
        "lqi": "125"
      },
      {
        "device_type": "Router",
        "rx_on_when_idle": "On",
        "relationship": "Sibling",
        "extended_pan_id": "**REDACTED**",
        "ieee": "**REDACTED**",
        "nwk": "0x7947",
        "permit_joining": "Unknown",
        "depth": "15",
        "lqi": "118"
      },
      {
        "device_type": "Router",
        "rx_on_when_idle": "On",
        "relationship": "Sibling",
        "extended_pan_id": "**REDACTED**",
        "ieee": "**REDACTED**",
        "nwk": "0x79E5",
        "permit_joining": "Unknown",
        "depth": "15",
        "lqi": "72"
      },
      {
        "device_type": "Router",
        "rx_on_when_idle": "On",
        "relationship": "Sibling",
        "extended_pan_id": "**REDACTED**",
        "ieee": "**REDACTED**",
        "nwk": "0x8241",
        "permit_joining": "Unknown",
        "depth": "15",
        "lqi": "81"
      },
      {
        "device_type": "Router",
        "rx_on_when_idle": "On",
        "relationship": "Sibling",
        "extended_pan_id": "**REDACTED**",
        "ieee": "**REDACTED**",
        "nwk": "0x8888",
        "permit_joining": "Unknown",
        "depth": "15",
        "lqi": "151"
      },
      {
        "device_type": "Router",
        "rx_on_when_idle": "On",
        "relationship": "Sibling",
        "extended_pan_id": "**REDACTED**",
        "ieee": "**REDACTED**",
        "nwk": "0x88DE",
        "permit_joining": "Unknown",
        "depth": "15",
        "lqi": "93"
      },
      {
        "device_type": "Router",
        "rx_on_when_idle": "On",
        "relationship": "Sibling",
        "extended_pan_id": "**REDACTED**",
        "ieee": "**REDACTED**",
        "nwk": "0x97C9",
        "permit_joining": "Unknown",
        "depth": "15",
        "lqi": "100"
      },
      {
        "device_type": "Router",
        "rx_on_when_idle": "On",
        "relationship": "Sibling",
        "extended_pan_id": "**REDACTED**",
        "ieee": "**REDACTED**",
        "nwk": "0xC253",
        "permit_joining": "Unknown",
        "depth": "15",
        "lqi": "90"
      }
    ],
    "endpoint_names": [
      {
        "name": "THERMOSTAT"
      }
    ],
    "user_given_name": null,
    "device_reg_id": "22dc4bbe60414a0ebda147336f27daea",
    "area_id": "4504c49c9cab4ee9a2baaae74ae35325"
  }
}
```

</details>

<details>
<summary>Additional logs</summary>

```
2022-05-25 16:19:33 WARNING (MainThread) [homeassistant.components.zha.entity] climate.elko_super_tr_344b22fe_thermostat: can't set 'heat' mode. Supported modes are: [<HVACMode.OFF: 'off'>]
```

</details>

**Additional context**
