### ISSUE TITLE
[Device Support Request] Datek HLU2909K

### ISSUE THREAD

**Issue by overas** [zigpy/zha-device-handlers#1631]
**Is your feature request related to a problem? Please describe.**
Device joins zigbee network and it's recognized by home-assistant. 

In Norway the smart plug is sold as Apex smart plug 16A EU version https://shop.evasmart.no/produkt/smarthus/smart-plug#product-tabs1. It is also known as Datek HLU2909K.
Documentation: https://dsh.datek.no/smartplug/index.html and https://dsh.datek.no/SmartPlug/Apex_SmartPlug_UserManual.pdf
Zigbee2mqtt already support the device: https://www.zigbee2mqtt.io/devices/HLU2909K.html

Entities are created for:
On/Off switch: It works
Electrical power measurement (W): Values updated correctly.
Electrical measurement ac frequency (Hz): Values updated correctly.
Electrical measurement rms current (A): Values updated correctly.
Electrical measurement rms voltage (V): Values updated correctly.
Temperature (C, Celsius): Values updated correctly.
Electrical measurement power factor: Entity is created but values are never updated.

The problem is Electrical measurement power factor sensor which ZHA create as "sensor.datek_pop_dd6ba0fe_electrical_measurement_power_factor" with state "Unknown". I believe the sensor gives a lot of `WARNING (MainThread) [zigpy.zcl] [0x3B22:1:0xfeed] Unknown cluster command 42 b'` in the HA log.

![image](https://user-images.githubusercontent.com/37910044/175512123-425e975f-38c7-4e72-b6b2-7113995cc545.png)

![image](https://user-images.githubusercontent.com/37910044/175503653-fc7c9342-cdb3-416b-805c-a55bafa794c4.png)

**Describe the solution you'd like**
Please consider adding support for fixing the electrical measurement power factor.

<details>

<summary>Device signature</summary>

```yaml
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress|RxOnWhenIdle|MainsPowered|FullFunctionDevice: 142>, manufacturer_code=4919, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0009",
      "in_clusters": [
        "0x0000",
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0006",
        "0x0009",
        "0x0402",
        "0x0b04",
        "0x1000",
        "0xfee1",
        "0xfeed"
      ],
      "out_clusters": [
        "0x0003",
        "0x000a",
        "0x0019"
      ]
    },
    "242": {
      "profile_id": 41440,
      "device_type": "0x0066",
      "in_clusters": [
        "0x0021"
      ],
      "out_clusters": [
        "0x0021"
      ]
    }
  },
  "manufacturer": "Datek",
  "model": "PoP",
  "class": "zigpy.device.Device"
}
```

</details>

<details>

<summary>Diagnostic information</summary>

```yaml
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.6.7",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.9.12",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Oslo",
    "os_name": "Linux",
    "os_version": "5.15.45",
    "supervisor": "2022.05.3",
    "host_os": "Home Assistant OS 8.2",
    "docker_version": "20.10.14",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "frigate": {
      "version": "2.3",
      "requirements": []
    },
    "easee": {
      "version": "0.9.43",
      "requirements": [
        "pyeasee==0.7.44"
      ]
    },
    "pyscript": {
      "version": "1.3.3",
      "requirements": [
        "croniter==1.3.4",
        "watchdog==2.1.6"
      ]
    },
    "hacs": {
      "version": "1.25.5",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
    "nordpool": {
      "version": "0.0.7",
      "requirements": [
        "nordpool>=0.2"
      ]
    },
    "apsystems": {
      "version": "1.0.4",
      "requirements": [
        "mechanize==0.4.5"
      ]
    },
    "watchman": {
      "version": "0.5.1",
      "requirements": [
        "prettytable==3.0.0"
      ]
    }
  },
  "integration_manifest": {
    "domain": "zha",
    "name": "Zigbee Home Automation",
    "config_flow": true,
    "documentation": "https://www.home-assistant.io/integrations/zha",
    "requirements": [
      "bellows==0.30.0",
      "pyserial==3.5",
      "pyserial-asyncio==0.6",
      "zha-quirks==0.0.75",
      "zigpy-deconz==0.16.0",
      "zigpy==0.45.1",
      "zigpy-xbee==0.14.0",
      "zigpy-zigate==0.7.4",
      "zigpy-znp==0.7.0"
    ],
    "usb": [
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*2652*",
        "known_devices": [
          "slae.sh cc2652rb stick"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*sonoff*plus*",
        "known_devices": [
          "sonoff zigbee dongle plus"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*zigstar*",
        "known_devices": [
          "ZigStar Coordinators"
        ]
      },
      {
        "vid": "1CF1",
        "pid": "0030",
        "description": "*conbee*",
        "known_devices": [
          "Conbee II"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8A2A",
        "description": "*zigbee*",
        "known_devices": [
          "Nortek HUSBZB-1"
        ]
      },
      {
        "vid": "0403",
        "pid": "6015",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate+"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8B34",
        "description": "*bv 2010/10*",
        "known_devices": [
          "Bitron Video AV2010/10"
        ]
      }
    ],
    "codeowners": [
      "@dmulcahey",
      "@adminiuga"
    ],
    "zeroconf": [
      {
        "type": "_esphomelib._tcp.local.",
        "name": "tube*"
      },
      {
        "type": "_zigate-zigbee-gateway._tcp.local.",
        "name": "*zigate*"
      }
    ],
    "after_dependencies": [
      "usb",
      "zeroconf"
    ],
    "iot_class": "local_polling",
    "loggers": [
      "aiosqlite",
      "bellows",
      "crccheck",
      "pure_pcapy3",
      "zhaquirks",
      "zigpy",
      "zigpy_deconz",
      "zigpy_xbee",
      "zigpy_zigate",
      "zigpy_znp"
    ],
    "is_built_in": true
  },
  "data": {
    "ieee": "**REDACTED**",
    "nwk": 15138,
    "manufacturer": "Datek",
    "model": "PoP",
    "name": "Datek PoP",
    "quirk_applied": false,
    "quirk_class": "zigpy.device.Device",
    "manufacturer_code": 4919,
    "power_source": "Mains",
    "lqi": 102,
    "rssi": null,
    "last_seen": "2022-06-24T11:48:45",
    "available": true,
    "device_type": "Router",
    "signature": {
      "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress|RxOnWhenIdle|MainsPowered|FullFunctionDevice: 142>, manufacturer_code=4919, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
      "endpoints": {
        "1": {
          "profile_id": 260,
          "device_type": "0x0009",
          "in_clusters": [
            "0x0000",
            "0x0003",
            "0x0004",
            "0x0005",
            "0x0006",
            "0x0009",
            "0x0402",
            "0x0b04",
            "0x1000",
            "0xfee1",
            "0xfeed"
          ],
          "out_clusters": [
            "0x0003",
            "0x000a",
            "0x0019"
          ]
        },
        "242": {
          "profile_id": 41440,
          "device_type": "0x0066",
          "in_clusters": [
            "0x0021"
          ],
          "out_clusters": [
            "0x0021"
          ]
        }
      }
    },
    "entities": [
      {
        "entity_id": "button.datek_pop_dd6ba0fe_identify",
        "name": "Datek PoP"
      },
      {
        "entity_id": "select.datek_pop_dd6ba0fe_on_off_startuponoff",
        "name": "Datek PoP"
      },
      {
        "entity_id": "sensor.datek_pop_dd6ba0fe_electrical_measurement",
        "name": "Datek PoP"
      },
      {
        "entity_id": "sensor.datek_pop_dd6ba0fe_electrical_measurement_rms_current",
        "name": "Datek PoP"
      },
      {
        "entity_id": "sensor.datek_pop_dd6ba0fe_electrical_measurement_rms_voltage",
        "name": "Datek PoP"
      },
      {
        "entity_id": "sensor.datek_pop_dd6ba0fe_electrical_measurement_ac_frequency",
        "name": "Datek PoP"
      },
      {
        "entity_id": "sensor.datek_pop_dd6ba0fe_electrical_measurement_power_factor",
        "name": "Datek PoP"
      },
      {
        "entity_id": "sensor.datek_pop_dd6ba0fe_temperature",
        "name": "Datek PoP"
      },
      {
        "entity_id": "switch.datek_pop_dd6ba0fe_on_off",
        "name": "Datek PoP"
      }
    ],
    "neighbors": [
      {
        "device_type": "Router",
        "rx_on_when_idle": "On",
        "relationship": "Sibling",
        "extended_pan_id": "**REDACTED**",
        "ieee": "**REDACTED**",
        "nwk": "0x244F",
        "permit_joining": "Unknown",
        "depth": "15",
        "lqi": "63"
      },
      {
        "device_type": "Router",
        "rx_on_when_idle": "On",
        "relationship": "Sibling",
        "extended_pan_id": "**REDACTED**",
        "ieee": "**REDACTED**",
        "nwk": "0x4F40",
        "permit_joining": "Unknown",
        "depth": "15",
        "lqi": "60"
      },
      {
        "device_type": "Router",
        "rx_on_when_idle": "On",
        "relationship": "Sibling",
        "extended_pan_id": "**REDACTED**",
        "ieee": "**REDACTED**",
        "nwk": "0x5ABA",
        "permit_joining": "Unknown",
        "depth": "15",
        "lqi": "111"
      },
      {
        "device_type": "Router",
        "rx_on_when_idle": "On",
        "relationship": "Sibling",
        "extended_pan_id": "**REDACTED**",
        "ieee": "**REDACTED**",
        "nwk": "0x6EDC",
        "permit_joining": "Unknown",
        "depth": "15",
        "lqi": "140"
      },
      {
        "device_type": "Router",
        "rx_on_when_idle": "On",
        "relationship": "Sibling",
        "extended_pan_id": "**REDACTED**",
        "ieee": "**REDACTED**",
        "nwk": "0x7B0C",
        "permit_joining": "Unknown",
        "depth": "15",
        "lqi": "80"
      },
      {
        "device_type": "Router",
        "rx_on_when_idle": "On",
        "relationship": "Sibling",
        "extended_pan_id": "**REDACTED**",
        "ieee": "**REDACTED**",
        "nwk": "0xABE0",
        "permit_joining": "Unknown",
        "depth": "15",
        "lqi": "105"
      },
      {
        "device_type": "Router",
        "rx_on_when_idle": "On",
        "relationship": "Sibling",
        "extended_pan_id": "**REDACTED**",
        "ieee": "**REDACTED**",
        "nwk": "0xB47D",
        "permit_joining": "Unknown",
        "depth": "15",
        "lqi": "196"
      },
      {
        "device_type": "Router",
        "rx_on_when_idle": "On",
        "relationship": "Parent",
        "extended_pan_id": "**REDACTED**",
        "ieee": "**REDACTED**",
        "nwk": "0xBD79",
        "permit_joining": "Unknown",
        "depth": "15",
        "lqi": "233"
      },
      {
        "device_type": "Router",
        "rx_on_when_idle": "On",
        "relationship": "Sibling",
        "extended_pan_id": "**REDACTED**",
        "ieee": "**REDACTED**",
        "nwk": "0xBF4B",
        "permit_joining": "Unknown",
        "depth": "15",
        "lqi": "114"
      },
      {
        "device_type": "Router",
        "rx_on_when_idle": "On",
        "relationship": "Sibling",
        "extended_pan_id": "**REDACTED**",
        "ieee": "**REDACTED**",
        "nwk": "0xCDA0",
        "permit_joining": "Unknown",
        "depth": "15",
        "lqi": "76"
      },
      {
        "device_type": "Router",
        "rx_on_when_idle": "On",
        "relationship": "Sibling",
        "extended_pan_id": "**REDACTED**",
        "ieee": "**REDACTED**",
        "nwk": "0xD4CC",
        "permit_joining": "Unknown",
        "depth": "15",
        "lqi": "136"
      },
      {
        "device_type": "Router",
        "rx_on_when_idle": "On",
        "relationship": "Sibling",
        "extended_pan_id": "**REDACTED**",
        "ieee": "**REDACTED**",
        "nwk": "0xD99B",
        "permit_joining": "Unknown",
        "depth": "15",
        "lqi": "138"
      },
      {
        "device_type": "Router",
        "rx_on_when_idle": "On",
        "relationship": "Sibling",
        "extended_pan_id": "**REDACTED**",
        "ieee": "**REDACTED**",
        "nwk": "0xF3C1",
        "permit_joining": "Unknown",
        "depth": "15",
        "lqi": "71"
      },
      {
        "device_type": "Router",
        "rx_on_when_idle": "On",
        "relationship": "Sibling",
        "extended_pan_id": "**REDACTED**",
        "ieee": "**REDACTED**",
        "nwk": "0xFC26",
        "permit_joining": "Unknown",
        "depth": "15",
        "lqi": "94"
      },
      {
        "device_type": "Router",
        "rx_on_when_idle": "On",
        "relationship": "Sibling",
        "extended_pan_id": "**REDACTED**",
        "ieee": "**REDACTED**",
        "nwk": "0xFDD5",
        "permit_joining": "Unknown",
        "depth": "15",
        "lqi": "74"
      }
    ],
    "endpoint_names": [
      {
        "name": "MAIN_POWER_OUTLET"
      },
      {
        "name": "unknown 102 device_type of 0xa1e0 profile id"
      }
    ],
    "user_given_name": null,
    "device_reg_id": "15372fe168724e74df5a49d181287b35",
    "area_id": null
  }
}
```

</details>

<details>
<summary>Additional logs</summary>

```
2022-06-24 11:13:05 WARNING (MainThread) [zigpy.zcl] [0x5E0E:1:0xfeed] Unknown cluster command 42 b''
2022-06-24 11:13:08 WARNING (MainThread) [zigpy.zcl] [0x3B22:1:0xfeed] Unknown cluster command 42 b''
```

</details>

**Additional context**
![image](https://user-images.githubusercontent.com/37910044/175511289-c1db00bf-97db-45d0-84ee-8469d48595ec.png)
![image](https://user-images.githubusercontent.com/37910044/175511343-10e9ea22-a54d-400b-bb4b-0785f1cf24ad.png)
![image](https://user-images.githubusercontent.com/37910044/175511392-75e80118-7fbb-4ca1-b40f-c0970f42aa92.png)

**Comment by andersi** [comment]
Installed Home Assistant 2023.8.4 today. Still the same problem.

`Logger: zigpy.zcl
Source: runner.py:179
First occurred: 11:54:23 (406 occurrences)
Last logged: 15:38:16

[0x8320:1:0xfeed] Unknown cluster command 42 b''
[0xDE7F:1:0xfeed] Unknown cluster command 42 b''`

**Comment by overas** [comment]
As a workaround i filtered the log to avoid these messages. I hope somebody make a zha quirk for Datek powerplug.
```
logger:
  default: info
  logs:
    custom_components.pyscript: info
  filters:
    zigpy.zcl:
      - "Unknown cluster command 42 b"
      - "Unknown cluster command 6 b"
```
