### ISSUE TITLE
[Device Support Request] lumi.plug.maus01 (ZNCZ12LM)

### ISSUE THREAD

**Issue by ghost** [zigpy/zha-device-handlers#1654]
I have seen similar devices listed as issues here but not quite this exact model number ZNCZ12LM.
It is an [Aqara Smart Plug](https://www.amazon.com/gp/aw/d/B07CJ2MM6Z?psc=1&ref=ppx_pop_mob_b_asin_title). It will join to the network and can be controlled but much of the energy reporting metrics are showing as unavailable

<details>

<summary>Device signature</summary>

```yaml
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress|RxOnWhenIdle|MainsPowered|FullFunctionDevice: 142>, manufacturer_code=4447, maximum_buffer_size=127, maximum_incoming_transfer_size=100, server_mask=0, maximum_outgoing_transfer_size=100, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0051",
      "in_clusters": [
        "0x0000",
        "0x0001",
        "0x0002",
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0006",
        "0x000a",
        "0x0010",
        "0x0b04"
      ],
      "out_clusters": [
        "0x000a",
        "0x0019"
      ]
    },
    "2": {
      "profile_id": 260,
      "device_type": "0x0009",
      "in_clusters": [
        "0x000c"
      ],
      "out_clusters": [
        "0x0004",
        "0x000c"
      ]
    },
    "3": {
      "profile_id": 260,
      "device_type": "0x0053",
      "in_clusters": [
        "0x000c"
      ],
      "out_clusters": [
        "0x000c"
      ]
    },
    "100": {
      "profile_id": 260,
      "device_type": "0x0107",
      "in_clusters": [
        "0x000f"
      ],
      "out_clusters": [
        "0x0004",
        "0x000f"
      ]
    }
  },
  "manufacturer": "LUMI",
  "model": "lumi.plug.maus01",
  "class": "zhaquirks.xiaomi.aqara.plug_maus01.Plug"
}
```

</details>

<details>

<summary>Diagnostic information</summary>

```yaml
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.7.4",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.5",
    "docker": true,
    "arch": "aarch64",
    "timezone": "America/New_York",
    "os_name": "Linux",
    "os_version": "5.15.32-v8",
    "supervisor": "2022.07.0",
    "host_os": "Home Assistant OS 8.2",
    "docker_version": "20.10.14",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "alarmo": {
      "version": "v1.9.4",
      "requirements": []
    },
    "hacs": {
      "version": "1.26.2",
      "requirements": [
        "aiogithubapi\u003e\u003d22.2.4"
      ]
    },
    "noonlight": {
      "version": "1.0.2",
      "requirements": [
        "noonlight\u003d\u003d0.1.1"
      ]
    },
    "keymaster": {
      "version": "v0.0.82",
      "requirements": []
    },
    "scheduler": {
      "version": "v0.0.0",
      "requirements": []
    },
    "powercalc": {
      "version": "v0.22.1",
      "requirements": [
        "numpy\u003e\u003d1.21.1"
      ]
    }
  },
  "integration_manifest": {
    "domain": "zha",
    "name": "Zigbee Home Automation",
    "config_flow": true,
    "documentation": "https://www.home-assistant.io/integrations/zha",
    "requirements": [
      "bellows\u003d\u003d0.31.1",
      "pyserial\u003d\u003d3.5",
      "pyserial-asyncio\u003d\u003d0.6",
      "zha-quirks\u003d\u003d0.0.77",
      "zigpy-deconz\u003d\u003d0.18.0",
      "zigpy\u003d\u003d0.47.2",
      "zigpy-xbee\u003d\u003d0.15.0",
      "zigpy-zigate\u003d\u003d0.9.0",
      "zigpy-znp\u003d\u003d0.8.1"
    ],
    "usb": [
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*2652*",
        "known_devices": [
          "slae.sh cc2652rb stick"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*sonoff*plus*",
        "known_devices": [
          "sonoff zigbee dongle plus"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*zigstar*",
        "known_devices": [
          "ZigStar Coordinators"
        ]
      },
      {
        "vid": "1CF1",
        "pid": "0030",
        "description": "*conbee*",
        "known_devices": [
          "Conbee II"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8A2A",
        "description": "*zigbee*",
        "known_devices": [
          "Nortek HUSBZB-1"
        ]
      },
      {
        "vid": "0403",
        "pid": "6015",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate+"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8B34",
        "description": "*bv 2010/10*",
        "known_devices": [
          "Bitron Video AV2010/10"
        ]
      }
    ],
    "codeowners": [
      "@dmulcahey",
      "@adminiuga"
    ],
    "zeroconf": [
      {
        "type": "_esphomelib._tcp.local.",
        "name": "tube*"
      },
      {
        "type": "_zigate-zigbee-gateway._tcp.local.",
        "name": "*zigate*"
      }
    ],
    "after_dependencies": [
      "onboarding",
      "usb",
      "zeroconf"
    ],
    "iot_class": "local_polling",
    "loggers": [
      "aiosqlite",
      "bellows",
      "crccheck",
      "pure_pcapy3",
      "zhaquirks",
      "zigpy",
      "zigpy_deconz",
      "zigpy_xbee",
      "zigpy_zigate",
      "zigpy_znp"
    ],
    "is_built_in": true
  },
  "data": {
    "ieee": "**REDACTED**",
    "nwk": 33253,
    "manufacturer": "LUMI",
    "model": "lumi.plug.maus01",
    "name": "LUMI lumi.plug.maus01",
    "quirk_applied": true,
    "quirk_class": "zhaquirks.xiaomi.aqara.plug_maus01.Plug",
    "manufacturer_code": 4447,
    "power_source": "Mains",
    "lqi": 255,
    "rssi": -60,
    "last_seen": "2022-07-15T00:04:34",
    "available": true,
    "device_type": "Router",
    "signature": {
      "node_descriptor": "NodeDescriptor(logical_type\u003d\u003cLogicalType.Router: 1\u003e, complex_descriptor_available\u003d0, user_descriptor_available\u003d0, reserved\u003d0, aps_flags\u003d0, frequency_band\u003d\u003cFrequencyBand.Freq2400MHz: 8\u003e, mac_capability_flags\u003d\u003cMACCapabilityFlags.AllocateAddress|RxOnWhenIdle|MainsPowered|FullFunctionDevice: 142\u003e, manufacturer_code\u003d4447, maximum_buffer_size\u003d127, maximum_incoming_transfer_size\u003d100, server_mask\u003d0, maximum_outgoing_transfer_size\u003d100, descriptor_capability_field\u003d\u003cDescriptorCapability.NONE: 0\u003e, *allocate_address\u003dTrue, *is_alternate_pan_coordinator\u003dFalse, *is_coordinator\u003dFalse, *is_end_device\u003dFalse, *is_full_function_device\u003dTrue, *is_mains_powered\u003dTrue, *is_receiver_on_when_idle\u003dTrue, *is_router\u003dTrue, *is_security_capable\u003dFalse)",
      "endpoints": {
        "1": {
          "profile_id": 260,
          "device_type": "0x0051",
          "in_clusters": [
            "0x0000",
            "0x0001",
            "0x0002",
            "0x0003",
            "0x0004",
            "0x0005",
            "0x0006",
            "0x000a",
            "0x0010",
            "0x0b04"
          ],
          "out_clusters": [
            "0x000a",
            "0x0019"
          ]
        },
        "2": {
          "profile_id": 260,
          "device_type": "0x0009",
          "in_clusters": [
            "0x000c"
          ],
          "out_clusters": [
            "0x0004",
            "0x000c"
          ]
        },
        "3": {
          "profile_id": 260,
          "device_type": "0x0053",
          "in_clusters": [
            "0x000c"
          ],
          "out_clusters": [
            "0x000c"
          ]
        },
        "100": {
          "profile_id": 260,
          "device_type": "0x0107",
          "in_clusters": [
            "0x000f"
          ],
          "out_clusters": [
            "0x0004",
            "0x000f"
          ]
        }
      }
    },
    "entities": [
      {
        "entity_id": "binary_sensor.lumi_lumi_plug_maus01_binary_input",
        "name": "LUMI lumi.plug.maus01"
      },
      {
        "entity_id": "button.lumi_lumi_plug_maus01_identify",
        "name": "LUMI lumi.plug.maus01"
      },
      {
        "entity_id": "sensor.lumi_lumi_plug_maus01_electrical_measurement_power_factor",
        "name": "LUMI lumi.plug.maus01"
      },
      {
        "entity_id": "sensor.lumi_lumi_plug_maus01_device_temperature",
        "name": "LUMI lumi.plug.maus01"
      },
      {
        "entity_id": "sensor.lumi_lumi_plug_maus01_analog_input",
        "name": "LUMI lumi.plug.maus01"
      },
      {
        "entity_id": "sensor.lumi_lumi_plug_maus01_analog_input_2",
        "name": "LUMI lumi.plug.maus01"
      },
      {
        "entity_id": "switch.lumi_lumi_plug_maus01_on_off",
        "name": "LUMI lumi.plug.maus01"
      }
    ],
    "neighbors": [],
    "endpoint_names": [
      {
        "name": "SMART_PLUG"
      },
      {
        "name": "MAIN_POWER_OUTLET"
      },
      {
        "name": "METER_INTERFACE"
      },
      {
        "name": "OCCUPANCY_SENSOR"
      }
    ],
    "user_given_name": "Living Room Wallflower",
    "device_reg_id": "3a508014a579c95a88a0e5fc1478d5a1",
    "area_id": "living_room",
    "cluster_details": {
      "1": {
        "device_type": {
          "name": "SMART_PLUG",
          "id": 81
        },
        "profile_id": 260,
        "in_clusters": {
          "0x0000": {
            "endpoint_attribute": "basic",
            "attributes": {
              "0x0004": {
                "attribute_name": "manufacturer",
                "value": "LUMI"
              },
              "0x0005": {
                "attribute_name": "model",
                "value": "lumi.plug.maus01"
              }
            },
            "unsupported_attributes": {}
          },
          "0x0001": {
            "endpoint_attribute": "power",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0002": {
            "endpoint_attribute": "device_temperature",
            "attributes": {
              "0x0000": {
                "attribute_name": "current_temperature",
                "value": 3800
              }
            },
            "unsupported_attributes": {}
          },
          "0x0004": {
            "endpoint_attribute": "groups",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0003": {
            "endpoint_attribute": "identify",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0006": {
            "endpoint_attribute": "on_off",
            "attributes": {
              "0x0000": {
                "attribute_name": "on_off",
                "value": 1
              }
            },
            "unsupported_attributes": {}
          },
          "0x0005": {
            "endpoint_attribute": "scenes",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0010": {
            "endpoint_attribute": "binary_output",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x000a": {
            "endpoint_attribute": "time",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0b04": {
            "endpoint_attribute": "electrical_measurement",
            "attributes": {
              "0x0304": {
                "attribute_name": "total_active_power",
                "value": 0.009568437933921814
              },
              "0x050b": {
                "attribute_name": "active_power",
                "value": 1.9700000286102295
              }
            },
            "unsupported_attributes": {
              "0x0300": {
                "attribute_name": "ac_frequency"
              },
              "0x0302": {
                "attribute_name": "ac_frequency_max"
              },
              "0x0505": {
                "attribute_name": "rms_voltage"
              },
              "0x0508": {
                "attribute_name": "rms_current"
              },
              "0x050a": {
                "attribute_name": "rms_current_max"
              },
              "0x050b": {
                "attribute_name": "active_power"
              },
              "0x050d": {
                "attribute_name": "active_power_max"
              },
              "0x0507": {
                "attribute_name": "rms_voltage_max"
              },
              "0x050f": {
                "attribute_name": "apparent_power"
              }
            }
          }
        },
        "out_clusters": {
          "0x0019": {
            "endpoint_attribute": "ota",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x000a": {
            "endpoint_attribute": "time",
            "attributes": {},
            "unsupported_attributes": {}
          }
        }
      },
      "2": {
        "device_type": {
          "name": "MAIN_POWER_OUTLET",
          "id": 9
        },
        "profile_id": 260,
        "in_clusters": {
          "0x000c": {
            "endpoint_attribute": "analog_input",
            "attributes": {
              "0x0055": {
                "attribute_name": "present_value",
                "value": 1.9199999570846558
              }
            },
            "unsupported_attributes": {}
          }
        },
        "out_clusters": {
          "0x000c": {
            "endpoint_attribute": "analog_input",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0004": {
            "endpoint_attribute": "groups",
            "attributes": {},
            "unsupported_attributes": {}
          }
        }
      },
      "3": {
        "device_type": {
          "name": "METER_INTERFACE",
          "id": 83
        },
        "profile_id": 260,
        "in_clusters": {
          "0x000c": {
            "endpoint_attribute": "analog_input",
            "attributes": {},
            "unsupported_attributes": {}
          }
        },
        "out_clusters": {
          "0x000c": {
            "endpoint_attribute": "analog_input",
            "attributes": {},
            "unsupported_attributes": {}
          }
        }
      },
      "100": {
        "device_type": {
          "name": "OCCUPANCY_SENSOR",
          "id": 263
        },
        "profile_id": 260,
        "in_clusters": {
          "0x000f": {
            "endpoint_attribute": "binary_input",
            "attributes": {},
            "unsupported_attributes": {}
          }
        },
        "out_clusters": {
          "0x000f": {
            "endpoint_attribute": "binary_input",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0004": {
            "endpoint_attribute": "groups",
            "attributes": {},
            "unsupported_attributes": {}
          }
        }
      }
    }
  }
}
```

</details>

<details>
<summary>Additional logs</summary>

```
Paste any additional debug logs here.
Don't remove the extra line breaks outside the ``` marks.
```

</details>

**Additional context**
