### ISSUE TITLE
[Device Support Request] Support temperature calibration for TuyaThermostat/MoesBHTThermostat

### ISSUE THREAD

**Issue by BenPru** [zigpy/zha-device-handlers#1669]
**Is your feature request related to a problem? Please describe.**
Under "Manage clusters" -> cluster "MoesBHTThermostat" the attribute "local_temperature_calibration (id: 0x0010)" is available.
In my case I have to calibrate the value -3 C°. For example the thermostat measure is 23 C° but the real temp is 20 C°.
If I send a value < 0 the following error occurs:
2022-07-30 22:41:18 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [2573410488] Error handling message: value must be at least 0 for dictionary value @ data['manufacturer']. Got -16 (invalid_format)
2022-07-30 22:41:29 ERROR (MainThread) [zigpy.zcl] [0x9846:1:0x0201] Failed to convert attribute 0x0010 from  (<class 'str'>) to type <class 'zigpy.types.basic.int8s'>: invalid literal for int() with base 10: ''
If I send a value > 0 the following error occurs:
2022-07-30 22:46:08 ERROR (MainThread) [zigpy.zcl] [0x9846:1:0x0201] Failed to convert attribute 0x0010 from  (<class 'str'>) to type <class 'zigpy.types.basic.int8s'>: invalid literal for int() with base 10: ''

**Describe the solution you'd like**
Currently it is not possible to set the local temp calibration value.
It is nice to calibrate the temp of the thermostat.

<details>

<summary>Device signature</summary>

```yaml
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress|RxOnWhenIdle|MainsPowered|FullFunctionDevice: 142>, manufacturer_code=4098, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0301",
      "in_clusters": [
        "0x0000",
        "0x0004",
        "0x0005",
        "0x0201",
        "0x0204",
        "0xef00"
      ],
      "out_clusters": [
        "0x000a",
        "0x0019"
      ]
    }
  },
  "manufacturer": "_TZE200_aoclfnxz",
  "model": "TS0601",
  "class": "electric_heating.MoesBHT"
}
```

</details>

<details>

<summary>Diagnostic information</summary>

```yaml
{
  "home_assistant": {
    "installation_type": "Home Assistant Container",
    "version": "2022.7.7",
    "dev": false,
    "hassio": false,
    "virtualenv": false,
    "python_version": "3.10.5",
    "docker": true,
    "arch": "armv7l",
    "timezone": "Europe/Berlin",
    "os_name": "Linux",
    "os_version": "5.10.103-v7l+",
    "run_as_root": true
  },
  "custom_components": {
    "tinkerforge_switch": {
      "version": "2021.03.18",
      "requirements": [
        "tinkerforge>=2.1.26"
      ]
    },
    "fontawesome": {
      "version": "2.1.5",
      "requirements": []
    },
    "hacs": {
      "version": "1.26.2",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
    "multiscrape": {
      "version": "2.2.0",
      "requirements": [
        "lxml",
        "beautifulsoup4==4.9.1"
      ]
    },
    "luxtronik": {
      "version": "2022.05.04",
      "requirements": [
        "luxtronik==0.3.9"
      ]
    },
    "novus300": {
      "version": "2021.03.17",
      "requirements": [
        "tinkerforge>=2.1.24",
        "pyserial>=3.4",
        "pyserial-asyncio>=0.4"
      ]
    },
    "simpleicons": {
      "version": "v2.0.0",
      "requirements": [
        "simpleicons==6.16.0"
      ]
    },
    "luxtronik_sensor": {
      "version": "2021.11.22",
      "requirements": [
        "luxtronik==0.3.9"
      ]
    },
    "drkblutspende": {
      "version": "0.1.8",
      "requirements": [
        "feedparser>=6.0.8"
      ]
    },
    "favicon": {
      "version": "10.4",
      "requirements": []
    },
    "novus300bus": {
      "version": "2021.09.21",
      "requirements": [
        "pyserial>=3.4",
        "pyserial-asyncio>=0.6"
      ]
    },
    "iaquk": {
      "version": "1.6.2",
      "requirements": []
    }
  },
  "integration_manifest": {
    "domain": "zha",
    "name": "Zigbee Home Automation",
    "config_flow": true,
    "documentation": "https://www.home-assistant.io/integrations/zha",
    "requirements": [
      "bellows==0.31.1",
      "pyserial==3.5",
      "pyserial-asyncio==0.6",
      "zha-quirks==0.0.77",
      "zigpy-deconz==0.18.0",
      "zigpy==0.47.3",
      "zigpy-xbee==0.15.0",
      "zigpy-zigate==0.9.0",
      "zigpy-znp==0.8.1"
    ],
    "usb": [
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*2652*",
        "known_devices": [
          "slae.sh cc2652rb stick"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*sonoff*plus*",
        "known_devices": [
          "sonoff zigbee dongle plus"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*zigstar*",
        "known_devices": [
          "ZigStar Coordinators"
        ]
      },
      {
        "vid": "1CF1",
        "pid": "0030",
        "description": "*conbee*",
        "known_devices": [
          "Conbee II"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8A2A",
        "description": "*zigbee*",
        "known_devices": [
          "Nortek HUSBZB-1"
        ]
      },
      {
        "vid": "0403",
        "pid": "6015",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate+"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8B34",
        "description": "*bv 2010/10*",
        "known_devices": [
          "Bitron Video AV2010/10"
        ]
      }
    ],
    "codeowners": [
      "@dmulcahey",
      "@adminiuga"
    ],
    "zeroconf": [
      {
        "type": "_esphomelib._tcp.local.",
        "name": "tube*"
      },
      {
        "type": "_zigate-zigbee-gateway._tcp.local.",
        "name": "*zigate*"
      }
    ],
    "after_dependencies": [
      "onboarding",
      "usb",
      "zeroconf"
    ],
    "iot_class": "local_polling",
    "loggers": [
      "aiosqlite",
      "bellows",
      "crccheck",
      "pure_pcapy3",
      "zhaquirks",
      "zigpy",
      "zigpy_deconz",
      "zigpy_xbee",
      "zigpy_zigate",
      "zigpy_znp"
    ],
    "is_built_in": true
  },
  "data": {
    "config": {
      "enable_quirks": true,
      "custom_quirks_path": "/config/extraconfig/custom_zha_quirks/",
      "zigpy_config": {
        "ota": {
          "ikea_provider": true,
          "ledvance_provider": true
        },
        "database_path": "/config/zigbee.db",
        "device": {
          "path": "/dev/ttyACM0"
        }
      },
      "device_config": {}
    },
    "config_entry": {
      "entry_id": "9209670c795b11c796919ae64ced9f9f",
      "version": 3,
      "domain": "zha",
      "title": "ConBee II, s/n: DE2190618 - dresden elektronik ingenieurtechnik GmbH",
      "data": {
        "radio_type": "deconz",
        "device": {
          "path": "/dev/ttyACM0"
        }
      },
      "options": {
        "custom_configuration": {
          "zha_options": {
            "default_light_transition": 5,
            "enable_identify_on_join": true,
            "consider_unavailable_battery": 21600,
            "consider_unavailable_mains": 7200
          }
        }
      },
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": null,
      "disabled_by": null
    },
    "application_state": {
      "node_info": {
        "nwk": 0,
        "ieee": "**REDACTED**",
        "logical_type": 0
      },
      "network_info": {
        "extended_pan_id": "**REDACTED**",
        "pan_id": 7296,
        "nwk_update_id": 0,
        "nwk_manager_id": 0,
        "channel": 15,
        "channel_mask": 32768,
        "security_level": 5,
        "network_key": "**REDACTED**",
        "tc_link_key": {
          "key": [
            90,
            105,
            103,
            66,
            101,
            101,
            65,
            108,
            108,
            105,
            97,
            110,
            99,
            101,
            48,
            57
          ],
          "tx_counter": 0,
          "rx_counter": 0,
          "seq": 0,
          "partner_ieee": "**REDACTED**"
        },
        "key_table": [],
        "children": [],
        "nwk_addresses": {},
        "stack_specific": {},
        "metadata": {
          "deconz": {
            "version": 642385664
          }
        },
        "source": "zigpy-deconz@0.18.0"
      },
      "counters": {},
      "broadcast_counters": {},
      "device_counters": {},
      "group_counters": {}
    },
    "versions": {
      "bellows": "0.31.1",
      "zigpy": "0.47.3",
      "zigpy_deconz": "0.18.0",
      "zigpy_xbee": "0.15.0",
      "zigpy_znp": "0.8.1",
      "zigpy_zigate": "0.9.0",
      "zhaquirks": "0.0.77"
    }
  }
}
```

</details>

<details>
<summary>Additional logs</summary>

```
2022-07-30 22:41:18 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [2573410488] Error handling message: value must be at least 0 for dictionary value @ data['manufacturer']. Got -16 (invalid_format)
2022-07-30 22:41:29 ERROR (MainThread) [zigpy.zcl] [0x9846:1:0x0201] Failed to convert attribute 0x0010 from  (<class 'str'>) to type <class 'zigpy.types.basic.int8s'>: invalid literal for int() with base 10: ''
```

</details>

**Additional context**
