### ISSUE TITLE
[Device Support Request] Freint Electricity Meter Interface (Develco ZHEMI101)

### ISSUE THREAD

**Issue by RefineryX** [zigpy/zha-device-handlers#1681]
**Is your feature request related to a problem? Please describe.**
I believe that the Freint Electricity Meter Interface (Develco ZHEMI101) is already somewhat supported, meaning I can add it to my Home Assistant via ZHA. However, not all sensors and functionality is present....

**Describe the solution you'd like**
1. It appears that the battery sensor is supported but does get get exposed via ZHA. According to the manual, there is a status attribute on the metering cluster for reporting “Low battery”.

2. The device supports changing  the ```PulseConfiguration``` from the default ```1000``` to something else such as ```3200```. However, changing this in Home Assistant does not save and the default ```1000` remains. 

3. Upon adding the device, it exposes a ```Devicetemperature``` sensor. There is no features to allow the monitoring of the device.

<details>

<summary>Device signature</summary>

```yaml
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.0: 0>, mac_capability_flags=<MACCapabilityFlags.NONE: 0>, manufacturer_code=0, maximum_buffer_size=0, maximum_incoming_transfer_size=0, server_mask=0, maximum_outgoing_transfer_size=0, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=False, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 49353,
      "device_type": "0x0001",
      "in_clusters": [
        "0x0002",
        "0x0003",
        "0x0005"
      ],
      "out_clusters": [
        "0x0001"
      ]
    },
    "2": {
      "profile_id": 260,
      "device_type": "0x0007",
      "in_clusters": [
        "0x0000",
        "0x0003",
        "0x0702"
      ],
      "out_clusters": [
        "0x000a"
      ]
    }
  },
  "manufacturer": "Develco",
  "model": "ZHEMI101",
  "class": "zigpy.device.Device"
} ``` marks.
```

</details>

<details>

<summary>Diagnostic information</summary>

```yaml
{
  "home_assistant": {
    "installation_type": "Home Assistant Container",
    "version": "2022.8.0",
    "dev": false,
    "hassio": false,
    "virtualenv": false,
    "python_version": "3.10.5",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/London",
    "os_name": "Linux",
    "os_version": "5.10.0-16-amd64",
    "run_as_root": true
  },
  "custom_components": {
    "eufy_vacuum": {
      "version": "1.0.4",
      "requirements": [
        "cryptography"
      ]
    },
    "adaptive_lighting": {
      "version": "1.0.14",
      "requirements": []
    },
    "auth_header": {
      "version": "1.4",
      "requirements": []
    },
    "dyson_local": {
      "version": "0.16.4-4",
      "requirements": [
        "libdyson==0.8.11"
      ]
    }
  },
  "integration_manifest": {
    "domain": "zha",
    "name": "Zigbee Home Automation",
    "config_flow": true,
    "documentation": "https://www.home-assistant.io/integrations/zha",
    "requirements": [
      "bellows==0.31.2",
      "pyserial==3.5",
      "pyserial-asyncio==0.6",
      "zha-quirks==0.0.78",
      "zigpy-deconz==0.18.0",
      "zigpy==0.48.0",
      "zigpy-xbee==0.15.0",
      "zigpy-zigate==0.9.0",
      "zigpy-znp==0.8.1"
    ],
    "usb": [
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*2652*",
        "known_devices": [
          "slae.sh cc2652rb stick"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*sonoff*plus*",
        "known_devices": [
          "sonoff zigbee dongle plus"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*zigstar*",
        "known_devices": [
          "ZigStar Coordinators"
        ]
      },
      {
        "vid": "1CF1",
        "pid": "0030",
        "description": "*conbee*",
        "known_devices": [
          "Conbee II"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8A2A",
        "description": "*zigbee*",
        "known_devices": [
          "Nortek HUSBZB-1"
        ]
      },
      {
        "vid": "0403",
        "pid": "6015",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate+"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8B34",
        "description": "*bv 2010/10*",
        "known_devices": [
          "Bitron Video AV2010/10"
        ]
      }
    ],
    "codeowners": [
      "@dmulcahey",
      "@adminiuga",
      "@puddly"
    ],
    "zeroconf": [
      {
        "type": "_esphomelib._tcp.local.",
        "name": "tube*"
      },
      {
        "type": "_zigate-zigbee-gateway._tcp.local.",
        "name": "*zigate*"
      }
    ],
    "after_dependencies": [
      "onboarding",
      "usb",
      "zeroconf"
    ],
    "iot_class": "local_polling",
    "loggers": [
      "aiosqlite",
      "bellows",
      "crccheck",
      "pure_pcapy3",
      "zhaquirks",
      "zigpy",
      "zigpy_deconz",
      "zigpy_xbee",
      "zigpy_zigate",
      "zigpy_znp"
    ],
    "is_built_in": true
  },
  "data": {
    "ieee": "**REDACTED**",
    "nwk": 37751,
    "manufacturer": "Develco",
    "model": "ZHEMI101",
    "name": "Develco ZHEMI101",
    "quirk_applied": false,
    "quirk_class": "zigpy.device.Device",
    "manufacturer_code": 0,
    "power_source": "Battery or Unknown",
    "lqi": 255,
    "rssi": -49,
    "last_seen": "2022-08-04T20:46:32",
    "available": true,
    "device_type": "EndDevice",
    "signature": {
      "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.0: 0>, mac_capability_flags=<MACCapabilityFlags.NONE: 0>, manufacturer_code=0, maximum_buffer_size=0, maximum_incoming_transfer_size=0, server_mask=0, maximum_outgoing_transfer_size=0, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=False, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
      "endpoints": {
        "1": {
          "profile_id": 49353,
          "device_type": "0x0001",
          "in_clusters": [
            "0x0002",
            "0x0003",
            "0x0005"
          ],
          "out_clusters": [
            "0x0001"
          ]
        },
        "2": {
          "profile_id": 260,
          "device_type": "0x0007",
          "in_clusters": [
            "0x0000",
            "0x0003",
            "0x0702"
          ],
          "out_clusters": [
            "0x000a"
          ]
        }
      }
    },
    "active_coordinator": false,
    "entities": [
      {
        "entity_id": "sensor.develco_zhemi101_smartenergymetering",
        "name": "Develco ZHEMI101"
      },
      {
        "entity_id": "sensor.develco_zhemi101_smartenergysummation",
        "name": "Develco ZHEMI101"
      }
    ],
    "neighbors": [],
    "endpoint_names": [
      {
        "name": "COMBINED_INTERFACE"
      },
      {
        "name": "unknown 1 device_type of 0xc0c9 profile id"
      }
    ],
    "user_given_name": null,
    "device_reg_id": "6a43a27cb395251a11ce4663ac33c030",
    "area_id": "cupboard",
    "cluster_details": {
      "2": {
        "device_type": {
          "name": "COMBINED_INTERFACE",
          "id": 7
        },
        "profile_id": 260,
        "in_clusters": {
          "0x0000": {
            "endpoint_attribute": "basic",
            "attributes": {
              "0x0004": {
                "attribute_name": "manufacturer",
                "value": "Develco"
              },
              "0x0005": {
                "attribute_name": "model",
                "value": "ZHEMI101"
              }
            },
            "unsupported_attributes": {}
          },
          "0x0003": {
            "endpoint_attribute": "identify",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0702": {
            "endpoint_attribute": "smartenergy_metering",
            "attributes": {
              "0x0000": {
                "attribute_name": "current_summ_delivered",
                "value": 0
              },
              "0x0100": {
                "attribute_name": "current_tier1_summ_delivered",
                "value": 281474976710655
              },
              "0x0102": {
                "attribute_name": "current_tier2_summ_delivered",
                "value": 281474976710655
              },
              "0x0200": {
                "attribute_name": "status",
                "value": 0
              },
              "0x0300": {
                "attribute_name": "unit_of_measure",
                "value": 0
              },
              "0x0301": {
                "attribute_name": "multiplier",
                "value": 1
              },
              "0x0302": {
                "attribute_name": "divisor",
                "value": 1000
              },
              "0x0303": {
                "attribute_name": "summation_formatting",
                "value": 251
              },
              "0x0304": {
                "attribute_name": "demand_formatting",
                "value": 251
              },
              "0x0306": {
                "attribute_name": "metering_device_type",
                "value": 0
              },
              "0x0400": {
                "attribute_name": "instantaneous_demand",
                "value": 0
              }
            },
            "unsupported_attributes": {}
          }
        },
        "out_clusters": {
          "0x000a": {
            "endpoint_attribute": "time",
            "attributes": {},
            "unsupported_attributes": {}
          }
        }
      },
      "1": {
        "device_type": {
          "name": "unknown",
          "id": 1
        },
        "profile_id": 49353,
        "in_clusters": {
          "0x0002": {
            "endpoint_attribute": "device_temperature",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0003": {
            "endpoint_attribute": "identify",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0005": {
            "endpoint_attribute": "scenes",
            "attributes": {},
            "unsupported_attributes": {}
          }
        },
        "out_clusters": {
          "0x0001": {
            "endpoint_attribute": "power",
            "attributes": {},
            "unsupported_attributes": {}
          }
        }
      }
    }
  }
}
```

</details>

### **Additional context**

**Manufacturer Product Page:**
https://www.develcoproducts.com/products/meter-interfaces/external-meter-interface/

**Technical manual:**
https://www.develcoproducts.com/media/1782/zhemi101-technical-manual-external-meter-interface.pdf

### **Extracts from Manual**

**_Battery Information_**

<img width="818" alt="Screenshot 2022-08-04 at 20 56 00" src="https://user-images.githubusercontent.com/46373533/182941150-56bfcdd8-a5bd-4acc-b646-d0121097a090.png">

_**Pulse Confirmation Information:**_

<img width="813" alt="Screenshot 2022-08-04 at 20 56 55" src="https://user-images.githubusercontent.com/46373533/182941278-8f611bb6-e6ce-4b85-bb54-bfeec3a1aff9.png">

_**Pulse Confirmation in Home Assistant**_

_This does not save and the default remains present_

<img width="554" alt="Screenshot 2022-08-04 at 20 58 58" src="https://user-images.githubusercontent.com/46373533/182941579-1e2e1cfd-d8e3-4b1e-b715-fef70f22a7ec.png">

### _**HA Reconfig**_
<img width="499" alt="Screenshot 2022-08-04 at 21 02 31" src="https://user-images.githubusercontent.com/46373533/182943306-0ec4a7e0-3a01-496c-9124-f929fce729a4.png">

### Other info
I saw zigbee2mqtt added support recently
https://github.com/Koenkk/zigbee2mqtt/issues/8638
