### ISSUE TITLE
[Device Support Request] _TZE200_2cs6g9i7 - Brennenstuhl Zigbee Connect 01 

### ISSUE THREAD

**Issue by ich777** [zigpy/zha-device-handlers#1788]
**Is your feature request related to a problem? Please describe.**
I bought a [Brennenstuhl Heizkörperthermostat Zigbee Connect 01](https://www.conrad.at/de/p/brennenstuhl-heizkoerperthermostat-zigbee-connect-01-2523459.html) Valve.
This valve is able to be added into ZHA fine, but no quirk is associated with it. It only lists `Lqi` and `Rssi` but nothing else, the valve looks like [Alecto Thermostatic Radiator Valve](https://zigbee.blakadder.com/Alecto_SMART-HEAT10.html) and [essentials Smart Home Heizkörperthermostat Premium](https://zigbee.blakadder.com/essentials_120112.html) and others.

**Describe the solution you'd like**
Add a quirk to make the device working in HA

<details>

<summary>Device signature</summary>

```yaml
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4098, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0051",
      "in_clusters": [
        "0x0000",
        "0x0004",
        "0x0005",
        "0xef00"
      ],
      "out_clusters": [
        "0x000a",
        "0x0019"
      ]
    }
  },
  "manufacturer": "_TZE200_2cs6g9i7",
  "model": "TS0601",
  "class": "zigpy.device.Device"
}
```

</details>

<details>

<summary>Diagnostic information</summary>

```yaml
{
  "home_assistant": {
    "installation_type": "Home Assistant Core",
    "version": "2022.9.6",
    "dev": false,
    "hassio": false,
    "virtualenv": true,
    "python_version": "3.9.2",
    "docker": false,
    "arch": "x86_64",
    "timezone": "Europe/Vienna",
    "os_name": "Linux",
    "os_version": "5.19.9-Unraid",
    "run_as_root": false
  },
  "custom_components": {},
  "integration_manifest": {
    "domain": "zha",
    "name": "Zigbee Home Automation",
    "config_flow": true,
    "documentation": "https://www.home-assistant.io/integrations/zha",
    "requirements": [
      "bellows==0.33.1",
      "pyserial==3.5",
      "pyserial-asyncio==0.6",
      "zha-quirks==0.0.79",
      "zigpy-deconz==0.18.1",
      "zigpy==0.50.3",
      "zigpy-xbee==0.15.0",
      "zigpy-zigate==0.9.2",
      "zigpy-znp==0.8.2"
    ],
    "usb": [
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*2652*",
        "known_devices": [
          "slae.sh cc2652rb stick"
        ]
      },
      {
        "vid": "1A86",
        "pid": "55D4",
        "description": "*sonoff*plus*",
        "known_devices": [
          "sonoff zigbee dongle plus v2"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*sonoff*plus*",
        "known_devices": [
          "sonoff zigbee dongle plus"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*zigstar*",
        "known_devices": [
          "ZigStar Coordinators"
        ]
      },
      {
        "vid": "1CF1",
        "pid": "0030",
        "description": "*conbee*",
        "known_devices": [
          "Conbee II"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8A2A",
        "description": "*zigbee*",
        "known_devices": [
          "Nortek HUSBZB-1"
        ]
      },
      {
        "vid": "0403",
        "pid": "6015",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate+"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8B34",
        "description": "*bv 2010/10*",
        "known_devices": [
          "Bitron Video AV2010/10"
        ]
      }
    ],
    "codeowners": [
      "@dmulcahey",
      "@adminiuga",
      "@puddly"
    ],
    "zeroconf": [
      {
        "type": "_esphomelib._tcp.local.",
        "name": "tube*"
      },
      {
        "type": "_zigate-zigbee-gateway._tcp.local.",
        "name": "*zigate*"
      }
    ],
    "dependencies": [
      "file_upload"
    ],
    "after_dependencies": [
      "onboarding",
      "usb",
      "zeroconf"
    ],
    "iot_class": "local_polling",
    "loggers": [
      "aiosqlite",
      "bellows",
      "crccheck",
      "pure_pcapy3",
      "zhaquirks",
      "zigpy",
      "zigpy_deconz",
      "zigpy_xbee",
      "zigpy_zigate",
      "zigpy_znp"
    ],
    "is_built_in": true
  },
  "data": {
    "config": {
      "zigpy_config": {
        "ota": {
          "ikea_provider": true,
          "ledvance_provider": true,
          "salus_provider": true,
          "otau_directory": "/home/homeassistant/.homeassistant/zigpy_ota"
        },
        "database_path": "/home/homeassistant/.homeassistant/zigbee.db",
        "device": {
          "path": "socket://10.0.0.16:6638",
          "baudrate": 115200,
          "flow_control": null
        }
      },
      "device_config": {},
      "enable_quirks": true
    },
    "config_entry": {
      "entry_id": "af8d1df79d806a286af68b93d3d3abab",
      "version": 3,
      "domain": "zha",
      "title": "socket://10.0.0.16:6638",
      "data": {
        "device": {
          "path": "socket://10.0.0.16:6638",
          "baudrate": 115200,
          "flow_control": null
        },
        "radio_type": "znp"
      },
      "options": {
        "custom_configuration": {
          "zha_options": {
            "enable_identify_on_join": true,
            "consider_unavailable_battery": 21600,
            "consider_unavailable_mains": 7200
          },
          "zha_alarm_options": {
            "alarm_arm_requires_code": false,
            "alarm_failed_tries": 3,
            "alarm_master_code": "**REDACTED**"
          }
        }
      },
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": null,
      "disabled_by": null
    },
    "application_state": {
      "node_info": {
        "nwk": 0,
        "ieee": "**REDACTED**",
        "logical_type": 0
      },
      "network_info": {
        "extended_pan_id": "**REDACTED**",
        "pan_id": 13143,
        "nwk_update_id": 0,
        "nwk_manager_id": 0,
        "channel": 15,
        "channel_mask": 32768,
        "security_level": 5,
        "network_key": "**REDACTED**",
        "tc_link_key": {
          "key": [
            90,
            105,
            103,
            66,
            101,
            101,
            65,
            108,
            108,
            105,
            97,
            110,
            99,
            101,
            48,
            57
          ],
          "tx_counter": 0,
          "rx_counter": 0,
          "seq": 0,
          "partner_ieee": "**REDACTED**"
        },
        "key_table": [],
        "children": [],
        "nwk_addresses": {},
        "stack_specific": {
          "zstack": {
            "tclk_seed": "d9c338ae43eabab317501603fc28a684"
          }
        },
        "metadata": {
          "zstack": {
            "TransportRev": 2,
            "ProductId": 1,
            "MajorRel": 2,
            "MinorRel": 7,
            "MaintRel": 1,
            "CodeRevision": 20220219,
            "BootloaderBuildType": 0,
            "BootloaderRevision": null
          }
        },
        "source": "zigpy-znp@0.8.2"
      },
      "counters": {},
      "broadcast_counters": {},
      "device_counters": {},
      "group_counters": {}
    },
    "versions": {
      "bellows": "0.33.1",
      "zigpy": "0.50.3",
      "zigpy_deconz": "0.18.1",
      "zigpy_xbee": "0.15.0",
      "zigpy_znp": "0.8.2",
      "zigpy_zigate": "0.9.2",
      "zhaquirks": "0.0.79"
    }
  }
}
```

</details>

<details>
<summary>Additional logs</summary>

```
none
```

</details>

**Additional context**
Maybe someone could help with that...

Thanks!
