### ISSUE TITLE
[Device Support Request] TS0042 by _TZ3000_5e235jpa

### ISSUE THREAD

**Issue by Quelbazar** [zigpy/zha-device-handlers#1830]
**Is your feature request related to a problem? Please describe.**
Trying to add a "Moes zigbee Scene switch". Seems to be added as "TS0042 by _TZ3000_5e235jpa" and "Quirk: zhaquirks.tuya.ts0042.TuyaSmartRemote0042TO". However, only Battery, Lqi and Rssi entities appear.

**Describe the solution you'd like**
Have "buttons" entities (short press, long press / button 1, button 2)

<details>

<summary>Device signature</summary>

```yaml
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4098, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0006",
      "in_clusters": [
        "0x0000",
        "0x0001",
        "0x0006"
      ],
      "out_clusters": [
        "0x000a",
        "0x0019"
      ]
    },
    "2": {
      "profile_id": 260,
      "device_type": "0x0006",
      "in_clusters": [
        "0x0001",
        "0x0006"
      ],
      "out_clusters": []
    }
  },
  "manufacturer": "_TZ3000_5e235jpa",
  "model": "TS0042",
  "class": "zhaquirks.tuya.ts0042.TuyaSmartRemote0042TO"
}
```

</details>

<details>

<summary>Diagnostic information</summary>

```yaml
{
  "home_assistant": {
    "installation_type": "Home Assistant Supervised",
    "version": "2022.10.3",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.5",
    "docker": true,
    "arch": "armv7l",
    "timezone": "Europe/Zurich",
    "os_name": "Linux",
    "os_version": "5.15.61-v7l+",
    "supervisor": "2022.10.0",
    "host_os": "Raspbian GNU/Linux 11 (bullseye)",
    "docker_version": "20.10.18",
    "chassis": "",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "version": "1.28.0",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
    "meteo-swiss": {
      "version": "1.3",
      "requirements": [
        "hamsclient==0.2.3",
        "geopy>=2.0"
      ]
    },
    "husqvarna_automower": {
      "version": "2022.9.0",
      "requirements": [
        "aioautomower==2022.9.0",
        "geopy>=2.1.0",
        "numpy>=1.21.6",
        "Pillow>=9.1.1"
      ]
    }
  },
  "integration_manifest": {
    "domain": "zha",
    "name": "Zigbee Home Automation",
    "config_flow": true,
    "documentation": "https://www.home-assistant.io/integrations/zha",
    "requirements": [
      "bellows==0.34.2",
      "pyserial==3.5",
      "pyserial-asyncio==0.6",
      "zha-quirks==0.0.82",
      "zigpy-deconz==0.19.0",
      "zigpy==0.51.3",
      "zigpy-xbee==0.16.2",
      "zigpy-zigate==0.10.2",
      "zigpy-znp==0.9.1"
    ],
    "usb": [
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*2652*",
        "known_devices": [
          "slae.sh cc2652rb stick"
        ]
      },
      {
        "vid": "1A86",
        "pid": "55D4",
        "description": "*sonoff*plus*",
        "known_devices": [
          "sonoff zigbee dongle plus v2"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*sonoff*plus*",
        "known_devices": [
          "sonoff zigbee dongle plus"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*zigstar*",
        "known_devices": [
          "ZigStar Coordinators"
        ]
      },
      {
        "vid": "1CF1",
        "pid": "0030",
        "description": "*conbee*",
        "known_devices": [
          "Conbee II"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8A2A",
        "description": "*zigbee*",
        "known_devices": [
          "Nortek HUSBZB-1"
        ]
      },
      {
        "vid": "0403",
        "pid": "6015",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate+"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8B34",
        "description": "*bv 2010/10*",
        "known_devices": [
          "Bitron Video AV2010/10"
        ]
      }
    ],
    "codeowners": [
      "@dmulcahey",
      "@adminiuga",
      "@puddly"
    ],
    "zeroconf": [
      {
        "type": "_esphomelib._tcp.local.",
        "name": "tube*"
      },
      {
        "type": "_zigate-zigbee-gateway._tcp.local.",
        "name": "*zigate*"
      },
      {
        "type": "_zigstar_gw._tcp.local.",
        "name": "*zigstar*"
      }
    ],
    "dependencies": [
      "file_upload"
    ],
    "after_dependencies": [
      "onboarding",
      "usb",
      "zeroconf"
    ],
    "iot_class": "local_polling",
    "loggers": [
      "aiosqlite",
      "bellows",
      "crccheck",
      "pure_pcapy3",
      "zhaquirks",
      "zigpy",
      "zigpy_deconz",
      "zigpy_xbee",
      "zigpy_zigate",
      "zigpy_znp"
    ],
    "is_built_in": true
  },
  "data": {
    "ieee": "**REDACTED**",
    "nwk": 19204,
    "manufacturer": "_TZ3000_5e235jpa",
    "model": "TS0042",
    "name": "_TZ3000_5e235jpa TS0042",
    "quirk_applied": true,
    "quirk_class": "zhaquirks.tuya.ts0042.TuyaSmartRemote0042TO",
    "manufacturer_code": 4098,
    "power_source": "Battery or Unknown",
    "lqi": 255,
    "rssi": -49,
    "last_seen": "2022-10-15T17:38:25",
    "available": true,
    "device_type": "EndDevice",
    "signature": {
      "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4098, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
      "endpoints": {
        "1": {
          "profile_id": 260,
          "device_type": "0x0006",
          "in_clusters": [
            "0x0000",
            "0x0001",
            "0x0006"
          ],
          "out_clusters": [
            "0x000a",
            "0x0019"
          ]
        },
        "2": {
          "profile_id": 260,
          "device_type": "0x0006",
          "in_clusters": [
            "0x0001",
            "0x0006"
          ],
          "out_clusters": []
        }
      }
    },
    "active_coordinator": false,
    "entities": [
      {
        "entity_id": "sensor.tz3000_5e235jpa_ts0042_battery",
        "name": "_TZ3000_5e235jpa TS0042"
      }
    ],
    "neighbors": [],
    "endpoint_names": [
      {
        "name": "REMOTE_CONTROL"
      },
      {
        "name": "REMOTE_CONTROL"
      }
    ],
    "user_given_name": null,
    "device_reg_id": "cd5253cbc4bc2b88c645d4a40036bcc9",
    "area_id": null,
    "cluster_details": {
      "1": {
        "device_type": {
          "name": "REMOTE_CONTROL",
          "id": 6
        },
        "profile_id": 260,
        "in_clusters": {
          "0x0000": {
            "endpoint_attribute": "basic",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0001": {
            "endpoint_attribute": "power",
            "attributes": {
              "0x0020": {
                "attribute_name": "battery_voltage",
                "value": 30
              },
              "0x0021": {
                "attribute_name": "battery_percentage_remaining",
                "value": 200
              }
            },
            "unsupported_attributes": {
              "0x0031": {
                "attribute_name": "battery_size"
              },
              "0x0033": {
                "attribute_name": "battery_quantity"
              }
            }
          },
          "0x0006": {
            "endpoint_attribute": "TS004X_cluster",
            "attributes": {},
            "unsupported_attributes": {}
          }
        },
        "out_clusters": {
          "0x000a": {
            "endpoint_attribute": "time",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0019": {
            "endpoint_attribute": "ota",
            "attributes": {},
            "unsupported_attributes": {}
          }
        }
      },
      "2": {
        "device_type": {
          "name": "REMOTE_CONTROL",
          "id": 6
        },
        "profile_id": 260,
        "in_clusters": {
          "0x0001": {
            "endpoint_attribute": "power",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0006": {
            "endpoint_attribute": "TS004X_cluster",
            "attributes": {},
            "unsupported_attributes": {}
          }
        },
        "out_clusters": {}
      }
    }
  }
}
```

</details>

<details>
<summary>Additional logs</summary>
Include log

```
New device 0x4b04 (e0:79:8d:ff:fe:c9:e5:84) joined the network
[0x4b04] Scheduling initialization
Received frame on uninitialized device <Device model=None manuf=None nwk=0x4B04 ieee=e0:79:8d:ff:fe:c9:e5:84 is_initialized=False> from ep 0 to ep 0, cluster 19: b'\x88\x04K\x84\xe5\xc9\xfe\xff\x8dy\xe0\x80'
[0x4b04:zdo] ZDO request ZDOCmd.Device_annce: [0x4B04, e0:79:8d:ff:fe:c9:e5:84, 128]
Tries remaining: 3
[0x4b04] Requesting 'Node Descriptor'
Tries remaining: 2
[0x4b04] Extending timeout for 0x52 request
Received a packet: ZigbeePacket(src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x4B04), src_ep=0, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=0, source_route=None, extended_timeout=False, tsn=None, profile_id=0, cluster_id=32770, data=Serialized[b'R\x00\x04K\x02@\x80\x02\x10RR\x00\x00,R\x00\x00'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=255, rssi=-49)
Received frame on uninitialized device <Device model=None manuf=None nwk=0x4B04 ieee=e0:79:8d:ff:fe:c9:e5:84 is_initialized=False> from ep 0 to ep 0, cluster 32770: b'R\x00\x04K\x02@\x80\x02\x10RR\x00\x00,R\x00\x00'
[0x4b04] Got Node Descriptor: NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4098, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)
[0x4b04] Discovering endpoints
Tries remaining: 3
[0x4b04] Extending timeout for 0x54 request
Received a packet: ZigbeePacket(src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x4B04), src_ep=0, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=0, source_route=None, extended_timeout=False, tsn=None, profile_id=0, cluster_id=32773, data=Serialized[b'T\x00\x04K\x02\x01\x02'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=255, rssi=-49)
Received frame on uninitialized device <Device model=None manuf=None nwk=0x4B04 ieee=e0:79:8d:ff:fe:c9:e5:84 is_initialized=False> from ep 0 to ep 0, cluster 32773: b'T\x00\x04K\x02\x01\x02'
[0x4b04] Discovered endpoints: [1, 2]
[0x4b04] Initializing endpoints [<Endpoint id=1 in=[] out=[] status=<Status.NEW: 0>>, <Endpoint id=2 in=[] out=[] status=<Status.NEW: 0>>]
[0x4b04:1] Discovering endpoint information
Tries remaining: 3
[0x4b04] Extending timeout for 0x56 request
Received a packet: ZigbeePacket(src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x4B04), src_ep=0, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=0, source_route=None, extended_timeout=False, tsn=None, profile_id=0, cluster_id=32772, data=Serialized[b'V\x00\x04K\x12\x01\x04\x01\x00\x00\x01\x03\x00\x00\x01\x00\x06\x00\x02\x19\x00\n\x00'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=255, rssi=-49)
Received frame on uninitialized device <Device model=None manuf=None nwk=0x4B04 ieee=e0:79:8d:ff:fe:c9:e5:84 is_initialized=False> from ep 0 to ep 0, cluster 32772: b'V\x00\x04K\x12\x01\x04\x01\x00\x00\x01\x03\x00\x00\x01\x00\x06\x00\x02\x19\x00\n\x00'
[0x4b04:1] Discovered endpoint information: SizePrefixedSimpleDescriptor(endpoint=1, profile=260, device_type=0, device_version=1, input_clusters=[0, 1, 6], output_clusters=[25, 10])
[0x4b04:2] Discovering endpoint information
Tries remaining: 3
[0x4b04] Extending timeout for 0x58 request
Received a packet: ZigbeePacket(src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x4B04), src_ep=0, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=0, source_route=None, extended_timeout=False, tsn=None, profile_id=0, cluster_id=32772, data=Serialized[b'X\x00\x04K\x0c\x02\x04\x01\x00\x00\x01\x02\x01\x00\x06\x00\x00'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=255, rssi=-49)
Received frame on uninitialized device <Device model=None manuf=None nwk=0x4B04 ieee=e0:79:8d:ff:fe:c9:e5:84 is_initialized=False> from ep 0 to ep 0, cluster 32772: b'X\x00\x04K\x0c\x02\x04\x01\x00\x00\x01\x02\x01\x00\x06\x00\x00'
[0x4b04:2] Discovered endpoint information: SizePrefixedSimpleDescriptor(endpoint=2, profile=260, device_type=0, device_version=1, input_clusters=[1, 6], output_clusters=[])
[0x4B04:1:0x0000] Sending request header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.GLOBAL_COMMAND: 0>, is_manufacturer_specific=False, direction=<Direction.Server_to_Client: 0>, disable_default_response=0, reserved=0, *is_cluster=False, *is_general=True, *is_reply=False), tsn=90, command_id=<GeneralCommand.Read_Attributes: 0>, *direction=<Direction.Server_to_Client: 0>, *is_reply=False)
[0x4B04:1:0x0000] Sending request: Read_Attributes(attribute_ids=[4, 5])
[0x4b04] Extending timeout for 0x5a request
Received a packet: ZigbeePacket(src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x4B04), src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=1, source_route=None, extended_timeout=False, tsn=None, profile_id=260, cluster_id=0, data=Serialized[b'\x18Z\x01\x04\x00\x00B\x10_TZ3000_5e235jpa\x05\x00\x00B\x06TS0042'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=255, rssi=-49)
[0x4B04:1:0x0000] Received ZCL frame: b'\x18Z\x01\x04\x00\x00B\x10_TZ3000_5e235jpa\x05\x00\x00B\x06TS0042'
[0x4B04:1:0x0000] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.GLOBAL_COMMAND: 0>, is_manufacturer_specific=0, direction=<Direction.Client_to_Server: 1>, disable_default_response=1, reserved=0, *is_cluster=False, *is_general=True, *is_reply=True), tsn=90, command_id=1, *direction=<Direction.Client_to_Server: 1>, *is_reply=True)
[0x4B04:1:0x0000] Decoded ZCL frame: Basic:Read_Attributes_rsp(status_records=[ReadAttributeRecord(attrid=0x0004, status=<Status.SUCCESS: 0>, value=TypeValue(type=CharacterString, value='_TZ3000_5e235jpa')), ReadAttributeRecord(attrid=0x0005, status=<Status.SUCCESS: 0>, value=TypeValue(type=CharacterString, value='TS0042'))])
[0x4b04] Read model 'TS0042' and manufacturer '_TZ3000_5e235jpa' from <Endpoint id=1 in=[basic:0x0000, power:0x0001, on_off:0x0006] out=[ota:0x0019, time:0x000A] status=<Status.ZDO_INIT: 1>>
[0x4b04] Discovered basic device information for <Device model='TS0042' manuf='_TZ3000_5e235jpa' nwk=0x4B04 ieee=e0:79:8d:ff:fe:c9:e5:84 is_initialized=True>
Device is initialized <Device model='TS0042' manuf='_TZ3000_5e235jpa' nwk=0x4B04 ieee=e0:79:8d:ff:fe:c9:e5:84 is_initialized=True>
Checking quirks for _TZ3000_5e235jpa TS0042 (e0:79:8d:ff:fe:c9:e5:84)
Considering <class 'ts0042.TuyaSmartRemote0042TOPlusA'>
Fail because endpoint list mismatch: {1, 2, 3, 4} {1, 2}
Considering <class 'ts0042.TuyaSmartRemote0042TI'>
Fail because input cluster mismatch on at least one endpoint
Considering <class 'zhaquirks.tuya.ts0042.TuyaSmartRemote0042TOPlusA'>
Fail because endpoint list mismatch: {1, 2, 3, 4} {1, 2}
Considering <class 'zhaquirks.tuya.ts0042.TuyaSmartRemote0042TO'>
Found custom device replacement for e0:79:8d:ff:fe:c9:e5:84: <class 'zhaquirks.tuya.ts0042.TuyaSmartRemote0042TO'>
'sensor' component -> 'Battery' using ['power']
'sensor' component -> 'RSSISensor' using ['basic']
'sensor' component -> 'LQISensor' using ['basic']
device - 0x4B04:e0:79:8d:ff:fe:c9:e5:84 entering async_device_initialized - is_new_join: True
device - 0x4B04:e0:79:8d:ff:fe:c9:e5:84 has joined the ZHA zigbee network
[0x4B04](TS0042): started configuration
[0x4B04:ZDO](TS0042): 'async_configure' stage succeeded
[0x4B04:1:0x0000]: Configuring cluster attribute reporting
[0x4B04:1:0x0000]: finished channel configuration
[0x4B04:1:0x0001]: Performing cluster binding
[0x4b04] Extending timeout for 0x5c request
[0x4B04:1:0x0019]: finished channel configuration
Error handling '_save_attribute' event with (e0:79:8d:ff:fe:c9:e5:84, 1, 0, 4, '_TZ3000_5e235jpa') params: FOREIGN KEY constraint failed
Error handling '_save_attribute' event with (e0:79:8d:ff:fe:c9:e5:84, 1, 0, 5, 'TS0042') params: FOREIGN KEY constraint failed
Received a packet: ZigbeePacket(src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x4B04), src_ep=0, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=0, source_route=None, extended_timeout=False, tsn=None, profile_id=0, cluster_id=32801, data=Serialized[b'\\\x00'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=255, rssi=-49)
[0x4B04:1:0x0001]: bound 'power' cluster: Status.SUCCESS
[0x4B04:1:0x0001]: Configuring cluster attribute reporting
[0x4B04:1:0x0001] Sending request header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.GLOBAL_COMMAND: 0>, is_manufacturer_specific=False, direction=<Direction.Server_to_Client: 0>, disable_default_response=0, reserved=0, *is_cluster=False, *is_general=True, *is_reply=False), tsn=94, command_id=<GeneralCommand.Configure_Reporting: 6>, *direction=<Direction.Server_to_Client: 0>, *is_reply=False)
[0x4B04:1:0x0001] Sending request: Configure_Reporting(config_records=[AttributeReportingConfig(direction=0, attrid=0x0020, datatype=32, min_interval=3600, max_interval=10800, reportable_change=1), AttributeReportingConfig(direction=0, attrid=0x0021, datatype=32, min_interval=3600, max_interval=10800, reportable_change=1)])
[0x4b04] Extending timeout for 0x5e request
Received a packet: ZigbeePacket(src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x4B04), src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=1, source_route=None, extended_timeout=False, tsn=None, profile_id=260, cluster_id=1, data=Serialized[b'\x18^\x07\x00'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=255, rssi=-49)
[0x4B04:1:0x0001] Received ZCL frame: b'\x18^\x07\x00'
[0x4B04:1:0x0001] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.GLOBAL_COMMAND: 0>, is_manufacturer_specific=0, direction=<Direction.Client_to_Server: 1>, disable_default_response=1, reserved=0, *is_cluster=False, *is_general=True, *is_reply=True), tsn=94, command_id=7, *direction=<Direction.Client_to_Server: 1>, *is_reply=True)
[0x4B04:1:0x0001] Decoded ZCL frame: PowerConfiguration:Configure_Reporting_rsp(status_records=[ConfigureReportingResponseRecord(status=<Status.SUCCESS: 0>)])
[0x4B04:1:0x0001]: Successfully configured reporting for '{'battery_voltage': (3600, 10800, 1), 'battery_percentage_remaining': (3600, 10800, 1)}' on 'power' cluster: [ConfigureReportingResponseRecord(status=<Status.SUCCESS: 0>)]
[0x4B04:1:0x0001]: finished channel configuration
[0x4B04:1:0x0000]: 'async_configure' stage succeeded
[0x4B04:1:0x0001]: 'async_configure' stage succeeded
[0x4B04:1:0x0019]: 'async_configure' stage succeeded
[0x4B04](TS0042): completed configuration
[0x4B04](TS0042): started initialization
[0x4B04:ZDO](TS0042): 'async_initialize' stage succeeded
Received a packet: ZigbeePacket(src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x4B04), src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=1, source_route=None, extended_timeout=False, tsn=None, profile_id=260, cluster_id=10, data=Serialized[b'\x00\t\x00\x07\x00'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=255, rssi=-49)
[0x4B04:1:0x000a] Received ZCL frame: b'\x00\t\x00\x07\x00'
[0x4B04:1:0x000a] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.GLOBAL_COMMAND: 0>, is_manufacturer_specific=0, direction=<Direction.Server_to_Client: 0>, disable_default_response=0, reserved=0, *is_cluster=False, *is_general=True, *is_reply=False), tsn=9, command_id=0, *direction=<Direction.Server_to_Client: 0>, *is_reply=False)
[0x4B04:1:0x000a] Decoded ZCL frame: Time:Read_Attributes(attribute_ids=[7])
[0x4B04:1:0x000a] Received command 0x00 (TSN 9): Read_Attributes(attribute_ids=[7])
[0x4B04:1:0x0000]: initializing channel: from_cache: False
[0x4B04:1:0x0000]: finished channel initialization
[0x4B04:1:0x0001]: initializing channel: from_cache: False
[0x4B04:1:0x0001]: initializing uncached channel attributes: ['battery_voltage', 'battery_percentage_remaining'] - from cache[False]
[0x4B04:1:0x0001]: Reading attributes in chunks: ['battery_voltage', 'battery_percentage_remaining']
[0x4B04:1:0x0001] Sending request header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.GLOBAL_COMMAND: 0>, is_manufacturer_specific=False, direction=<Direction.Server_to_Client: 0>, disable_default_response=0, reserved=0, *is_cluster=False, *is_general=True, *is_reply=False), tsn=96, command_id=<GeneralCommand.Read_Attributes: 0>, *direction=<Direction.Server_to_Client: 0>, *is_reply=False)
[0x4B04:1:0x0001] Sending request: Read_Attributes(attribute_ids=[32, 33])
[0x4b04] Extending timeout for 0x60 request
[0x4B04:1:0x0019]: initializing channel: from_cache: False
[0x4B04:1:0x0019]: finished channel initialization
[0x4B04:1:0x000a] Sending reply header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.GLOBAL_COMMAND: 0>, is_manufacturer_specific=False, direction=<Direction.Client_to_Server: 1>, disable_default_response=1, reserved=0, *is_cluster=False, *is_general=True, *is_reply=True), tsn=9, command_id=<GeneralCommand.Read_Attributes_rsp: 1>, *direction=<Direction.Client_to_Server: 1>, *is_reply=True)
[0x4B04:1:0x000a] Sending reply: Read_Attributes_rsp(status_records=[ReadAttributeRecord(attrid=0x0007, status=<Status.SUCCESS: 0>, value=TypeValue(type=LocalTime, value=719170705))])
Received a packet: ZigbeePacket(src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x4B04), src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=1, source_route=None, extended_timeout=False, tsn=None, profile_id=260, cluster_id=1, data=Serialized[b'\x18`\x01 \x00\x00 \x1e!\x00\x00 \xc8'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=255, rssi=-49)
[0x4B04:1:0x0001] Received ZCL frame: b'\x18`\x01 \x00\x00 \x1e!\x00\x00 \xc8'
[0x4B04:1:0x0001] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.GLOBAL_COMMAND: 0>, is_manufacturer_specific=0, direction=<Direction.Client_to_Server: 1>, disable_default_response=1, reserved=0, *is_cluster=False, *is_general=True, *is_reply=True), tsn=96, command_id=1, *direction=<Direction.Client_to_Server: 1>, *is_reply=True)
[0x4B04:1:0x0001] Decoded ZCL frame: PowerConfiguration:Read_Attributes_rsp(status_records=[ReadAttributeRecord(attrid=0x0020, status=<Status.SUCCESS: 0>, value=TypeValue(type=uint8_t, value=30)), ReadAttributeRecord(attrid=0x0021, status=<Status.SUCCESS: 0>, value=TypeValue(type=uint8_t, value=200))])
[0x4B04:1:0x0001]: Performing channel specific initialization: ['battery_voltage', 'battery_percentage_remaining']
[0x4B04:1:0x0001]: Reading attributes in chunks: ['battery_size', 'battery_quantity']
[0x4B04:1:0x0001] Sending request header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.GLOBAL_COMMAND: 0>, is_manufacturer_specific=False, direction=<Direction.Server_to_Client: 0>, disable_default_response=0, reserved=0, *is_cluster=False, *is_general=True, *is_reply=False), tsn=99, command_id=<GeneralCommand.Read_Attributes: 0>, *direction=<Direction.Server_to_Client: 0>, *is_reply=False)
[0x4B04:1:0x0001] Sending request: Read_Attributes(attribute_ids=[49, 51])
[0x4b04] Extending timeout for 0x63 request
Received a packet: ZigbeePacket(src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x4B04), src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=1, source_route=None, extended_timeout=False, tsn=None, profile_id=260, cluster_id=1, data=Serialized[b'\x18c\x011\x00\x863\x00\x86'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=255, rssi=-49)
[0x4B04:1:0x0001] Received ZCL frame: b'\x18c\x011\x00\x863\x00\x86'
[0x4B04:1:0x0001] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.GLOBAL_COMMAND: 0>, is_manufacturer_specific=0, direction=<Direction.Client_to_Server: 1>, disable_default_response=1, reserved=0, *is_cluster=False, *is_general=True, *is_reply=True), tsn=99, command_id=1, *direction=<Direction.Client_to_Server: 1>, *is_reply=True)
[0x4B04:1:0x0001] Decoded ZCL frame: PowerConfiguration:Read_Attributes_rsp(status_records=[ReadAttributeRecord(attrid=0x0031, status=<Status.UNSUPPORTED_ATTRIBUTE: 134>), ReadAttributeRecord(attrid=0x0033, status=<Status.UNSUPPORTED_ATTRIBUTE: 134>)])
[0x4B04:1:0x0001]: finished channel initialization
[0x4B04:1:0x0000]: 'async_initialize' stage succeeded
[0x4B04:1:0x0001]: 'async_initialize' stage succeeded
[0x4B04:1:0x0019]: 'async_initialize' stage succeeded
[0x4B04](TS0042): power source: Battery or Unknown
[0x4B04](TS0042): completed initialization
```

</details>

**Additional context**
