### ISSUE TITLE
[Device Support Request] GLEDOPTO GL-S-004Z Dual White and Color

### ISSUE THREAD

**Issue by aquemy** [zigpy/zha-device-handlers#1848]
Hello,

I have two Gledopto GL-S-004Z Dual White and Color (details [here](https://zigbee.blakadder.com/Gledopto_GL-S-004Z.html)).
They are perfectly recognized by ZHA. However, I cannot access the RGB capabilities, only WW. 

**Describe the solution you'd like**

Technically, these bad boys can handle both White and Colors at the same time so the perfect solution would be to have a way to control simultaneously both.    
However, I would already be happy with RGB support and a way to switch between WW and RGB as I have with other GLEDOPTO device (e.g. [GL-MC-001P](https://zigbee.blakadder.com/Gledopto_GL-MC-001P.html) controller).

<details>

<summary>Device signature</summary>

```yaml
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress|RxOnWhenIdle|MainsPowered|FullFunctionDevice: 142>, manufacturer_code=0, maximum_buffer_size=80, maximum_incoming_transfer_size=160, server_mask=0, maximum_outgoing_transfer_size=160, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
  "endpoints": {
    "11": {
      "profile_id": 49246,
      "device_type": "0x0220",
      "in_clusters": [
        "0x0000",
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0006",
        "0x0008",
        "0x0300"
      ],
      "out_clusters": []
    },
    "13": {
      "profile_id": 49246,
      "device_type": "0x0220",
      "in_clusters": [
        "0x1000"
      ],
      "out_clusters": [
        "0x1000"
      ]
    }
  },
  "manufacturer": "GLEDOPTO",
  "model": "GL-S-004Z",
  "class": "zigpy.device.Device"
}
 ```
</details>

<details>

<summary>Diagnostic information</summary>

```yaml
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.10.1",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.5",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Warsaw",
    "os_name": "Linux",
    "os_version": "5.15.61-v8",
    "supervisor": "2022.10.0",
    "host_os": "Home Assistant OS 9.0",
    "docker_version": "20.10.17",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "miio_yeelink": {
      "version": "0.1.12",
      "requirements": [
        "construct==2.10.56",
        "python-miio>=0.5.6"
      ]
    },
    "hacs": {
      "version": "1.27.2",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
    "ble_monitor": {
      "version": "4.6.2",
      "requirements": [
        "pycryptodomex>=3.10.1",
        "janus>=0.6.1",
        "aioblescan>=0.2.8"
      ]
    },
    "localtuya": {
      "version": "4.1.0",
      "requirements": []
    }
  },
  "integration_manifest": {
    "domain": "zha",
    "name": "Zigbee Home Automation",
    "config_flow": true,
    "documentation": "https://www.home-assistant.io/integrations/zha",
    "requirements": [
      "bellows==0.34.1",
      "pyserial==3.5",
      "pyserial-asyncio==0.6",
      "zha-quirks==0.0.82",
      "zigpy-deconz==0.19.0",
      "zigpy==0.51.2",
      "zigpy-xbee==0.16.0",
      "zigpy-zigate==0.10.0",
      "zigpy-znp==0.9.0"
    ],
    "usb": [
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*2652*",
        "known_devices": [
          "slae.sh cc2652rb stick"
        ]
      },
      {
        "vid": "1A86",
        "pid": "55D4",
        "description": "*sonoff*plus*",
        "known_devices": [
          "sonoff zigbee dongle plus v2"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*sonoff*plus*",
        "known_devices": [
          "sonoff zigbee dongle plus"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*zigstar*",
        "known_devices": [
          "ZigStar Coordinators"
        ]
      },
      {
        "vid": "1CF1",
        "pid": "0030",
        "description": "*conbee*",
        "known_devices": [
          "Conbee II"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8A2A",
        "description": "*zigbee*",
        "known_devices": [
          "Nortek HUSBZB-1"
        ]
      },
      {
        "vid": "0403",
        "pid": "6015",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate+"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8B34",
        "description": "*bv 2010/10*",
        "known_devices": [
          "Bitron Video AV2010/10"
        ]
      }
    ],
    "codeowners": [
      "@dmulcahey",
      "@adminiuga",
      "@puddly"
    ],
    "zeroconf": [
      {
        "type": "_esphomelib._tcp.local.",
        "name": "tube*"
      },
      {
        "type": "_zigate-zigbee-gateway._tcp.local.",
        "name": "*zigate*"
      },
      {
        "type": "_zigstar_gw._tcp.local.",
        "name": "*zigstar*"
      }
    ],
    "dependencies": [
      "file_upload"
    ],
    "after_dependencies": [
      "onboarding",
      "usb",
      "zeroconf"
    ],
    "iot_class": "local_polling",
    "loggers": [
      "aiosqlite",
      "bellows",
      "crccheck",
      "pure_pcapy3",
      "zhaquirks",
      "zigpy",
      "zigpy_deconz",
      "zigpy_xbee",
      "zigpy_zigate",
      "zigpy_znp"
    ],
    "is_built_in": true
  },
  "data": {
    "ieee": "**REDACTED**",
    "nwk": 49358,
    "manufacturer": "GLEDOPTO",
    "model": "GL-S-004Z",
    "name": "GLEDOPTO GL-S-004Z",
    "quirk_applied": false,
    "quirk_class": "zigpy.device.Device",
    "manufacturer_code": 0,
    "power_source": "Mains",
    "lqi": null,
    "rssi": null,
    "last_seen": "2022-10-21T01:10:04",
    "available": false,
    "device_type": "Router",
    "signature": {
      "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress|RxOnWhenIdle|MainsPowered|FullFunctionDevice: 142>, manufacturer_code=0, maximum_buffer_size=80, maximum_incoming_transfer_size=160, server_mask=0, maximum_outgoing_transfer_size=160, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
      "endpoints": {
        "11": {
          "profile_id": 49246,
          "device_type": "0x0220",
          "in_clusters": [
            "0x0000",
            "0x0003",
            "0x0004",
            "0x0005",
            "0x0006",
            "0x0008",
            "0x0300"
          ],
          "out_clusters": []
        },
        "13": {
          "profile_id": 49246,
          "device_type": "0x0220",
          "in_clusters": [
            "0x1000"
          ],
          "out_clusters": [
            "0x1000"
          ]
        }
      }
    },
    "active_coordinator": false,
    "entities": [
      {
        "entity_id": "button.kitchen_spot_light_2_identifybutton",
        "name": "GLEDOPTO GL-S-004Z"
      },
      {
        "entity_id": "light.kitchen_spot_light_2_light",
        "name": "GLEDOPTO GL-S-004Z"
      }
    ],
    "neighbors": [],
    "endpoint_names": [
      {
        "name": "COLOR_TEMPERATURE_LIGHT"
      },
      {
        "name": "COLOR_TEMPERATURE_LIGHT"
      }
    ],
    "user_given_name": "Kitchen Spot Light 2",
    "device_reg_id": "047070b84da0af84d74c231f908ad918",
    "area_id": "kitchen",
    "cluster_details": {
      "11": {
        "device_type": {
          "name": "COLOR_TEMPERATURE_LIGHT",
          "id": 544
        },
        "profile_id": 49246,
        "in_clusters": {
          "0x0000": {
            "endpoint_attribute": "basic",
            "attributes": {
              "0x0004": {
                "attribute_name": "manufacturer",
                "value": "GLEDOPTO"
              },
              "0x0005": {
                "attribute_name": "model",
                "value": "GL-S-004Z"
              }
            },
            "unsupported_attributes": {}
          },
          "0x0003": {
            "endpoint_attribute": "identify",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0004": {
            "endpoint_attribute": "groups",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0005": {
            "endpoint_attribute": "scenes",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0006": {
            "endpoint_attribute": "on_off",
            "attributes": {
              "0x0000": {
                "attribute_name": "on_off",
                "value": 1
              }
            },
            "unsupported_attributes": {
              "0x4003": {
                "attribute_name": "start_up_on_off"
              }
            }
          },
          "0x0008": {
            "endpoint_attribute": "level",
            "attributes": {
              "0x0000": {
                "attribute_name": "current_level",
                "value": 254
              }
            },
            "unsupported_attributes": {
              "0x4000": {
                "attribute_name": "start_up_current_level"
              },
              "0x0012": {
                "attribute_name": "on_transition_time"
              },
              "0x0013": {
                "attribute_name": "off_transition_time"
              },
              "0x0011": {
                "attribute_name": "on_level"
              },
              "0x0014": {
                "attribute_name": "default_move_rate"
              },
              "0x0010": {
                "attribute_name": "on_off_transition_time"
              }
            }
          },
          "0x0300": {
            "endpoint_attribute": "light_color",
            "attributes": {
              "0x0000": {
                "attribute_name": "current_hue",
                "value": 0
              },
              "0x0001": {
                "attribute_name": "current_saturation",
                "value": 0
              },
              "0x0003": {
                "attribute_name": "current_x",
                "value": 24939
              },
              "0x0004": {
                "attribute_name": "current_y",
                "value": 24701
              },
              "0x0007": {
                "attribute_name": "color_temperature",
                "value": 438
              },
              "0x0008": {
                "attribute_name": "color_mode",
                "value": 2
              },
              "0x4000": {
                "attribute_name": "enhanced_current_hue",
                "value": 0
              },
              "0x4002": {
                "attribute_name": "color_loop_active",
                "value": 0
              },
              "0x400a": {
                "attribute_name": "color_capabilities",
                "value": 16
              },
              "0x400b": {
                "attribute_name": "color_temp_physical_min",
                "value": 155
              },
              "0x400c": {
                "attribute_name": "color_temp_physical_max",
                "value": 495
              }
            },
            "unsupported_attributes": {}
          }
        },
        "out_clusters": {}
      },
      "13": {
        "device_type": {
          "name": "COLOR_TEMPERATURE_LIGHT",
          "id": 544
        },
        "profile_id": 49246,
        "in_clusters": {
          "0x1000": {
            "endpoint_attribute": "lightlink",
            "attributes": {},
            "unsupported_attributes": {}
          }
        },
        "out_clusters": {
          "0x1000": {
            "endpoint_attribute": "lightlink",
            "attributes": {},
            "unsupported_attributes": {}
          }
        }
      }
    }
  }
}
```

</details>

Happy to help with anything if needed!
