### ISSUE TITLE
[Device Support Request] Add ExternalSwitchType property to tuya.ts130f.TuyaTS130Double_GP (TS130F _TZ3000_j1xl73iw)

### ISSUE THREAD

**Issue by BenPru** [zigpy/zha-device-handlers#1866]
**Is your feature request related to a problem? Please describe.**
I have a TS130F _TZ3000_j1xl73iw Girier Tuya Smart Blind 2 Gang. My problem is that they act as ExternalSwitchType.Momentary / button switch.
I connect it to my existing hardware switches that stays pressed.
Now I press my hardware switch for down, but nothing happens. Only after I push the hardware down switch to neutral position back, the tuya switch acts and shut down the blind. So it act as button switch.
I have to change the default config from ExternalSwitchType.Momentary to ExternalSwitchType.Toggle.
I have create a quirk with TuyaZBExternalSwitchTypeCluster with attribute external_switch_type (id: 0xd030) but it doesn't work.
I have other single blind switches TS130F _TZ3000_e3vhyirx which has no TuyaZBExternalSwitchTypeCluster but works fine with my hardware switches because they act as ExternalSwitchType.Toggle by default.

**Describe the solution you'd like**
Allow TuyaZBExternalSwitchTypeCluster with attribute external_switch_type (id: 0xd030) to change the external switch behavior.

<details>

<summary>Device signature</summary>

```yaml

  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress|RxOnWhenIdle|MainsPowered|FullFunctionDevice: 142>, manufacturer_code=4417, maximum_buffer_size=66, maximum_incoming_transfer_size=66, server_mask=10752, maximum_outgoing_transfer_size=66, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0202",
      "in_clusters": [
        "0x0000",
        "0x0004",
        "0x0005",
        "0x0006",
        "0x0102"
      ],
      "out_clusters": [
        "0x000a",
        "0x0019"
      ]
    },
    "2": {
      "profile_id": 260,
      "device_type": "0x0202",
      "in_clusters": [
        "0x0004",
        "0x0005",
        "0x0006",
        "0x0102"
      ],
      "out_clusters": []
    },
    "242": {
      "profile_id": 41440,
      "device_type": "0x0061",
      "in_clusters": [],
      "out_clusters": [
        "0x0021"
      ]
    }
  },
  "manufacturer": "_TZ3000_j1xl73iw",
  "model": "TS130F",
  "class": "zhaquirks.tuya.ts130f.TuyaTS130Double_GP"
}
```

</details>

<details>

<summary>Diagnostic information</summary>

```yaml
{
  "home_assistant": {
    "installation_type": "Home Assistant Container",
    "version": "2022.10.5",
    "dev": false,
    "hassio": false,
    "virtualenv": false,
    "python_version": "3.10.5",
    "docker": true,
    "arch": "armv7l",
    "timezone": "Europe/Berlin",
    "os_name": "Linux",
    "os_version": "5.15.68-v7l+",
    "run_as_root": true
  },
  "custom_components": {
    "tinkerforge_switch": {
      "version": "2021.03.18",
      "requirements": [
        "tinkerforge>=2.1.26"
      ]
    },
    "fontawesome": {
      "version": "2.1.5",
      "requirements": []
    },
    "hacs": {
      "version": "1.28.3",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
    "multiscrape": {
      "version": "2.2.0",
      "requirements": [
        "lxml",
        "beautifulsoup4==4.9.1"
      ]
    },
    "novus300": {
      "version": "2021.03.17",
      "requirements": [
        "tinkerforge>=2.1.24",
        "pyserial>=3.4",
        "pyserial-asyncio>=0.4"
      ]
    },
    "simpleicons": {
      "version": "v2.2.0",
      "requirements": [
        "simpleicons==7.14.0"
      ]
    },
    "luxtronik_sensor": {
      "version": "2021.11.22",
      "requirements": [
        "luxtronik==0.3.9"
      ]
    },
    "drkblutspende": {
      "version": "0.1.8",
      "requirements": [
        "feedparser>=6.0.8"
      ]
    },
    "favicon": {
      "version": "10.4",
      "requirements": []
    },
    "luxtronik2": {
      "version": "2022.08.01",
      "requirements": [
        "luxtronik>=0.3.14"
      ]
    },
    "novus2": {
      "version": "0.0.1",
      "requirements": [
        "pyserial-asyncio==0.6"
      ]
    },
    "novus300bus": {
      "version": "2021.09.21",
      "requirements": [
        "pyserial>=3.4",
        "pyserial-asyncio>=0.6"
      ]
    },
    "iaquk": {
      "version": "1.6.2",
      "requirements": []
    }
  },
  "integration_manifest": {
    "domain": "zha",
    "name": "Zigbee Home Automation",
    "config_flow": true,
    "documentation": "https://www.home-assistant.io/integrations/zha",
    "requirements": [
      "bellows==0.34.2",
      "pyserial==3.5",
      "pyserial-asyncio==0.6",
      "zha-quirks==0.0.83",
      "zigpy-deconz==0.19.0",
      "zigpy==0.51.3",
      "zigpy-xbee==0.16.2",
      "zigpy-zigate==0.10.2",
      "zigpy-znp==0.9.1"
    ],
    "usb": [
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*2652*",
        "known_devices": [
          "slae.sh cc2652rb stick"
        ]
      },
      {
        "vid": "1A86",
        "pid": "55D4",
        "description": "*sonoff*plus*",
        "known_devices": [
          "sonoff zigbee dongle plus v2"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*sonoff*plus*",
        "known_devices": [
          "sonoff zigbee dongle plus"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*zigstar*",
        "known_devices": [
          "ZigStar Coordinators"
        ]
      },
      {
        "vid": "1CF1",
        "pid": "0030",
        "description": "*conbee*",
        "known_devices": [
          "Conbee II"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8A2A",
        "description": "*zigbee*",
        "known_devices": [
          "Nortek HUSBZB-1"
        ]
      },
      {
        "vid": "0403",
        "pid": "6015",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate+"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8B34",
        "description": "*bv 2010/10*",
        "known_devices": [
          "Bitron Video AV2010/10"
        ]
      }
    ],
    "codeowners": [
      "@dmulcahey",
      "@adminiuga",
      "@puddly"
    ],
    "zeroconf": [
      {
        "type": "_esphomelib._tcp.local.",
        "name": "tube*"
      },
      {
        "type": "_zigate-zigbee-gateway._tcp.local.",
        "name": "*zigate*"
      },
      {
        "type": "_zigstar_gw._tcp.local.",
        "name": "*zigstar*"
      }
    ],
    "dependencies": [
      "file_upload"
    ],
    "after_dependencies": [
      "onboarding",
      "usb",
      "zeroconf"
    ],
    "iot_class": "local_polling",
    "loggers": [
      "aiosqlite",
      "bellows",
      "crccheck",
      "pure_pcapy3",
      "zhaquirks",
      "zigpy",
      "zigpy_deconz",
      "zigpy_xbee",
      "zigpy_zigate",
      "zigpy_znp"
    ],
    "is_built_in": true
  },
  "data": {
    "ieee": "**REDACTED**",
    "nwk": 25211,
    "manufacturer": "_TZ3000_j1xl73iw",
    "model": "TS130F",
    "name": "_TZ3000_j1xl73iw TS130F",
    "quirk_applied": true,
    "quirk_class": "zhaquirks.tuya.ts130f.TuyaTS130Double_GP",
    "manufacturer_code": 4417,
    "power_source": "Mains",
    "lqi": 199,
    "rssi": -69,
    "last_seen": "2022-10-25T22:46:04",
    "available": true,
    "device_type": "Router",
    "signature": {
      "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress|RxOnWhenIdle|MainsPowered|FullFunctionDevice: 142>, manufacturer_code=4417, maximum_buffer_size=66, maximum_incoming_transfer_size=66, server_mask=10752, maximum_outgoing_transfer_size=66, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
      "endpoints": {
        "1": {
          "profile_id": 260,
          "device_type": "0x0202",
          "in_clusters": [
            "0x0000",
            "0x0004",
            "0x0005",
            "0x0006",
            "0x0102"
          ],
          "out_clusters": [
            "0x000a",
            "0x0019"
          ]
        },
        "2": {
          "profile_id": 260,
          "device_type": "0x0202",
          "in_clusters": [
            "0x0004",
            "0x0005",
            "0x0006",
            "0x0102"
          ],
          "out_clusters": []
        },
        "242": {
          "profile_id": 41440,
          "device_type": "0x0061",
          "in_clusters": [],
          "out_clusters": [
            "0x0021"
          ]
        }
      }
    },
    "active_coordinator": false,
    "entities": [
      {
        "entity_id": "cover.kitchen",
        "name": "_TZ3000_j1xl73iw TS130F"
      },
      {
        "entity_id": "cover.kitchen_door",
        "name": "_TZ3000_j1xl73iw TS130F"
      }
    ],
    "neighbors": [
      {
        "device_type": "Coordinator",
        "rx_on_when_idle": "On",
        "relationship": "Parent",
        "extended_pan_id": "**REDACTED**",
        "ieee": "**REDACTED**",
        "nwk": "0x0000",
        "permit_joining": "Unknown",
        "depth": "0",
        "lqi": "78"
      },
      {
        "device_type": "Router",
        "rx_on_when_idle": "On",
        "relationship": "Sibling",
        "extended_pan_id": "**REDACTED**",
        "ieee": "**REDACTED**",
        "nwk": "0x19FF",
        "permit_joining": "Unknown",
        "depth": "2",
        "lqi": "139"
      },
      {
        "device_type": "Router",
        "rx_on_when_idle": "On",
        "relationship": "Sibling",
        "extended_pan_id": "**REDACTED**",
        "ieee": "**REDACTED**",
        "nwk": "0x1D69",
        "permit_joining": "Unknown",
        "depth": "1",
        "lqi": "72"
      },
      {
        "device_type": "Router",
        "rx_on_when_idle": "On",
        "relationship": "Sibling",
        "extended_pan_id": "**REDACTED**",
        "ieee": "**REDACTED**",
        "nwk": "0x82BF",
        "permit_joining": "Unknown",
        "depth": "1",
        "lqi": "75"
      },
      {
        "device_type": "Router",
        "rx_on_when_idle": "On",
        "relationship": "Sibling",
        "extended_pan_id": "**REDACTED**",
        "ieee": "**REDACTED**",
        "nwk": "0x88EC",
        "permit_joining": "Unknown",
        "depth": "1",
        "lqi": "6"
      },
      {
        "device_type": "Router",
        "rx_on_when_idle": "On",
        "relationship": "Sibling",
        "extended_pan_id": "**REDACTED**",
        "ieee": "**REDACTED**",
        "nwk": "0xD670",
        "permit_joining": "Unknown",
        "depth": "2",
        "lqi": "78"
      },
      {
        "device_type": "Router",
        "rx_on_when_idle": "On",
        "relationship": "Sibling",
        "extended_pan_id": "**REDACTED**",
        "ieee": "**REDACTED**",
        "nwk": "0xF9A2",
        "permit_joining": "Unknown",
        "depth": "2",
        "lqi": "12"
      },
      {
        "device_type": "Router",
        "rx_on_when_idle": "On",
        "relationship": "Sibling",
        "extended_pan_id": "**REDACTED**",
        "ieee": "**REDACTED**",
        "nwk": "0x769E",
        "permit_joining": "Unknown",
        "depth": "1",
        "lqi": "18"
      }
    ],
    "endpoint_names": [
      {
        "name": "WINDOW_COVERING_DEVICE"
      },
      {
        "name": "WINDOW_COVERING_DEVICE"
      },
      {
        "name": "unknown 97 device_type of 0xa1e0 profile id"
      }
    ],
    "user_given_name": "Rolladen K\u00fcche",
    "device_reg_id": "1f218007af9e0a6854fc6ad2562bc9c7",
    "area_id": "kuche",
    "cluster_details": {
      "1": {
        "device_type": {
          "name": "WINDOW_COVERING_DEVICE",
          "id": 514
        },
        "profile_id": 260,
        "in_clusters": {
          "0x0000": {
            "endpoint_attribute": "basic",
            "attributes": {
              "0x0001": {
                "attribute_name": "app_version",
                "value": 67
              },
              "0x0004": {
                "attribute_name": "manufacturer",
                "value": "_TZ3000_j1xl73iw"
              },
              "0x0005": {
                "attribute_name": "model",
                "value": "TS130F"
              },
              "0x0006": {
                "attribute_name": "date_code",
                "value": ""
              }
            },
            "unsupported_attributes": {
              "0x000a": {
                "attribute_name": "product_code"
              },
              "0x000b": {
                "attribute_name": "product_url"
              },
              "0x0012": {
                "attribute_name": "device_enabled"
              },
              "0x000d": {
                "attribute_name": "serial_number"
              },
              "0x000e": {
                "attribute_name": "product_label"
              },
              "0x0014": {
                "attribute_name": "disable_local_config"
              },
              "0x0013": {
                "attribute_name": "alarm_mask"
              }
            }
          },
          "0x0004": {
            "endpoint_attribute": "groups",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0005": {
            "endpoint_attribute": "scenes",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0006": {
            "endpoint_attribute": null,
            "attributes": {
              "0x8001": {
                "attribute_name": "backlight_mode",
                "value": 0
              }
            },
            "unsupported_attributes": {}
          },
          "0x0102": {
            "endpoint_attribute": "window_covering",
            "attributes": {
              "0x0008": {
                "attribute_name": "current_position_lift_percentage",
                "value": 0
              },
              "0xf000": {
                "attribute_name": "tuya_moving_state",
                "value": 1
              },
              "0xf001": {
                "attribute_name": "calibration",
                "value": 1
              },
              "0xf002": {
                "attribute_name": "motor_reversal",
                "value": 0
              },
              "0xf003": {
                "attribute_name": "calibration_time",
                "value": 215
              }
            },
            "unsupported_attributes": {
              "0x0000": {
                "attribute_name": "window_covering_type"
              },
              "0x0007": {
                "attribute_name": "config_status"
              },
              "0x0017": {
                "attribute_name": "window_covering_mode"
              },
              "0x0014": {
                "attribute_name": "velocity_lift"
              }
            }
          }
        },
        "out_clusters": {
          "0x000a": {
            "endpoint_attribute": "time",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0019": {
            "endpoint_attribute": "ota",
            "attributes": {},
            "unsupported_attributes": {}
          }
        }
      },
      "2": {
        "device_type": {
          "name": "WINDOW_COVERING_DEVICE",
          "id": 514
        },
        "profile_id": 260,
        "in_clusters": {
          "0x0004": {
            "endpoint_attribute": "groups",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0005": {
            "endpoint_attribute": "scenes",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0006": {
            "endpoint_attribute": null,
            "attributes": {},
            "unsupported_attributes": {
              "0x8001": {
                "attribute_name": "backlight_mode"
              }
            }
          },
          "0x0102": {
            "endpoint_attribute": "window_covering",
            "attributes": {
              "0x0008": {
                "attribute_name": "current_position_lift_percentage",
                "value": 0
              },
              "0xf000": {
                "attribute_name": "tuya_moving_state",
                "value": 1
              },
              "0xf001": {
                "attribute_name": "calibration",
                "value": 1
              },
              "0xf002": {
                "attribute_name": "motor_reversal",
                "value": 0
              },
              "0xf003": {
                "attribute_name": "calibration_time",
                "value": 270
              }
            },
            "unsupported_attributes": {
              "0x0000": {
                "attribute_name": "window_covering_type"
              },
              "0x0017": {
                "attribute_name": "window_covering_mode"
              },
              "0x0010": {
                "attribute_name": "installed_open_limit_lift"
              },
              "0x0014": {
                "attribute_name": "velocity_lift"
              },
              "0x0015": {
                "attribute_name": "acceleration_time_lift"
              }
            }
          }
        },
        "out_clusters": {}
      },
      "242": {
        "device_type": {
          "name": "unknown",
          "id": 97
        },
        "profile_id": 41440,
        "in_clusters": {},
        "out_clusters": {
          "0x0021": {
            "endpoint_attribute": "green_power",
            "attributes": {},
            "unsupported_attributes": {}
          }
        }
      }
    }
  }
}
```

</details>

<details>
<summary>Additional logs</summary>

```
```

</details>

**Additional context**
