### ISSUE TITLE
TS011F by _TZ3000_typdpbpg  smart plug shuts down goes offline

### ISSUE THREAD

**Issue by TommisGR** [zigpy/zha-device-handlers#1868]
**Describe the bug**
I have several TS011F by _TZ3000_typdpbpg  smart plugs that use zhaquirks.tuya.ts011f_plug.Plug
The work oK except from the issue on the title,
At random the go offline and shutdown but work normaly if u turn them on again via button of HA

**To Reproduce**
1. Add to zha
2. Leave it on for some time
3. They  turn off without automation or user access
4. Other times "became unavailable"

**Expected behavior**
When on to remain ON until action is called

**Screenshots**
![image](https://user-images.githubusercontent.com/15345884/198191879-e61ccd69-2340-47bd-a973-879eb532be19.png)

<details>

<summary>Device signature</summary>

```yaml
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress|RxOnWhenIdle|MainsPowered|FullFunctionDevice: 142>, manufacturer_code=4417, maximum_buffer_size=66, maximum_incoming_transfer_size=66, server_mask=10752, maximum_outgoing_transfer_size=66, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x010a",
      "in_clusters": [
        "0x0000",
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0006",
        "0x0702",
        "0x0b04",
        "0xe000",
        "0xe001"
      ],
      "out_clusters": [
        "0x000a",
        "0x0019"
      ]
    }
  },
  "manufacturer": "_TZ3000_typdpbpg",
  "model": "TS011F",
  "class": "zhaquirks.tuya.ts011f_plug.Plug"
}
```

</details>

<details>

<summary>Diagnostic information</summary>

```yaml
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.10.5",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.5",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Athens",
    "os_name": "Linux",
    "os_version": "5.15.61-v8",
    "supervisor": "2022.10.0",
    "host_os": "Home Assistant OS 9.2",
    "docker_version": "20.10.17",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "version": "1.28.3",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
    "watchman": {
      "version": "0.5.1",
      "requirements": [
        "prettytable==3.0.0"
      ]
    },
    "ble_monitor": {
      "version": "10.5.3",
      "requirements": [
        "pycryptodomex>=3.14.1",
        "janus>=1.0.0",
        "aioblescan>=0.2.13",
        "btsocket>=0.2.0",
        "pyric>=0.1.6.3"
      ]
    },
    "mopidy": {
      "version": "1.4.7",
      "requirements": [
        "mopidyapi>=1.0.0"
      ]
    },
    "androidtv_custom": {
      "version": "0.1.1",
      "requirements": [
        "adb-shell[async]==0.4.2",
        "androidtv[async]==0.0.67",
        "pure-python-adb[async]==0.3.0.dev0"
      ]
    },
    "tapo": {
      "version": "1.2.17",
      "requirements": [
        "plugp100==2.1.20"
      ]
    },
    "sonoff": {
      "version": "3.3.1",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    }
  },
  "integration_manifest": {
    "domain": "zha",
    "name": "Zigbee Home Automation",
    "config_flow": true,
    "documentation": "https://www.home-assistant.io/integrations/zha",
    "requirements": [
      "bellows==0.34.2",
      "pyserial==3.5",
      "pyserial-asyncio==0.6",
      "zha-quirks==0.0.83",
      "zigpy-deconz==0.19.0",
      "zigpy==0.51.3",
      "zigpy-xbee==0.16.2",
      "zigpy-zigate==0.10.2",
      "zigpy-znp==0.9.1"
    ],
    "usb": [
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*2652*",
        "known_devices": [
          "slae.sh cc2652rb stick"
        ]
      },
      {
        "vid": "1A86",
        "pid": "55D4",
        "description": "*sonoff*plus*",
        "known_devices": [
          "sonoff zigbee dongle plus v2"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*sonoff*plus*",
        "known_devices": [
          "sonoff zigbee dongle plus"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*zigstar*",
        "known_devices": [
          "ZigStar Coordinators"
        ]
      },
      {
        "vid": "1CF1",
        "pid": "0030",
        "description": "*conbee*",
        "known_devices": [
          "Conbee II"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8A2A",
        "description": "*zigbee*",
        "known_devices": [
          "Nortek HUSBZB-1"
        ]
      },
      {
        "vid": "0403",
        "pid": "6015",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate+"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8B34",
        "description": "*bv 2010/10*",
        "known_devices": [
          "Bitron Video AV2010/10"
        ]
      }
    ],
    "codeowners": [
      "@dmulcahey",
      "@adminiuga",
      "@puddly"
    ],
    "zeroconf": [
      {
        "type": "_esphomelib._tcp.local.",
        "name": "tube*"
      },
      {
        "type": "_zigate-zigbee-gateway._tcp.local.",
        "name": "*zigate*"
      },
      {
        "type": "_zigstar_gw._tcp.local.",
        "name": "*zigstar*"
      }
    ],
    "dependencies": [
      "file_upload"
    ],
    "after_dependencies": [
      "onboarding",
      "usb",
      "zeroconf"
    ],
    "iot_class": "local_polling",
    "loggers": [
      "aiosqlite",
      "bellows",
      "crccheck",
      "pure_pcapy3",
      "zhaquirks",
      "zigpy",
      "zigpy_deconz",
      "zigpy_xbee",
      "zigpy_zigate",
      "zigpy_znp"
    ],
    "is_built_in": true
  },
  "data": {
    "ieee": "**REDACTED**",
    "nwk": 28488,
    "manufacturer": "_TZ3000_typdpbpg",
    "model": "TS011F",
    "name": "_TZ3000_typdpbpg TS011F",
    "quirk_applied": true,
    "quirk_class": "zhaquirks.tuya.ts011f_plug.Plug",
    "manufacturer_code": 4417,
    "power_source": "Mains",
    "lqi": 100,
    "rssi": -75,
    "last_seen": "2022-10-27T07:29:55",
    "available": true,
    "device_type": "Router",
    "signature": {
      "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress|RxOnWhenIdle|MainsPowered|FullFunctionDevice: 142>, manufacturer_code=4417, maximum_buffer_size=66, maximum_incoming_transfer_size=66, server_mask=10752, maximum_outgoing_transfer_size=66, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
      "endpoints": {
        "1": {
          "profile_id": 260,
          "device_type": "0x010a",
          "in_clusters": [
            "0x0000",
            "0x0003",
            "0x0004",
            "0x0005",
            "0x0006",
            "0x0702",
            "0x0b04",
            "0xe000",
            "0xe001"
          ],
          "out_clusters": [
            "0x000a",
            "0x0019"
          ]
        }
      }
    },
    "active_coordinator": false,
    "entities": [
      {
        "entity_id": "button.4b2_50h1_01_saloni_3_identifybutton",
        "name": "_TZ3000_typdpbpg TS011F"
      },
      {
        "entity_id": "sensor.4b2_50h1_01_saloni_3_power",
        "name": "_TZ3000_typdpbpg TS011F"
      },
      {
        "entity_id": "sensor.4b2_50h1_01_saloni_3_current",
        "name": "_TZ3000_typdpbpg TS011F"
      },
      {
        "entity_id": "sensor.4b2_50h1_01_saloni_3_voltage",
        "name": "_TZ3000_typdpbpg TS011F"
      },
      {
        "entity_id": "sensor.4b2_50h1_01_saloni_3_powerfactor",
        "name": "_TZ3000_typdpbpg TS011F"
      },
      {
        "entity_id": "sensor.4b2_50h1_01_saloni_3_rssi",
        "name": "_TZ3000_typdpbpg TS011F"
      },
      {
        "entity_id": "sensor.4b2_50h1_01_saloni_3_lqi",
        "name": "_TZ3000_typdpbpg TS011F"
      },
      {
        "entity_id": "sensor.4b2_50h1_01_saloni_3_sum",
        "name": "_TZ3000_typdpbpg TS011F"
      },
      {
        "entity_id": "switch.4b2_50h1_01_saloni_3_switch",
        "name": "_TZ3000_typdpbpg TS011F"
      }
    ],
    "neighbors": [
      {
        "device_type": "Coordinator",
        "rx_on_when_idle": "On",
        "relationship": "Parent",
        "extended_pan_id": "**REDACTED**",
        "ieee": "**REDACTED**",
        "nwk": "0x0000",
        "permit_joining": "Unknown",
        "depth": "0",
        "lqi": "42"
      },
      {
        "device_type": "Router",
        "rx_on_when_idle": "On",
        "relationship": "Sibling",
        "extended_pan_id": "**REDACTED**",
        "ieee": "**REDACTED**",
        "nwk": "0x2B38",
        "permit_joining": "Unknown",
        "depth": "1",
        "lqi": "66"
      },
      {
        "device_type": "Router",
        "rx_on_when_idle": "On",
        "relationship": "Sibling",
        "extended_pan_id": "**REDACTED**",
        "ieee": "**REDACTED**",
        "nwk": "0x5F3B",
        "permit_joining": "Unknown",
        "depth": "1",
        "lqi": "0"
      },
      {
        "device_type": "Router",
        "rx_on_when_idle": "On",
        "relationship": "Sibling",
        "extended_pan_id": "**REDACTED**",
        "ieee": "**REDACTED**",
        "nwk": "0xA2D6",
        "permit_joining": "Unknown",
        "depth": "1",
        "lqi": "45"
      },
      {
        "device_type": "Router",
        "rx_on_when_idle": "On",
        "relationship": "Sibling",
        "extended_pan_id": "**REDACTED**",
        "ieee": "**REDACTED**",
        "nwk": "0x5CFF",
        "permit_joining": "Unknown",
        "depth": "1",
        "lqi": "0"
      },
      {
        "device_type": "Router",
        "rx_on_when_idle": "On",
        "relationship": "Sibling",
        "extended_pan_id": "**REDACTED**",
        "ieee": "**REDACTED**",
        "nwk": "0xB6E9",
        "permit_joining": "Unknown",
        "depth": "1",
        "lqi": "42"
      },
      {
        "device_type": "Router",
        "rx_on_when_idle": "On",
        "relationship": "Sibling",
        "extended_pan_id": "**REDACTED**",
        "ieee": "**REDACTED**",
        "nwk": "0x377A",
        "permit_joining": "Unknown",
        "depth": "1",
        "lqi": "0"
      },
      {
        "device_type": "Router",
        "rx_on_when_idle": "On",
        "relationship": "Sibling",
        "extended_pan_id": "**REDACTED**",
        "ieee": "**REDACTED**",
        "nwk": "0xAFAD",
        "permit_joining": "Unknown",
        "depth": "1",
        "lqi": "42"
      },
      {
        "device_type": "Router",
        "rx_on_when_idle": "On",
        "relationship": "Sibling",
        "extended_pan_id": "**REDACTED**",
        "ieee": "**REDACTED**",
        "nwk": "0x3E12",
        "permit_joining": "Unknown",
        "depth": "1",
        "lqi": "33"
      },
      {
        "device_type": "Router",
        "rx_on_when_idle": "On",
        "relationship": "Sibling",
        "extended_pan_id": "**REDACTED**",
        "ieee": "**REDACTED**",
        "nwk": "0x47FD",
        "permit_joining": "Unknown",
        "depth": "1",
        "lqi": "39"
      }
    ],
    "endpoint_names": [
      {
        "name": "ON_OFF_PLUG_IN_UNIT"
      }
    ],
    "user_given_name": "4B2-50H1-01 Saloni 3",
    "device_reg_id": "affddf297b4dd67ee573bb05c822df8d",
    "area_id": "living_room",
    "cluster_details": {
      "1": {
        "device_type": {
          "name": "ON_OFF_PLUG_IN_UNIT",
          "id": 266
        },
        "profile_id": 260,
        "in_clusters": {
          "0x0000": {
            "endpoint_attribute": "basic",
            "attributes": {
              "0x0000": {
                "attribute_name": "zcl_version",
                "value": 3
              },
              "0x0001": {
                "attribute_name": "app_version",
                "value": 74
              },
              "0x0004": {
                "attribute_name": "manufacturer",
                "value": "_TZ3000_typdpbpg"
              },
              "0x0005": {
                "attribute_name": "model",
                "value": "TS011F"
              },
              "0x0007": {
                "attribute_name": "power_source",
                "value": 1
              },
              "0xfffe": {
                "attribute_name": "attr_reporting_status",
                "value": 0
              }
            },
            "unsupported_attributes": {}
          },
          "0x0003": {
            "endpoint_attribute": "identify",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0004": {
            "endpoint_attribute": "groups",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0005": {
            "endpoint_attribute": "scenes",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0006": {
            "endpoint_attribute": "on_off",
            "attributes": {
              "0x0000": {
                "attribute_name": "on_off",
                "value": 1
              }
            },
            "unsupported_attributes": {
              "0x4003": {
                "attribute_name": "start_up_on_off"
              }
            }
          },
          "0x0702": {
            "endpoint_attribute": "smartenergy_metering",
            "attributes": {
              "0x0000": {
                "attribute_name": "current_summ_delivered",
                "value": 16
              },
              "0x0200": {
                "attribute_name": "status",
                "value": 0
              },
              "0x0300": {
                "attribute_name": "unit_of_measure",
                "value": 0
              },
              "0x0301": {
                "attribute_name": "multiplier",
                "value": 1
              },
              "0x0302": {
                "attribute_name": "divisor",
                "value": 100
              },
              "0x0303": {
                "attribute_name": "summation_formatting",
                "value": 0
              },
              "0x0306": {
                "attribute_name": "metering_device_type",
                "value": 0
              }
            },
            "unsupported_attributes": {
              "0x0400": {
                "attribute_name": "instantaneous_demand"
              },
              "0x0304": {
                "attribute_name": "demand_formatting"
              }
            }
          },
          "0x0b04": {
            "endpoint_attribute": "electrical_measurement",
            "attributes": {
              "0x0505": {
                "attribute_name": "rms_voltage",
                "value": 229
              },
              "0x0508": {
                "attribute_name": "rms_current",
                "value": 415
              },
              "0x050b": {
                "attribute_name": "active_power",
                "value": 89
              },
              "0x0602": {
                "attribute_name": "ac_current_multiplier",
                "value": 1
              },
              "0x0603": {
                "attribute_name": "ac_current_divisor",
                "value": 1000
              }
            },
            "unsupported_attributes": {
              "0x0300": {
                "attribute_name": "ac_frequency"
              },
              "0x0601": {
                "attribute_name": "ac_voltage_divisor"
              },
              "0x0302": {
                "attribute_name": "ac_frequency_max"
              },
              "0x0604": {
                "attribute_name": "ac_power_multiplier"
              },
              "0x0605": {
                "attribute_name": "ac_power_divisor"
              },
              "0x0600": {
                "attribute_name": "ac_voltage_multiplier"
              },
              "0x0507": {
                "attribute_name": "rms_voltage_max"
              },
              "0x0401": {
                "attribute_name": "ac_frequency_divisor"
              },
              "0x0400": {
                "attribute_name": "ac_frequency_multiplier"
              },
              "0x050a": {
                "attribute_name": "rms_current_max"
              },
              "0x0000": {
                "attribute_name": "measurement_type"
              },
              "0x0403": {
                "attribute_name": "power_divisor"
              },
              "0x050d": {
                "attribute_name": "active_power_max"
              },
              "0x050f": {
                "attribute_name": "apparent_power"
              },
              "0x0402": {
                "attribute_name": "power_multiplier"
              }
            }
          },
          "0xe000": {
            "endpoint_attribute": "tuya_is_pita_0",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0xe001": {
            "endpoint_attribute": "tuya_external_switch_type",
            "attributes": {},
            "unsupported_attributes": {}
          }
        },
        "out_clusters": {
          "0x000a": {
            "endpoint_attribute": "time",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0019": {
            "endpoint_attribute": "ota",
            "attributes": {},
            "unsupported_attributes": {}
          }
        }
      }
    }
  }
}
```

</details>

<details>
<summary>Additional logs</summary>

```
    grep "6f48" home-assistant.log 
2022-10-27 05:47:13.211 DEBUG (MainThread) [zigpy.appdb] [0x6f48:1:0x0000] Attribute id: 4 value: _TZ3000_typdpbpg
2022-10-27 05:47:13.211 DEBUG (MainThread) [zigpy.appdb] [0x6f48:1:0x0000] Attribute id: 5 value: TS011F
2022-10-27 05:47:17.160 DEBUG (MainThread) [zigpy.appdb] [0x6f48:1:0x0000] Attribute id: 4 value: _TZ3000_typdpbpg
2022-10-27 05:47:17.160 DEBUG (MainThread) [zigpy.appdb] [0x6f48:1:0x0000] Attribute id: 5 value: TS011F
2022-10-27 05:47:17.161 DEBUG (MainThread) [zigpy.appdb] [0x6f48:1:0x0000] Attribute id: 0 value: 3
2022-10-27 05:47:17.161 DEBUG (MainThread) [zigpy.appdb] [0x6f48:1:0x0000] Attribute id: 1 value: 74
2022-10-27 05:47:17.161 DEBUG (MainThread) [zigpy.appdb] [0x6f48:1:0x0000] Attribute id: 7 value: 1
2022-10-27 05:47:17.161 DEBUG (MainThread) [zigpy.appdb] [0x6f48:1:0x0000] Attribute id: 65534 value: 0
2022-10-27 05:47:17.162 DEBUG (MainThread) [zigpy.appdb] [0x6f48:1:0x0b04] Attribute id: 1539 value: 1000
2022-10-27 05:47:17.162 DEBUG (MainThread) [zigpy.appdb] [0x6f48:1:0x0b04] Attribute id: 1538 value: 1
2022-10-27 05:47:17.162 DEBUG (MainThread) [zigpy.appdb] [0x6f48:1:0x0702] Attribute id: 770 value: 100
2022-10-27 05:47:17.162 DEBUG (MainThread) [zigpy.appdb] [0x6f48:1:0x0702] Attribute id: 769 value: 1
2022-10-27 05:47:17.163 DEBUG (MainThread) [zigpy.appdb] [0x6f48:1:0x0702] Attribute id: 774 value: 0
2022-10-27 05:47:17.163 DEBUG (MainThread) [zigpy.appdb] [0x6f48:1:0x0702] Attribute id: 771 value: 0
2022-10-27 05:47:17.163 DEBUG (MainThread) [zigpy.appdb] [0x6f48:1:0x0006] Attribute id: 0 value: 0
2022-10-27 05:47:17.164 DEBUG (MainThread) [zigpy.appdb] [0x6f48:1:0x0702] Attribute id: 768 value: 0
2022-10-27 05:47:17.164 DEBUG (MainThread) [zigpy.appdb] [0x6f48:1:0x0702] Attribute id: 0 value: 12
2022-10-27 05:47:17.164 DEBUG (MainThread) [zigpy.appdb] [0x6f48:1:0x0702] Attribute id: 512 value: 0
2022-10-27 05:47:17.165 DEBUG (MainThread) [zigpy.appdb] [0x6f48:1:0x0b04] Attribute id: 1291 value: 0
2022-10-27 05:47:17.165 DEBUG (MainThread) [zigpy.appdb] [0x6f48:1:0x0b04] Attribute id: 1288 value: 0
2022-10-27 05:47:17.165 DEBUG (MainThread) [zigpy.appdb] [0x6f48:1:0x0b04] Attribute id: 1285 value: 233
2022-10-27 05:47:17.165 DEBUG (MainThread) [zigpy.appdb] [0x6f48:1:0x0000] Attribute id: 65506 value: 53
2022-10-27 05:47:17.166 DEBUG (MainThread) [zigpy.appdb] [0x6f48:1:0x0000] Attribute id: 65508 value: 0
2022-10-27 05:47:17.166 DEBUG (MainThread) [zigpy.appdb] [0x6f48:1:0x0000] Attribute id: 65503 value: 	
2022-10-27 05:47:17.166 DEBUG (MainThread) [zigpy.appdb] [0x6f48:1:0xe001] Attribute id: 53249 value: 0
2022-10-27 05:48:06.818 DEBUG (MainThread) [zigpy.device] [0x6f48] Invalid state on future for 0x53 seq -- probably duplicate response
2022-10-27 05:48:07.290 DEBUG (MainThread) [zigpy.device] [0x6f48] Invalid state on future for 0x59 seq -- probably duplicate response
2022-10-27 05:48:07.309 DEBUG (MainThread) [zigpy.device] [0x6f48] Invalid state on future for 0x59 seq -- probably duplicate response
2022-10-27 05:49:03.712 DEBUG (MainThread) [zigpy.device] [0x6f48] Invalid state on future for 0x93 seq -- probably duplicate response
2022-10-27 05:50:32.926 DEBUG (MainThread) [zigpy.device] [0x6f48] Invalid state on future for 0xc4 seq -- probably duplicate response
2022-10-27 05:50:32.952 DEBUG (MainThread) [zigpy.device] [0x6f48] Invalid state on future for 0xc4 seq -- probably duplicate response
2022-10-27 05:51:03.179 DEBUG (MainThread) [zigpy.device] [0x6f48] Invalid state on future for 0xd0 seq -- probably duplicate response
2022-10-27 06:08:33.419 DEBUG (MainThread) [zigpy.device] [0x6f48] Invalid state on future for 0xb8 seq -- probably duplicate response
2022-10-27 06:44:32.949 DEBUG (MainThread) [zigpy.device] [0x6f48] Invalid state on future for 0xa5 seq -- probably duplicate response
2022-10-27 06:51:33.119 DEBUG (MainThread) [zigpy.device] [0x6f48] Invalid state on future for 0x6c seq -- probably duplicate response
2022-10-27 07:12:33.048 DEBUG (MainThread) [zigpy.device] [0x6f48] Invalid state on future for 0xd0 seq -- probably duplicate response
2022-10-27 07:20:33.095 DEBUG (MainThread) [zigpy.device] [0x6f48] Invalid state on future for 0xd9 seq -- probably duplicate response
2022-10-27 07:20:33.251 DEBUG (MainThread) [zigpy.device] [0x6f48] Invalid state on future for 0xd9 seq -- probably duplicate response

```

</details>

**Additional context**
