### ISSUE TITLE
[BUG] Saswell SEA802-Zigbee only showing off button and gets stuck

### ISSUE THREAD

**Issue by jzielke84** [zigpy/zha-device-handlers#1900]
**Describe the bug**
After adding my thermostat the climate card - aside of the temperature control - only shows the `off`-button. When I click on it, the thermostat is turned off and I can't control it anymore from HA. I have to manually set the thermostat to a specific temperature instead to switch the `hvac_mode` to `heat`. I tried overriding this with a customized yaml but then I get the following error while clicking on the `heat` button:

```shell
Nov  6 14:03:46 homeassistant homeassistant[909]: #033[33m2022-11-06 14:03:46.293 WARNING (MainThread) [homeassistant.components.zha.entity] climate.thermostat_thermostat: can't set 'heat' mode. Supported modes are: [<HVACMode.OFF: 'off'>]#033[0m
````

**To Reproduce**
1. Pair thermostat
2. set temperature
3. click`off`-button
4. try to set temperature again. It won't change.

**Expected behavior**
Offer a working `off` and `heat` button.

**Screenshots**
![Bildschirmfoto 2022-11-06 um 14 18 07](https://user-images.githubusercontent.com/13448042/200172951-32d4ff8a-2f27-48fd-812d-70fbb76911e5.png)

<details>

<summary>Device signature</summary>

```yaml
IEEE: 84:ba:20:ff:fe:3c:e6:02
Nwk: 0xc598
Device Type: EndDevice
LQI: Unbekannt
RSSI: Unbekannt
Zuletzt gesehen: 2022-11-06T13:54:12
Energiequelle: Battery or Unknown
Eigenart: zhaquirks.tuya.ts0601_trv_sas.Thermostat_TZE200_c88teujp ``` marks.
```

</details>

<details>

<summary>Diagnostic information</summary>

```yaml
{
  "home_assistant": {
    "installation_type": "Home Assistant Supervised",
    "version": "2022.11.1",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.7",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Berlin",
    "os_name": "Linux",
    "os_version": "5.10.0-19-amd64",
    "supervisor": "2022.11.dev0401",
    "host_os": "Debian GNU/Linux 11 (bullseye)",
    "docker_version": "20.10.21",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "version": "1.28.3",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    }
  },
  "integration_manifest": {
    "domain": "zha",
    "name": "Zigbee Home Automation",
    "config_flow": true,
    "documentation": "https://www.home-assistant.io/integrations/zha",
    "requirements": [
      "bellows==0.34.2",
      "pyserial==3.5",
      "pyserial-asyncio==0.6",
      "zha-quirks==0.0.84",
      "zigpy-deconz==0.19.0",
      "zigpy==0.51.5",
      "zigpy-xbee==0.16.2",
      "zigpy-zigate==0.10.3",
      "zigpy-znp==0.9.1"
    ],
    "usb": [
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*2652*",
        "known_devices": [
          "slae.sh cc2652rb stick"
        ]
      },
      {
        "vid": "1A86",
        "pid": "55D4",
        "description": "*sonoff*plus*",
        "known_devices": [
          "sonoff zigbee dongle plus v2"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*sonoff*plus*",
        "known_devices": [
          "sonoff zigbee dongle plus"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*zigstar*",
        "known_devices": [
          "ZigStar Coordinators"
        ]
      },
      {
        "vid": "1CF1",
        "pid": "0030",
        "description": "*conbee*",
        "known_devices": [
          "Conbee II"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8A2A",
        "description": "*zigbee*",
        "known_devices": [
          "Nortek HUSBZB-1"
        ]
      },
      {
        "vid": "0403",
        "pid": "6015",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate+"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8B34",
        "description": "*bv 2010/10*",
        "known_devices": [
          "Bitron Video AV2010/10"
        ]
      }
    ],
    "codeowners": [
      "@dmulcahey",
      "@adminiuga",
      "@puddly"
    ],
    "zeroconf": [
      {
        "type": "_esphomelib._tcp.local.",
        "name": "tube*"
      },
      {
        "type": "_zigate-zigbee-gateway._tcp.local.",
        "name": "*zigate*"
      },
      {
        "type": "_zigstar_gw._tcp.local.",
        "name": "*zigstar*"
      }
    ],
    "dependencies": [
      "file_upload"
    ],
    "after_dependencies": [
      "onboarding",
      "usb",
      "zeroconf"
    ],
    "iot_class": "local_polling",
    "loggers": [
      "aiosqlite",
      "bellows",
      "crccheck",
      "pure_pcapy3",
      "zhaquirks",
      "zigpy",
      "zigpy_deconz",
      "zigpy_xbee",
      "zigpy_zigate",
      "zigpy_znp"
    ],
    "is_built_in": true
  },
  "data": {
    "ieee": "**REDACTED**",
    "nwk": 50584,
    "manufacturer": "_TZE200_yw7cahqs",
    "model": "TS0601",
    "name": "_TZE200_yw7cahqs TS0601",
    "quirk_applied": true,
    "quirk_class": "zhaquirks.tuya.ts0601_trv_sas.Thermostat_TZE200_c88teujp",
    "manufacturer_code": 4098,
    "power_source": "Battery or Unknown",
    "lqi": null,
    "rssi": null,
    "last_seen": "2022-11-06T13:54:12",
    "available": true,
    "device_type": "EndDevice",
    "signature": {
      "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4098, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
      "endpoints": {
        "1": {
          "profile_id": 260,
          "device_type": "0x0301",
          "in_clusters": [
            "0x0000",
            "0x0001",
            "0x0004",
            "0x0005",
            "0x0201",
            "0xef00"
          ],
          "out_clusters": [
            "0x0001",
            "0x000a",
            "0x0019",
            "0x0201"
          ]
        }
      }
    },
    "active_coordinator": false,
    "entities": [
      {
        "entity_id": "sensor.thermostat_battery",
        "name": "_TZE200_yw7cahqs TS0601"
      },
      {
        "entity_id": "sensor.thermostat_hvac_action",
        "name": "_TZE200_yw7cahqs TS0601"
      },
      {
        "entity_id": "climate.thermostat_thermostat",
        "name": "_TZE200_yw7cahqs TS0601"
      }
    ],
    "neighbors": [],
    "endpoint_names": [
      {
        "name": "THERMOSTAT"
      }
    ],
    "user_given_name": "Heizung Arbeitszimmer",
    "device_reg_id": "35ffd04914ede394cd7822dc087fa932",
    "area_id": "arbeitszimmer",
    "cluster_details": {
      "1": {
        "device_type": {
          "name": "THERMOSTAT",
          "id": 769
        },
        "profile_id": 260,
        "in_clusters": {
          "0x0000": {
            "endpoint_attribute": "basic",
            "attributes": {
              "0x0004": {
                "attribute_name": "manufacturer",
                "value": "_TZE200_yw7cahqs"
              },
              "0x0005": {
                "attribute_name": "model",
                "value": "TS0601"
              }
            },
            "unsupported_attributes": {}
          },
          "0x0004": {
            "endpoint_attribute": "groups",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0005": {
            "endpoint_attribute": "scenes",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0xef00": {
            "endpoint_attribute": "tuya_manufacturer",
            "attributes": {
              "0x0165": {
                "attribute_name": "system_mode",
                "value": 0
              },
              "0x0267": {
                "attribute_name": "occupied_heating_setpoint",
                "value": 90
              },
              "0x0266": {
                "attribute_name": "local_temperature",
                "value": 234
              },
              "0x0569": {
                "attribute_name": "battery_state",
                "value": 0
              }
            },
            "unsupported_attributes": {}
          },
          "0x0001": {
            "endpoint_attribute": "power",
            "attributes": {
              "0x0021": {
                "attribute_name": "battery_percentage_remaining",
                "value": 200
              }
            },
            "unsupported_attributes": {}
          },
          "0x0201": {
            "endpoint_attribute": "thermostat",
            "attributes": {
              "0x0000": {
                "attribute_name": "local_temperature",
                "value": 2340
              },
              "0x0012": {
                "attribute_name": "occupied_heating_setpoint",
                "value": 900
              },
              "0x001c": {
                "attribute_name": "system_mode",
                "value": 0
              },
              "0x001e": {
                "attribute_name": "running_mode",
                "value": 0
              }
            },
            "unsupported_attributes": {}
          }
        },
        "out_clusters": {
          "0x000a": {
            "endpoint_attribute": "time",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0019": {
            "endpoint_attribute": "ota",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0001": {
            "endpoint_attribute": "power",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0201": {
            "endpoint_attribute": "thermostat",
            "attributes": {},
            "unsupported_attributes": {}
          }
        }
      }
    }
  }
}``` marks.
```

</details>

<details>
<summary>Additional logs</summary>

```
Paste any additional debug logs here.


Don't remove the extra line breaks outside the ``` marks.
```

</details>

**Additional context**
[MQTT Information](https://www.zigbee2mqtt.io/devices/SEA801-Zigbee_SEA802-Zigbee.html)
