### ISSUE TITLE
Support for Back Light on/off and Child Lock on/off for BlitzWolf-SHP15

### ISSUE THREAD

**Issue by zleba** [zigpy/zha-device-handlers#1963]
These parameters are available in cluster 6 as attributes 32769 (Back Light) and 32768 (Child Lock).
Always 0 means off, 1 means on.

<details>

```yaml
   "nwk": 43382,
    "manufacturer": "_TZ3000_u5u4cakc",
    "model": "TS011F",
    "name": "_TZ3000_u5u4cakc TS011F",
    "quirk_applied": true,
    "quirk_class": "device_plug.Plug",
    "manufacturer_code": 4098,
    "power_source": "Mains",
```

</details>
