### ISSUE TITLE
[Device Support Request] TS011F _TZ3000_rdfh8cfs 

### ISSUE THREAD

**Issue by ChristophCaina** [zigpy/zha-device-handlers#1992]
**Is your feature request related to a problem? Please describe.**
After setting up a fresh Zigbee network I've seen the following warnings in the Logs of my HomeAssistant installation:

```
Logger: zigpy.zcl
Source: runner.py:119
First occurred: 00:51:30 (20 occurrences)
Last logged: 00:51:48

[0xA5B5:1:0xe001] Unknown cluster command 225 b'\x02\xef\x91"+9\x00\x00\x00\x07\x00\x00\x00\x00'
[0xE3C2:1:0xe001] Unknown cluster command 225 b'\x02\xed\x91"+\x15\x00\x00\x00\x00\x00\x00\x00\x00'
```

The devices are TS011F PPower Plugs
![grafik](https://user-images.githubusercontent.com/26391061/206242226-daa47d4e-7019-4be7-9019-6bff080a98bf.png)

**Describe the solution you'd like**

<details>

<summary>Device signature</summary>

```yaml
"data": {
    "ieee": "**REDACTED**",
    "nwk": 58306,
    "manufacturer": "_TZ3000_rdfh8cfs",
    "model": "TS011F",
    "name": "_TZ3000_rdfh8cfs TS011F",
    "quirk_applied": true,
    "quirk_class": "zhaquirks.tuya.ts011f_plug.Plug",
    "manufacturer_code": 4417,
    "power_source": "Mains",
    "lqi": 48,
    "rssi": null,
    "last_seen": "2022-12-07T18:02:45",
    "available": true,
    "device_type": "Router",
    "signature": {
      "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress|RxOnWhenIdle|MainsPowered|FullFunctionDevice: 142>, manufacturer_code=4417, maximum_buffer_size=66, maximum_incoming_transfer_size=66, server_mask=10752, maximum_outgoing_transfer_size=66, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
      "endpoints": {
        "1": {
          "profile_id": 260,
          "device_type": "0x010a",
          "in_clusters": [
            "0x0000",
            "0x0003",
            "0x0004",
            "0x0005",
            "0x0006",
            "0x0702",
            "0x0b04",
            "0xe000",
            "0xe001"
          ],
          "out_clusters": [
            "0x000a",
            "0x0019"
          ]
        }
      }
    },
```

</details>

<details>

<summary>Diagnostic information</summary>

```yaml
Paste the diagnostic information here.
Don't remove the extra line breaks outside the ``` marks.
```

</details>

<details>
<summary>Additional logs</summary>

```
Paste any additional debug logs here.
Don't remove the extra line breaks outside the ``` marks.
```

</details>

**Additional context**
