### ISSUE TITLE
Tuya Multi-Sensor 4 In 1 (PIR and mmWave presence radars) - TS0601 _TZE200_auin8mzr

### ISSUE THREAD

**Issue by mbrton** [zigpy/zha-device-handlers#1993]
Sensor is not working properly.

<details>
<summary>Device signature</summary>

```yaml
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress|RxOnWhenIdle|MainsPowered|FullFunctionDevice: 142>, manufacturer_code=4098, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0107",
      "in_clusters": [
        "0x0000",
        "0x0004",
        "0x0005",
        "0x000c",
        "0x000d",
        "0x0400",
        "0x0406",
        "0xef00"
      ],
      "out_clusters": [
        "0x000a",
        "0x0019"
      ]
    },
    "2": {
      "profile_id": 260,
      "device_type": "0x0007",
      "in_clusters": [
        "0x000d"
      ],
      "out_clusters": []
    },
    "3": {
      "profile_id": 260,
      "device_type": "0x0007",
      "in_clusters": [
        "0x000d"
      ],
      "out_clusters": []
    },
    "4": {
      "profile_id": 260,
      "device_type": "0x0007",
      "in_clusters": [
        "0x000d"
      ],
      "out_clusters": []
    },
    "5": {
      "profile_id": 260,
      "device_type": "0x0007",
      "in_clusters": [
        "0x000d"
      ],
      "out_clusters": []
    }
  },
  "manufacturer": "_TZE200_auin8mzr",
  "model": "TS0601",
  "class": "TS0601_TZE200_ikvncluo.TuyaMmwRadarOccupancy"
}
```

</details>

<details>

<summary>Diagnostic information</summary>

```yaml
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.11.5",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.7",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Prague",
    "os_name": "Linux",
    "os_version": "5.15.61-v8",
    "supervisor": "2022.11.2",
    "host_os": "Home Assistant OS 9.3",
    "docker_version": "20.10.18",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "sonoff": {
      "version": "3.3.1",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    },
    "fullykiosk": {
      "version": "1.1.0",
      "requirements": [
        "python-fullykiosk==0.0.11"
      ]
    },
    "hikconnect": {
      "version": "1.3.0",
      "requirements": [
        "hikconnect==1.0.0"
      ]
    },
    "hacs": {
      "version": "1.28.4",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
    "sonos_cloud": {
      "version": "0.3.3",
      "requirements": []
    },
    "shelly": {
      "version": "1.0.2",
      "requirements": [
        "pyShelly==1.0.2",
        "paho-mqtt==1.6.1",
        "websocket-client"
      ]
    },
    "xiaomi_cloud_map_extractor": {
      "version": "v2.2.0",
      "requirements": [
        "pillow",
        "pybase64",
        "python-miio",
        "requests",
        "pycryptodome"
      ]
    },
    "salusfy": {
      "version": "0.0.1",
      "requirements": []
    },
    "mikrotik_router": {
      "version": "0.0.0",
      "requirements": [
        "librouteros>=3.2.0",
        "mac-vendor-lookup>=0.1.12"
      ]
    },
    "xiaomi_miot": {
      "version": "0.7.2",
      "requirements": [
        "construct==2.10.56",
        "python-miio>=0.5.6",
        "micloud>=0.3"
      ]
    }
  },
  "integration_manifest": {
    "domain": "zha",
    "name": "Zigbee Home Automation",
    "config_flow": true,
    "documentation": "https://www.home-assistant.io/integrations/zha",
    "requirements": [
      "bellows==0.34.4",
      "pyserial==3.5",
      "pyserial-asyncio==0.6",
      "zha-quirks==0.0.87",
      "zigpy-deconz==0.19.1",
      "zigpy==0.51.6",
      "zigpy-xbee==0.16.2",
      "zigpy-zigate==0.10.3",
      "zigpy-znp==0.9.1"
    ],
    "usb": [
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*2652*",
        "known_devices": [
          "slae.sh cc2652rb stick"
        ]
      },
      {
        "vid": "1A86",
        "pid": "55D4",
        "description": "*sonoff*plus*",
        "known_devices": [
          "sonoff zigbee dongle plus v2"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*sonoff*plus*",
        "known_devices": [
          "sonoff zigbee dongle plus"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*zigstar*",
        "known_devices": [
          "ZigStar Coordinators"
        ]
      },
      {
        "vid": "1CF1",
        "pid": "0030",
        "description": "*conbee*",
        "known_devices": [
          "Conbee II"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8A2A",
        "description": "*zigbee*",
        "known_devices": [
          "Nortek HUSBZB-1"
        ]
      },
      {
        "vid": "0403",
        "pid": "6015",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate+"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8B34",
        "description": "*bv 2010/10*",
        "known_devices": [
          "Bitron Video AV2010/10"
        ]
      }
    ],
    "codeowners": [
      "@dmulcahey",
      "@adminiuga",
      "@puddly"
    ],
    "zeroconf": [
      {
        "type": "_esphomelib._tcp.local.",
        "name": "tube*"
      },
      {
        "type": "_zigate-zigbee-gateway._tcp.local.",
        "name": "*zigate*"
      },
      {
        "type": "_zigstar_gw._tcp.local.",
        "name": "*zigstar*"
      }
    ],
    "dependencies": [
      "file_upload"
    ],
    "after_dependencies": [
      "onboarding",
      "usb",
      "zeroconf"
    ],
    "iot_class": "local_polling",
    "loggers": [
      "aiosqlite",
      "bellows",
      "crccheck",
      "pure_pcapy3",
      "zhaquirks",
      "zigpy",
      "zigpy_deconz",
      "zigpy_xbee",
      "zigpy_zigate",
      "zigpy_znp"
    ],
    "is_built_in": true
  },
  "data": {
    "ieee": "**REDACTED**",
    "nwk": 49770,
    "manufacturer": "_TZE200_auin8mzr",
    "model": "TS0601",
    "name": "_TZE200_auin8mzr TS0601",
    "quirk_applied": true,
    "quirk_class": "TS0601_TZE200_ikvncluo.TuyaMmwRadarOccupancy",
    "manufacturer_code": 4098,
    "power_source": "Mains",
    "lqi": 208,
    "rssi": -48,
    "last_seen": "2022-12-07T20:21:26",
    "available": true,
    "device_type": "Router",
    "signature": {
      "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress|RxOnWhenIdle|MainsPowered|FullFunctionDevice: 142>, manufacturer_code=4098, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
      "endpoints": {
        "1": {
          "profile_id": 260,
          "device_type": "0x0107",
          "in_clusters": [
            "0x0000",
            "0x0004",
            "0x0005",
            "0x000c",
            "0x000d",
            "0x0400",
            "0x0406",
            "0xef00"
          ],
          "out_clusters": [
            "0x000a",
            "0x0019"
          ]
        },
        "2": {
          "profile_id": 260,
          "device_type": "0x0007",
          "in_clusters": [
            "0x000d"
          ],
          "out_clusters": []
        },
        "3": {
          "profile_id": 260,
          "device_type": "0x0007",
          "in_clusters": [
            "0x000d"
          ],
          "out_clusters": []
        },
        "4": {
          "profile_id": 260,
          "device_type": "0x0007",
          "in_clusters": [
            "0x000d"
          ],
          "out_clusters": []
        },
        "5": {
          "profile_id": 260,
          "device_type": "0x0007",
          "in_clusters": [
            "0x000d"
          ],
          "out_clusters": []
        }
      }
    },
    "active_coordinator": false,
    "entities": [
      {
        "entity_id": "number.pszb03_number_detection_delay",
        "name": "_TZE200_auin8mzr TS0601"
      },
      {
        "entity_id": "number.pszb03_number_fading_time",
        "name": "_TZE200_auin8mzr TS0601"
      },
      {
        "entity_id": "number.pszb03_number_max_range_cm",
        "name": "_TZE200_auin8mzr TS0601"
      },
      {
        "entity_id": "number.pszb03_number_min_range_cm",
        "name": "_TZE200_auin8mzr TS0601"
      },
      {
        "entity_id": "number.pszb03_number_sensitivity",
        "name": "_TZE200_auin8mzr TS0601"
      },
      {
        "entity_id": "binary_sensor.pszb03_occupancy",
        "name": "_TZE200_auin8mzr TS0601"
      }
    ],
    "neighbors": [],
    "endpoint_names": [
      {
        "name": "OCCUPANCY_SENSOR"
      },
      {
        "name": "COMBINED_INTERFACE"
      },
      {
        "name": "COMBINED_INTERFACE"
      },
      {
        "name": "COMBINED_INTERFACE"
      },
      {
        "name": "COMBINED_INTERFACE"
      }
    ],
    "user_given_name": "PSZB03",
    "device_reg_id": "420570a78f4974d6ebc5260f16cd070e",
    "area_id": "chodba",
    "cluster_details": {
      "1": {
        "device_type": {
          "name": "OCCUPANCY_SENSOR",
          "id": 263
        },
        "profile_id": 260,
        "in_clusters": {
          "0x0000": {
            "endpoint_attribute": "basic",
            "attributes": {
              "0x0001": {
                "attribute_name": "app_version",
                "value": 70
              },
              "0x0003": {
                "attribute_name": "hw_version",
                "value": 1
              }
            },
            "unsupported_attributes": {}
          },
          "0x0004": {
            "endpoint_attribute": "groups",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0005": {
            "endpoint_attribute": "scenes",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0xef00": {
            "endpoint_attribute": "tuya_manufacturer",
            "attributes": {
              "0xef00": {
                "attribute_name": "mcu_version",
                "value": "1.0.9"
              },
              "0xef67": {
                "attribute_name": "cli",
                "value": 10
              }
            },
            "unsupported_attributes": {}
          },
          "0x0400": {
            "endpoint_attribute": "illuminance",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0406": {
            "endpoint_attribute": "occupancy",
            "attributes": {
              "0x0000": {
                "attribute_name": "occupancy",
                "value": 0
              }
            },
            "unsupported_attributes": {}
          },
          "0x000c": {
            "endpoint_attribute": "analog_input",
            "attributes": {
              "0x001c": {
                "attribute_name": "description",
                "value": "Target distance"
              },
              "0x0075": {
                "attribute_name": "engineering_units",
                "value": 31
              }
            },
            "unsupported_attributes": {}
          },
          "0x000d": {
            "endpoint_attribute": "analog_output",
            "attributes": {
              "0x001c": {
                "attribute_name": "description",
                "value": "Sensitivity"
              },
              "0x0041": {
                "attribute_name": "max_present_value",
                "value": 9
              },
              "0x0045": {
                "attribute_name": "min_present_value",
                "value": 1
              },
              "0x006a": {
                "attribute_name": "resolution",
                "value": 1
              }
            },
            "unsupported_attributes": {}
          }
        },
        "out_clusters": {
          "0x000a": {
            "endpoint_attribute": "time",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0019": {
            "endpoint_attribute": "ota",
            "attributes": {},
            "unsupported_attributes": {}
          }
        }
      },
      "2": {
        "device_type": {
          "name": "COMBINED_INTERFACE",
          "id": 7
        },
        "profile_id": 260,
        "in_clusters": {
          "0x000d": {
            "endpoint_attribute": "analog_output",
            "attributes": {
              "0x001c": {
                "attribute_name": "description",
                "value": "Min range (cm)"
              },
              "0x0041": {
                "attribute_name": "max_present_value",
                "value": 950
              },
              "0x0045": {
                "attribute_name": "min_present_value",
                "value": 0
              },
              "0x006a": {
                "attribute_name": "resolution",
                "value": 10
              },
              "0x0075": {
                "attribute_name": "engineering_units",
                "value": 118
              }
            },
            "unsupported_attributes": {}
          }
        },
        "out_clusters": {}
      },
      "3": {
        "device_type": {
          "name": "COMBINED_INTERFACE",
          "id": 7
        },
        "profile_id": 260,
        "in_clusters": {
          "0x000d": {
            "endpoint_attribute": "analog_output",
            "attributes": {
              "0x001c": {
                "attribute_name": "description",
                "value": "Max range (cm)"
              },
              "0x0041": {
                "attribute_name": "max_present_value",
                "value": 950
              },
              "0x0045": {
                "attribute_name": "min_present_value",
                "value": 0
              },
              "0x006a": {
                "attribute_name": "resolution",
                "value": 10
              },
              "0x0075": {
                "attribute_name": "engineering_units",
                "value": 18
              }
            },
            "unsupported_attributes": {}
          }
        },
        "out_clusters": {}
      },
      "4": {
        "device_type": {
          "name": "COMBINED_INTERFACE",
          "id": 7
        },
        "profile_id": 260,
        "in_clusters": {
          "0x000d": {
            "endpoint_attribute": "analog_output",
            "attributes": {
              "0x001c": {
                "attribute_name": "description",
                "value": "Detection delay"
              },
              "0x0041": {
                "attribute_name": "max_present_value",
                "value": 30
              },
              "0x0045": {
                "attribute_name": "min_present_value",
                "value": 0.1
              },
              "0x0055": {
                "attribute_name": "present_value",
                "value": 0.1
              },
              "0x006a": {
                "attribute_name": "resolution",
                "value": 0.1
              },
              "0x0075": {
                "attribute_name": "engineering_units",
                "value": 73
              }
            },
            "unsupported_attributes": {}
          }
        },
        "out_clusters": {}
      },
      "5": {
        "device_type": {
          "name": "COMBINED_INTERFACE",
          "id": 7
        },
        "profile_id": 260,
        "in_clusters": {
          "0x000d": {
            "endpoint_attribute": "analog_output",
            "attributes": {
              "0x001c": {
                "attribute_name": "description",
                "value": "Fading time"
              },
              "0x0041": {
                "attribute_name": "max_present_value",
                "value": 30
              },
              "0x0045": {
                "attribute_name": "min_present_value",
                "value": 0.1
              },
              "0x0055": {
                "attribute_name": "present_value",
                "value": 0.0
              },
              "0x006a": {
                "attribute_name": "resolution",
                "value": 0.1
              },
              "0x0075": {
                "attribute_name": "engineering_units",
                "value": 73
              }
            },
            "unsupported_attributes": {}
          }
        },
        "out_clusters": {}
      }
    }
  }

```

</details>

<details>
<summary>Additional logs</summary>

```
Paste any additional debug logs here.
Don't remove the extra line breaks outside the ``` marks.
```

</details>

I found only this link about this sensor
https://community.hubitat.com/t/release-tuya-zigbee-multi-sensor-4-in-1-pir-motion-sensors-and-mmwave-presence-radars/92441

Home assistant Zigbee devices info:
![image](https://user-images.githubusercontent.com/5383660/206277072-1dc5ddf4-1049-4c3c-9e38-d6945cb4d89f.png)
