### ISSUE TITLE
TRADFRI on/off switch not firing DIM_DOWN events

### ISSUE THREAD

**Issue by xcyb0rg** [zigpy/zha-device-handlers#2024]
Hi,

I have a TRADFRI on/off switch which works mostly fine, except that it mistakenly fires DIM_DOWN events as DIM_UP. I looked over the zhaquirks.ikea.twobtnremote.IkeaTradfriRemote2Btn file, but nothing jumps at me as being incorrect. I tried tweaking commands and events, things do change, but I cannot make DIM_DOWN work.

The Logbook correctly lists the events when I keep the "Up" button pressed (first the long press and then the release):

> Ikea_Switch Move With On Off event was fired with parameters: {'move_mode': <**MoveMode.Up**: 0>, 'rate': 83}
> Ikea_Switch Remote Button Long Release - **Dim Up** event was fired

But when I keep the "Down" button pressed, even though the Move is clearly shown as "Down", the release event is fired as "Dim Up" !?

> Ikea_Switch Move event was fired with parameters: {'move_mode': <**MoveMode.Down**: 1>, 'rate': 83, 'options_mask': <bitmap8.0: 0>, 'options_override': <bitmap8.0: 0>}
> Ikea_Switch Remote Button Long Release - **Dim Up** event was fired

I'm using Home Assistant 2022.12.7.

Where is the problem?

Thank you,
Mihai

**Comment by MattWestb** [comment]
The device is not firing one real down is sending one stop command after move.
We have not implanting the logic to "remember" if it was up or down from the proviso command fired so we dont knowing the direction.

If you like implanting it is PR more then welcome and you can looking on the IKEA open close remote it have it implanted.

**Comment by TheJulianJES** [comment]
Indeed, the device sends a ``stop_with_on_off`` command after being released from a long-press.
We're currently parsing this as a release from a DIM_UP here:
https://github.com/zigpy/zha-device-handlers/blob/7788036230986cebe8e65281d7f58c7566172c8a/zhaquirks/ikea/twobtnremote.py#L121-L125

When does the dimmer send a simple ``stop`` event instead of a ``stop_with_on_off`` event though?
Asking because of this:
https://github.com/zigpy/zha-device-handlers/blob/7788036230986cebe8e65281d7f58c7566172c8a/zhaquirks/ikea/twobtnremote.py#L133-L137

**Comment by MattWestb** [comment]
I think the stop after MoveMode.Down was working in one earlier firmware version (= i dont knowing).
The Open/Close is storing the last move command and its using it for "tagging" the stop with up or down.

**Comment by elvismercado** [comment]
I also have this problem.

**Comment by JR-Y** [comment]
Same issue, in homeassistant looks like this:

DOWN long press
![image](https://user-images.githubusercontent.com/24767278/229309050-a362027d-7fd6-4211-be4a-b476dec29bc4.png)

UP long press
![image](https://user-images.githubusercontent.com/24767278/229309097-cb5abb99-a04a-47b4-ad35-3d42a7d92aac.png)

**Comment by MattWestb** [comment]
With latest firmware 24.4.5
Long press up:
```
  endpoint_id: 1
  cluster_id: 8
  command: move_with_on_off
  args:
    - 0
    - 83
  params:
    move_mode: 0
    rate: 83
```
Long press down:
```
  endpoint_id: 1
  cluster_id: 8
  command: move
  args:
    - 1
    - 83
    - 0
    - 0
  params:
    move_mode: 1
    rate: 83
    options_mask: 0
    options_override: 0
 ```
Both is sending the same stop command:
```
  endpoint_id: 1
  cluster_id: 8
  command: stop_with_on_off
  args: []
  params: {}

  endpoint_id: 1
  cluster_id: 8
  command: stop_with_on_off
  args: []
  params: {}
```
And all is OK in the DA:
https://github.com/zigpy/zha-device-handlers/blob/be0fc65d9b074406bb16e43e5b0decc3665ed84f/zhaquirks/ikea/twobtnremote.py#L113-L138

**Comment by lxs687** [comment]
I also have this problem with IKEA switch not firing DIM_DOWN events ! I'm running latest firmware and core version but looks like the triggers type: remote_button_long_press ; subtype: dim_down is definitively not working !

I do understand that for a Dim Down (long press on 0) the event are "RODRET Dimmer Remote Button Long Release - Dim Up event was fired" and "RODRET Dimmer Move event was fired with parameters: {'move_mode': <MoveMode.Down: 1>, 'rate': 83, 'options_mask': <OptionsMask: 0>, 'options_override': <Options: 0>}"

But now how do you implement that in the automation as following code is never executed : 

- id: '1748331844557
  alias: Button xxx Dim Down
  description: ''
  triggers:
  - device_id: 3dbdcdf4594908df4643dc3808077f62
    domain: zha
    type: remote_button_long_press
    subtype: dim_down
    trigger: device
  conditions: []
  actions:
  - action: light.turn_on
    metadata: {}
    data:
      brightness_step_pct: -10
    target:
      device_id: ff65832f1059e1c371c2f408ad4c82c0
  mode: single

**Comment by MattWestb** [comment]
Your automation looks OK if you have using the right device.

I was testing one of my On/Off switches.
Device:
TRADFRI on/off switch
by IKEA of Sweden

Firmware: 0x24040006

Automation (made from device card):
```
alias: OnOff Dimm Dow
description: ""
triggers:
  - device_id: bb1ac5ecf8103436fa1609c46b0cc536
    domain: zha
    type: remote_button_long_press
    subtype: dim_down
    trigger: device
conditions: []
actions:
  - action: persistent_notification.create
    metadata: {}
    data:
      message: Dimm down
mode: single
```
Device card long:
```
IKEA TRADFRI on/off switch Remote Button Long Release - Dim Up event was fired
19:25:46 
IKEA TRADFRI on/off switch Move event was fired with parameters: {'move_mode': 1, 'rate': 83, 'options_mask': 0, 'options_override': 0}
19:25:45 
```

In the log:
```
May 27, 2025
OnOff Dimm Dow triggered by event 'zha_event'
19:25:45
```
Automation trace:
```
this:
  entity_id: automation.onoff_dimm_dow
  state: 'on'
  attributes:
    id: '1748366688543'
    last_triggered: null
    mode: single
    current: 0
    friendly_name: OnOff Dimm Dow
  last_changed: '2025-05-27T17:25:05.209221+00:00'
  last_reported: '2025-05-27T17:25:05.211632+00:00'
  last_updated: '2025-05-27T17:25:05.209221+00:00'
  context:
    id: 01JW9CDGHSVDN3V51MFAM52T9T
```
So my automation looks working OK then i getting the notification.

If you is getting:
```
Rodret Dim Down triggered by IKEA RODRET Dimmer Move event was fired with parameters: {'move_mode': 1, 'rate': 83, 'options_mask': 0, 'options_override': 0} 
```
its looks like you is not using OnOff switch but is using one Rodret that is also working OK (also tested) and also cant detect if long release is from up or down and the OnOff.
What is the device `device_id: 3dbdcdf4594908df4643dc3808077f62` type ??
