### ISSUE TITLE
[Device Support Request] Cleverio / iHorn - Scenario Button (HO-011ZB)

### ISSUE THREAD

**Issue by Tagnard** [zigpy/zha-device-handlers#2205]
**Is your feature request related to a problem? Please describe.**
Button presses are not recognized

**Describe the solution you'd like**
I want it to be able to handle the single-, dubbel- and long press events

<details>

<summary>Device signature</summary>

```yaml
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4098, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0000",
      "in_clusters": [
        "0x0000",
        "0x0001",
        "0x0006"
      ],
      "out_clusters": [
        "0x0006",
        "0x000a",
        "0x0019"
      ]
    }
  },
  "manufacturer": "_TYZB01_4qw4rl1u",
  "model": "TS0041A",
  "class": "zigpy.device.Device"
}
```

</details>

<details>

<summary>Diagnostic information</summary>

```yaml
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.2.5",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.7",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Stockholm",
    "os_name": "Linux",
    "os_version": "5.15.90",
    "supervisor": "2023.01.1",
    "host_os": "Home Assistant OS 9.5",
    "docker_version": "20.10.22",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {},
  "integration_manifest": {
    "domain": "zha",
    "name": "Zigbee Home Automation",
    "config_flow": true,
    "documentation": "https://www.home-assistant.io/integrations/zha",
    "requirements": [
      "bellows==0.34.7",
      "pyserial==3.5",
      "pyserial-asyncio==0.6",
      "zha-quirks==0.0.92",
      "zigpy-deconz==0.19.2",
      "zigpy==0.53.0",
      "zigpy-xbee==0.16.2",
      "zigpy-zigate==0.10.3",
      "zigpy-znp==0.9.2"
    ],
    "usb": [
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*2652*",
        "known_devices": [
          "slae.sh cc2652rb stick"
        ]
      },
      {
        "vid": "1A86",
        "pid": "55D4",
        "description": "*sonoff*plus*",
        "known_devices": [
          "sonoff zigbee dongle plus v2"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*sonoff*plus*",
        "known_devices": [
          "sonoff zigbee dongle plus"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*zigstar*",
        "known_devices": [
          "ZigStar Coordinators"
        ]
      },
      {
        "vid": "1CF1",
        "pid": "0030",
        "description": "*conbee*",
        "known_devices": [
          "Conbee II"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8A2A",
        "description": "*zigbee*",
        "known_devices": [
          "Nortek HUSBZB-1"
        ]
      },
      {
        "vid": "0403",
        "pid": "6015",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate+"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8B34",
        "description": "*bv 2010/10*",
        "known_devices": [
          "Bitron Video AV2010/10"
        ]
      }
    ],
    "codeowners": [
      "@dmulcahey",
      "@adminiuga",
      "@puddly"
    ],
    "zeroconf": [
      {
        "type": "_esphomelib._tcp.local.",
        "name": "tube*"
      },
      {
        "type": "_zigate-zigbee-gateway._tcp.local.",
        "name": "*zigate*"
      },
      {
        "type": "_zigstar_gw._tcp.local.",
        "name": "*zigstar*"
      },
      {
        "type": "_slzb-06._tcp.local.",
        "name": "slzb-06*"
      }
    ],
    "dependencies": [
      "file_upload"
    ],
    "after_dependencies": [
      "onboarding",
      "usb",
      "zeroconf"
    ],
    "iot_class": "local_polling",
    "loggers": [
      "aiosqlite",
      "bellows",
      "crccheck",
      "pure_pcapy3",
      "zhaquirks",
      "zigpy",
      "zigpy_deconz",
      "zigpy_xbee",
      "zigpy_zigate",
      "zigpy_znp"
    ],
    "is_built_in": true
  },
  "data": {
    "ieee": "**REDACTED**",
    "nwk": 49908,
    "manufacturer": "_TYZB01_4qw4rl1u",
    "model": "TS0041A",
    "name": "_TYZB01_4qw4rl1u TS0041A",
    "quirk_applied": false,
    "quirk_class": "zigpy.device.Device",
    "manufacturer_code": 4098,
    "power_source": "Battery or Unknown",
    "lqi": 255,
    "rssi": -54,
    "last_seen": "2023-02-18T15:51:22",
    "available": true,
    "device_type": "EndDevice",
    "signature": {
      "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4098, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
      "endpoints": {
        "1": {
          "profile_id": 260,
          "device_type": "0x0000",
          "in_clusters": [
            "0x0000",
            "0x0001",
            "0x0006"
          ],
          "out_clusters": [
            "0x0006",
            "0x000a",
            "0x0019"
          ]
        }
      }
    },
    "active_coordinator": false,
    "entities": [
      {
        "entity_id": "sensor.tyzb01_4qw4rl1u_ts0041a_battery",
        "name": "_TYZB01_4qw4rl1u TS0041A"
      },
      {
        "entity_id": "switch.tyzb01_4qw4rl1u_ts0041a_switch",
        "name": "_TYZB01_4qw4rl1u TS0041A"
      }
    ],
    "neighbors": [],
    "routes": [],
    "endpoint_names": [
      {
        "name": "ON_OFF_SWITCH"
      }
    ],
    "user_given_name": null,
    "device_reg_id": "3eb26f5a0e26e5cc7cc564563ad4b5d8",
    "area_id": "bedroom",
    "cluster_details": {
      "1": {
        "device_type": {
          "name": "ON_OFF_SWITCH",
          "id": 0
        },
        "profile_id": 260,
        "in_clusters": {
          "0x0000": {
            "endpoint_attribute": "basic",
            "attributes": {
              "0x0004": {
                "attribute_name": "manufacturer",
                "value": "_TYZB01_4qw4rl1u"
              },
              "0x0005": {
                "attribute_name": "model",
                "value": "TS0041A"
              }
            },
            "unsupported_attributes": {}
          },
          "0x0001": {
            "endpoint_attribute": "power",
            "attributes": {
              "0x0020": {
                "attribute_name": "battery_voltage",
                "value": 30
              },
              "0x0021": {
                "attribute_name": "battery_percentage_remaining",
                "value": 200
              }
            },
            "unsupported_attributes": {
              "0x0031": {
                "attribute_name": "battery_size"
              },
              "0x0033": {
                "attribute_name": "battery_quantity"
              }
            }
          },
          "0x0006": {
            "endpoint_attribute": "on_off",
            "attributes": {
              "0x0000": {
                "attribute_name": "on_off",
                "value": 0
              }
            },
            "unsupported_attributes": {
              "0x4003": {
                "attribute_name": "start_up_on_off"
              }
            }
          }
        },
        "out_clusters": {
          "0x0019": {
            "endpoint_attribute": "ota",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x000a": {
            "endpoint_attribute": "time",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0006": {
            "endpoint_attribute": "on_off",
            "attributes": {},
            "unsupported_attributes": {}
          }
        }
      }
    }
  }
}
```

</details>

<details>
<summary>Additional logs</summary>

```
# single press

Received a packet: ZigbeePacket(src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0xC2F4), src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=1, source_route=None, extended_timeout=False, tsn=43, profile_id=260, cluster_id=6, data=Serialized[b'\x01\x0c\xfd\x00'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=255, rssi=-55)
[0xC2F4:1:0x0006] Received ZCL frame: b'\x01\x0c\xfd\x00'
[0xC2F4:1:0x0006] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.CLUSTER_COMMAND: 1>, is_manufacturer_specific=0, direction=<Direction.Server_to_Client: 0>, disable_default_response=0, reserved=0, *is_cluster=True, *is_general=False, *is_reply=False), tsn=12, command_id=253, *direction=<Direction.Server_to_Client: 0>, *is_reply=False)
[0xC2F4:1:0x0006] Unknown cluster command 253 b'\x00'
[0xC2F4:1:0x0006] Received command 0xFD (TSN 12): b'\x00'
[0xC2F4:1:0x0006] No explicit handler for cluster command 0xfd: b'\x00'
[0xC2F4:1:0x0006]: received '253' command with b'\x00' args on cluster_id '6' tsn '12'
Received a packet: ZigbeePacket(src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0xC2F4), src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=1, source_route=None, extended_timeout=False, tsn=44, profile_id=260, cluster_id=6, data=Serialized[b'\x01\x0c\xfd\x00'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=255, rssi=-53)
[0xC2F4:1:0x0006] Received ZCL frame: b'\x01\x0c\xfd\x00'
[0xC2F4:1:0x0006] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.CLUSTER_COMMAND: 1>, is_manufacturer_specific=0, direction=<Direction.Server_to_Client: 0>, disable_default_response=0, reserved=0, *is_cluster=True, *is_general=False, *is_reply=False), tsn=12, command_id=253, *direction=<Direction.Server_to_Client: 0>, *is_reply=False)
[0xC2F4:1:0x0006] Unknown cluster command 253 b'\x00'
[0xC2F4:1:0x0006] Received command 0xFD (TSN 12): b'\x00'
[0xC2F4:1:0x0006] No explicit handler for cluster command 0xfd: b'\x00'
[0xC2F4:1:0x0006]: received '253' command with b'\x00' args on cluster_id '6' tsn '12'
Received a packet: ZigbeePacket(src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0xC2F4), src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=1, source_route=None, extended_timeout=False, tsn=45, profile_id=260, cluster_id=6, data=Serialized[b'\x01\x0c\xfd\x00'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=255, rssi=-65)
[0xC2F4:1:0x0006] Received ZCL frame: b'\x01\x0c\xfd\x00'
[0xC2F4:1:0x0006] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.CLUSTER_COMMAND: 1>, is_manufacturer_specific=0, direction=<Direction.Server_to_Client: 0>, disable_default_response=0, reserved=0, *is_cluster=True, *is_general=False, *is_reply=False), tsn=12, command_id=253, *direction=<Direction.Server_to_Client: 0>, *is_reply=False)
[0xC2F4:1:0x0006] Unknown cluster command 253 b'\x00'
[0xC2F4:1:0x0006] Received command 0xFD (TSN 12): b'\x00'
[0xC2F4:1:0x0006] No explicit handler for cluster command 0xfd: b'\x00'
[0xC2F4:1:0x0006]: received '253' command with b'\x00' args on cluster_id '6' tsn '12'
Received a packet: ZigbeePacket(src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0xC2F4), src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=1, source_route=None, extended_timeout=False, tsn=46, profile_id=260, cluster_id=6, data=Serialized[b'\x01\x0c\xfd\x00'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=255, rssi=-64)
[0xC2F4:1:0x0006] Received ZCL frame: b'\x01\x0c\xfd\x00'
[0xC2F4:1:0x0006] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.CLUSTER_COMMAND: 1>, is_manufacturer_specific=0, direction=<Direction.Server_to_Client: 0>, disable_default_response=0, reserved=0, *is_cluster=True, *is_general=False, *is_reply=False), tsn=12, command_id=253, *direction=<Direction.Server_to_Client: 0>, *is_reply=False)
[0xC2F4:1:0x0006] Unknown cluster command 253 b'\x00'
[0xC2F4:1:0x0006] Received command 0xFD (TSN 12): b'\x00'
[0xC2F4:1:0x0006] No explicit handler for cluster command 0xfd: b'\x00'
[0xC2F4:1:0x0006]: received '253' command with b'\x00' args on cluster_id '6' tsn '12'
Received a packet: ZigbeePacket(src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0xC2F4), src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=1, source_route=None, extended_timeout=False, tsn=47, profile_id=260, cluster_id=6, data=Serialized[b'\x01\x0c\xfd\x00'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=255, rssi=-63)
[0xC2F4:1:0x0006] Received ZCL frame: b'\x01\x0c\xfd\x00'
[0xC2F4:1:0x0006] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.CLUSTER_COMMAND: 1>, is_manufacturer_specific=0, direction=<Direction.Server_to_Client: 0>, disable_default_response=0, reserved=0, *is_cluster=True, *is_general=False, *is_reply=False), tsn=12, command_id=253, *direction=<Direction.Server_to_Client: 0>, *is_reply=False)
[0xC2F4:1:0x0006] Unknown cluster command 253 b'\x00'
[0xC2F4:1:0x0006] Received command 0xFD (TSN 12): b'\x00'
[0xC2F4:1:0x0006] No explicit handler for cluster command 0xfd: b'\x00'
[0xC2F4:1:0x0006]: received '253' command with b'\x00' args on cluster_id '6' tsn '12'

# dubble press

Received a packet: ZigbeePacket(src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0xC2F4), src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=1, source_route=None, extended_timeout=False, tsn=48, profile_id=260, cluster_id=6, data=Serialized[b'\x01\r\xfd\x01'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=255, rssi=-53)
[0xC2F4:1:0x0006] Received ZCL frame: b'\x01\r\xfd\x01'
[0xC2F4:1:0x0006] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.CLUSTER_COMMAND: 1>, is_manufacturer_specific=0, direction=<Direction.Server_to_Client: 0>, disable_default_response=0, reserved=0, *is_cluster=True, *is_general=False, *is_reply=False), tsn=13, command_id=253, *direction=<Direction.Server_to_Client: 0>, *is_reply=False)
[0xC2F4:1:0x0006] Unknown cluster command 253 b'\x01'
[0xC2F4:1:0x0006] Received command 0xFD (TSN 13): b'\x01'
[0xC2F4:1:0x0006] No explicit handler for cluster command 0xfd: b'\x01'
[0xC2F4:1:0x0006]: received '253' command with b'\x01' args on cluster_id '6' tsn '13'
Received a packet: ZigbeePacket(src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x6A68), src_ep=2, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=1, source_route=None, extended_timeout=False, tsn=21, profile_id=260, cluster_id=1024, data=Serialized[b'\x08\x9f\n\x00\x00!\x042'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=255, rssi=-71)
[0x6A68:2:0x0400] Received ZCL frame: b'\x08\x9f\n\x00\x00!\x042'
[0x6A68:2:0x0400] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.GLOBAL_COMMAND: 0>, is_manufacturer_specific=0, direction=<Direction.Client_to_Server: 1>, disable_default_response=0, reserved=0, *is_cluster=False, *is_general=True, *is_reply=True), tsn=159, command_id=10, *direction=<Direction.Client_to_Server: 1>, *is_reply=True)
[0x6A68:2:0x0400] Decoded ZCL frame: IlluminanceMeasurement:Report_Attributes(attribute_reports=[Attribute(attrid=0x0000, value=TypeValue(type=uint16_t, value=12804))])
[0x6A68:2:0x0400] Received command 0x0A (TSN 159): Report_Attributes(attribute_reports=[Attribute(attrid=0x0000, value=TypeValue(type=uint16_t, value=12804))])
[0x6A68:2:0x0400] Attribute report received: measured_value=12804
[0x6A68:2:0x0400] Sending reply header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.GLOBAL_COMMAND: 0>, is_manufacturer_specific=False, direction=<Direction.Client_to_Server: 1>, disable_default_response=1, reserved=0, *is_cluster=False, *is_general=True, *is_reply=True), tsn=159, command_id=<GeneralCommand.Default_Response: 11>, *direction=<Direction.Client_to_Server: 1>, *is_reply=True)
[0x6A68:2:0x0400] Sending reply: Default_Response(command_id=10, status=<Status.SUCCESS: 0>)
Received a packet: ZigbeePacket(src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0xC2F4), src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=1, source_route=None, extended_timeout=False, tsn=49, profile_id=260, cluster_id=6, data=Serialized[b'\x01\r\xfd\x01'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=255, rssi=-52)
[0xC2F4:1:0x0006] Received ZCL frame: b'\x01\r\xfd\x01'
[0xC2F4:1:0x0006] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.CLUSTER_COMMAND: 1>, is_manufacturer_specific=0, direction=<Direction.Server_to_Client: 0>, disable_default_response=0, reserved=0, *is_cluster=True, *is_general=False, *is_reply=False), tsn=13, command_id=253, *direction=<Direction.Server_to_Client: 0>, *is_reply=False)
[0xC2F4:1:0x0006] Unknown cluster command 253 b'\x01'
[0xC2F4:1:0x0006] Received command 0xFD (TSN 13): b'\x01'
[0xC2F4:1:0x0006] No explicit handler for cluster command 0xfd: b'\x01'
[0xC2F4:1:0x0006]: received '253' command with b'\x01' args on cluster_id '6' tsn '13'
Received a packet: ZigbeePacket(src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0xC2F4), src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=1, source_route=None, extended_timeout=False, tsn=50, profile_id=260, cluster_id=6, data=Serialized[b'\x01\r\xfd\x01'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=255, rssi=-65)
[0xC2F4:1:0x0006] Received ZCL frame: b'\x01\r\xfd\x01'
[0xC2F4:1:0x0006] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.CLUSTER_COMMAND: 1>, is_manufacturer_specific=0, direction=<Direction.Server_to_Client: 0>, disable_default_response=0, reserved=0, *is_cluster=True, *is_general=False, *is_reply=False), tsn=13, command_id=253, *direction=<Direction.Server_to_Client: 0>, *is_reply=False)
[0xC2F4:1:0x0006] Unknown cluster command 253 b'\x01'
[0xC2F4:1:0x0006] Received command 0xFD (TSN 13): b'\x01'
[0xC2F4:1:0x0006] No explicit handler for cluster command 0xfd: b'\x01'
[0xC2F4:1:0x0006]: received '253' command with b'\x01' args on cluster_id '6' tsn '13'
Received a packet: ZigbeePacket(src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0xC2F4), src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=1, source_route=None, extended_timeout=False, tsn=51, profile_id=260, cluster_id=6, data=Serialized[b'\x01\r\xfd\x01'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=255, rssi=-62)
[0xC2F4:1:0x0006] Received ZCL frame: b'\x01\r\xfd\x01'
[0xC2F4:1:0x0006] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.CLUSTER_COMMAND: 1>, is_manufacturer_specific=0, direction=<Direction.Server_to_Client: 0>, disable_default_response=0, reserved=0, *is_cluster=True, *is_general=False, *is_reply=False), tsn=13, command_id=253, *direction=<Direction.Server_to_Client: 0>, *is_reply=False)
[0xC2F4:1:0x0006] Unknown cluster command 253 b'\x01'
[0xC2F4:1:0x0006] Received command 0xFD (TSN 13): b'\x01'
[0xC2F4:1:0x0006] No explicit handler for cluster command 0xfd: b'\x01'
[0xC2F4:1:0x0006]: received '253' command with b'\x01' args on cluster_id '6' tsn '13'
Received a packet: ZigbeePacket(src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0xC2F4), src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=1, source_route=None, extended_timeout=False, tsn=52, profile_id=260, cluster_id=6, data=Serialized[b'\x01\r\xfd\x01'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=255, rssi=-61)
[0xC2F4:1:0x0006] Received ZCL frame: b'\x01\r\xfd\x01'
[0xC2F4:1:0x0006] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.CLUSTER_COMMAND: 1>, is_manufacturer_specific=0, direction=<Direction.Server_to_Client: 0>, disable_default_response=0, reserved=0, *is_cluster=True, *is_general=False, *is_reply=False), tsn=13, command_id=253, *direction=<Direction.Server_to_Client: 0>, *is_reply=False)
[0xC2F4:1:0x0006] Unknown cluster command 253 b'\x01'
[0xC2F4:1:0x0006] Received command 0xFD (TSN 13): b'\x01'
[0xC2F4:1:0x0006] No explicit handler for cluster command 0xfd: b'\x01'
[0xC2F4:1:0x0006]: received '253' command with b'\x01' args on cluster_id '6' tsn '13'

# long press

[0xCAC6](TS0203): Device seen - marking the device available and resetting counter
[0xCAC6](TS0203): Update device availability -  device available: True - new availability: True - changed: False
Received a packet: ZigbeePacket(src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0xC2F4), src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=1, source_route=None, extended_timeout=False, tsn=53, profile_id=260, cluster_id=6, data=Serialized[b'\x01\x0e\xfd\x02'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=255, rssi=-62)
[0xC2F4:1:0x0006] Received ZCL frame: b'\x01\x0e\xfd\x02'
[0xC2F4:1:0x0006] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.CLUSTER_COMMAND: 1>, is_manufacturer_specific=0, direction=<Direction.Server_to_Client: 0>, disable_default_response=0, reserved=0, *is_cluster=True, *is_general=False, *is_reply=False), tsn=14, command_id=253, *direction=<Direction.Server_to_Client: 0>, *is_reply=False)
[0xC2F4:1:0x0006] Unknown cluster command 253 b'\x02'
[0xC2F4:1:0x0006] Received command 0xFD (TSN 14): b'\x02'
[0xC2F4:1:0x0006] No explicit handler for cluster command 0xfd: b'\x02'
[0xC2F4:1:0x0006]: received '253' command with b'\x02' args on cluster_id '6' tsn '14'
Received a packet: ZigbeePacket(src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0xC2F4), src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=1, source_route=None, extended_timeout=False, tsn=54, profile_id=260, cluster_id=6, data=Serialized[b'\x01\x0e\xfd\x02'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=255, rssi=-63)
[0xC2F4:1:0x0006] Received ZCL frame: b'\x01\x0e\xfd\x02'
[0xC2F4:1:0x0006] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.CLUSTER_COMMAND: 1>, is_manufacturer_specific=0, direction=<Direction.Server_to_Client: 0>, disable_default_response=0, reserved=0, *is_cluster=True, *is_general=False, *is_reply=False), tsn=14, command_id=253, *direction=<Direction.Server_to_Client: 0>, *is_reply=False)
[0xC2F4:1:0x0006] Unknown cluster command 253 b'\x02'
[0xC2F4:1:0x0006] Received command 0xFD (TSN 14): b'\x02'
[0xC2F4:1:0x0006] No explicit handler for cluster command 0xfd: b'\x02'
[0xC2F4:1:0x0006]: received '253' command with b'\x02' args on cluster_id '6' tsn '14'
Received a packet: ZigbeePacket(src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0xC2F4), src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=1, source_route=None, extended_timeout=False, tsn=55, profile_id=260, cluster_id=6, data=Serialized[b'\x01\x0e\xfd\x02'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=255, rssi=-62)
[0xC2F4:1:0x0006] Received ZCL frame: b'\x01\x0e\xfd\x02'
[0xC2F4:1:0x0006] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.CLUSTER_COMMAND: 1>, is_manufacturer_specific=0, direction=<Direction.Server_to_Client: 0>, disable_default_response=0, reserved=0, *is_cluster=True, *is_general=False, *is_reply=False), tsn=14, command_id=253, *direction=<Direction.Server_to_Client: 0>, *is_reply=False)
[0xC2F4:1:0x0006] Unknown cluster command 253 b'\x02'
[0xC2F4:1:0x0006] Received command 0xFD (TSN 14): b'\x02'
[0xC2F4:1:0x0006] No explicit handler for cluster command 0xfd: b'\x02'
[0xC2F4:1:0x0006]: received '253' command with b'\x02' args on cluster_id '6' tsn '14'
Received a packet: ZigbeePacket(src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0xC2F4), src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=1, source_route=None, extended_timeout=False, tsn=56, profile_id=260, cluster_id=6, data=Serialized[b'\x01\x0e\xfd\x02'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=255, rssi=-65)
[0xC2F4:1:0x0006] Received ZCL frame: b'\x01\x0e\xfd\x02'
[0xC2F4:1:0x0006] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.CLUSTER_COMMAND: 1>, is_manufacturer_specific=0, direction=<Direction.Server_to_Client: 0>, disable_default_response=0, reserved=0, *is_cluster=True, *is_general=False, *is_reply=False), tsn=14, command_id=253, *direction=<Direction.Server_to_Client: 0>, *is_reply=False)
[0xC2F4:1:0x0006] Unknown cluster command 253 b'\x02'
[0xC2F4:1:0x0006] Received command 0xFD (TSN 14): b'\x02'
[0xC2F4:1:0x0006] No explicit handler for cluster command 0xfd: b'\x02'
[0xC2F4:1:0x0006]: received '253' command with b'\x02' args on cluster_id '6' tsn '14'
Received a packet: ZigbeePacket(src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0xC2F4), src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=1, source_route=None, extended_timeout=False, tsn=57, profile_id=260, cluster_id=6, data=Serialized[b'\x01\x0e\xfd\x02'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=255, rssi=-66)
[0xC2F4:1:0x0006] Received ZCL frame: b'\x01\x0e\xfd\x02'
[0xC2F4:1:0x0006] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.CLUSTER_COMMAND: 1>, is_manufacturer_specific=0, direction=<Direction.Server_to_Client: 0>, disable_default_response=0, reserved=0, *is_cluster=True, *is_general=False, *is_reply=False), tsn=14, command_id=253, *direction=<Direction.Server_to_Client: 0>, *is_reply=False)
[0xC2F4:1:0x0006] Unknown cluster command 253 b'\x02'
[0xC2F4:1:0x0006] Received command 0xFD (TSN 14): b'\x02'
[0xC2F4:1:0x0006] No explicit handler for cluster command 0xfd: b'\x02'
[0xC2F4:1:0x0006]: received '253' command with b'\x02' args on cluster_id '6' tsn '14'
[0xC2F4](TS0041A): Device seen - marking the device available and resetting counter
[0xC2F4](TS0041A): Update device availability -  device available: True - new availability: True - changed: False
```

</details>

**Additional context**
