### ISSUE TITLE
[BUG] Hue switch module long release triggers don't fire

### ISSUE THREAD

**Issue by andyjenkinson** [zigpy/zha-device-handlers#2571]
### Bug description

I have a Hue in-wall switch module (RDM001) configured in mode 3 (double momentary switches) and the events appear to be firing as intended. Both left and right button presses trigger automations correctly using the pre-configured device triggers. However the 'long release' device triggers don't trigger automations. This automation is very simple, and was set up via the UI by selecting from the list of available 'device' events. Looking at the event configuration in YAML it appears correct compared to 'press' triggers that _do_ work, but nonetheless it doesn't trigger the automation.

An event indeed is fired when the switch is released, and shows up in the logbook on the device page, so it's not a hardware, installation or configuration issue. I am also able to work around it by configuring the automation to use manual zha_event triggers instead of the pre-configured device events. I notice that the names of the events are different in the automation vs the logbook ("turn_on" vs "left") but this is true of all the events that work correctly also, so I guess is expected? I'm not so familiar with how events are connected to device triggers.

Looking at the quirk code, I _think_ the problem is that the 'command' string for the device automation triggers (line [187](https://github.com/zigpy/zha-device-handlers/blob/f99806ad6a54bdd1cbd1bab2c55be072fe3cdf33/zhaquirks/philips/rdm001.py#L187C15-L187C15) and [195](https://github.com/zigpy/zha-device-handlers/blob/f99806ad6a54bdd1cbd1bab2c55be072fe3cdf33/zhaquirks/philips/rdm001.py#L195)) doesn't match the ZHA event. As I said I'nm not too familiar with the architecture so I am making assumptions about how these two things are connected, i.e. that the 'command' string from the zha_event is checked against the list of device_automation_triggers.

So, I _think_ `left_long_release` should be `left_hold_release` (and likewise for right).

If anyone is able to test/confirm my findings I'm happy to submit a PR but since it's working for me with my workaround I'm afraid I don't really have the time to set up a test environment to be able to test it.

### Steps to reproduce

1. Install, add to ZHA and configure the mode of a switch module
2. Create a new automation
3. Choose a 'device' trigger, and select the device.
4. Select either the '"Turn on" released after long press' or  "Right" released after long press' options
5. Save
6. Long press the button
7. Observe automation not firing

### Expected behavior

When releasing from the long press of either left or right channel of the module, automations using the appropriate 'device' trigger should fire.

### Screenshots/Video

<details><summary>Screenshots/Video</summary>

[Paste/upload your media here]

</details>

### Additional information

This is what the zha_event looks like:
```
event_type: zha_event
data:
  device_ieee: 00:17:88:01:0c:c3:b8:6c
  unique_id: 00:17:88:01:0c:c3:b8:6c:1:0xfc00
  device_id: b0c34a917c3ced6a16dce4966b77695f
  endpoint_id: 1
  cluster_id: 64512
  command: left_hold_release
  args:
    button: left
    press_type: hold_release
    command_id: 0
    args:
      - 1
      - 3145728
      - 3
      - 33
      - 37
      - 0
  params: {}
origin: LOCAL
time_fired: "2023-09-06T16:37:17.025838+00:00"
context:
  id: 01H9NNNWK1R7FBVW4X80JQY0A9
  parent_id: null
  user_id: null
```

For the sake of clarity, these triggers (which the UI generates itself) do not work:
```
trigger:
  - device_id: b0c34a917c3ced6a16dce4966b77695f
    domain: zha
    platform: device
    type: remote_button_long_release
    subtype: turn_on
  - device_id: b0c34a917c3ced6a16dce4966b77695f
    domain: zha
    platform: device
    type: remote_button_long_release
    subtype: right
```

These events (that I manually configured by listening for `zha_event` events in the developer tools) DO work:
```
trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: b0c34a917c3ced6a16dce4966b77695f
      command: left_hold_release
  - platform: event
    event_type: zha_event
    event_data:
      device_id: b0c34a917c3ced6a16dce4966b77695f
      command: right_hold_release
```
