### ISSUE TITLE
Ignore problematic firmware updates of Aqara MAEU01 plugs

### ISSUE THREAD

**Issue by FlorianFreudiger** [zigpy/zha-device-handlers#3067]
### Bug description

As already established, newer firmware versions (>v32) of the Aqara MAEU01 plugs have the problem of toggling on/off when certain remotes are used. Because v32 is already well supported, ZHA should not offer firmware updates beyond v32.

Relevant information on the toggling issue:

https://github.com/zigpy/zha-device-handlers/blob/4b3d6591c72302fd82e1b5a6e4ee30eb2e08dd9c/zhaquirks/xiaomi/aqara/plug_eu.py#L44-L47

- https://github.com/zigpy/zha-device-handlers/pull/1656#issuecomment-1244750465
- https://github.com/zigpy/zha-device-handlers/pull/1706
- https://github.com/Koenkk/zigbee2mqtt/issues/13903

### Steps to reproduce

1. Have Aqara MAEU01 plug with v32 firmware version connected.
2. Browse to the Settings in Home Assistant
3. See ZHA offer plug update from 0x00000020 (v32) to 0x00000029 (v41)

### Expected behavior

ZHA to not offer an update beyond v32 for these plugs.

**Comment by TheJulianJES** [comment]
What do you have in your `configuration.yaml`?

**Comment by FlorianFreudiger** [comment]
> What do you have in your `configuration.yaml`?

```
zha:
  zigpy_config:
    ota:
      ikea_provider: true
      ledvance_provider: true
      salus_provider: true
      inovelli_provider: true
      otau_directory: /config/zigpy_ota
```
I previously used this configuration to be able to manually downgrade to the v32 version. The `/config/zigpy_ota` directory has since been empty.
