### ISSUE TITLE
[Device Support Request] Avatto 1/2-ch dimmer. TS0601 _TZE204_o9gyszw2/_TZE204_5cuocqty

### ISSUE THREAD

**Issue by gruzzy** [zigpy/zha-device-handlers#3141]
### Problem description

I bought a couple of devices from AliEexpress (https://www.aliexpress.com/item/1005006524716136.html)

Devices were added to Home Assistance server without issues, but didn't expose any controls. After reading documentation, I have madew a custom quirk and devices are working fine now.

### Solution description

ZHA logs suggest to contribute changes into the main branch.

### Screenshots/Video

<details><summary>Screenshots/Video</summary>

[Paste/upload your media here]
![image](https://github.com/zigpy/zha-device-handlers/assets/33974769/60bafa03-ff41-44a0-b27f-af8a61966c24)
![image](https://github.com/zigpy/zha-device-handlers/assets/33974769/e1449df7-13ed-4e6a-8b14-9482d6686804)

</details>

### Device signature

<details><summary>Device signature</summary>

```json
[Paste the device signature here]
```

</details>

### Diagnostic information

<details><summary>Diagnostic information</summary>

```json
[Paste the diagnostic information here]
```

</details>

### Logs

<details><summary>Logs</summary>

```python
[Paste the logs here]
```

</details>

### Custom quirk

<details><summary>Custom quirk1</summary>
class TuyaSingleSwitchDimmerGP(TuyaDimmerSwitch):
    """Tuya touch switch device."""

    signature = {
        MODELS_INFO: [
            ("_TZE200_3p5ydos3", "TS0601"),
            ("_TZE200_ip2akl4w", "TS0601"),
            ("_TZE200_vucankjx", "TS0601"),  # Loratap
            ("_TZE200_y8yjulon", "TS0601"),
            ("_TZE204_n9ctkb6j", "TS0601"),  # For BSEED switch
            ("_TZE204_5cuocqty", "TS0601"), #Avattto ZDMS16-1
        ],
</details>

<details><summary>Custom quirk2</summary>
class TuyaDoubleSwitchDimmerGP(TuyaDimmerSwitch):
    """Tuya double channel dimmer device."""

    signature = {
        MODELS_INFO: [
            ("_TZE200_fjjbhx9d", "TS0601"),
            ("_TZE200_gwkapsoq", "TS0601"),  # Loratap
            ("_TZE204_zenj4lxv", "TS0601"),
            ("_TZE204_o9gyszw2", "TS0601"), #Avattto ZDMS16-2
        ],
</details>

**Comment by NH-Networks** [comment]
@gruzzy  are custom quirks complete?

seem to miss information? can you send me files or give full code ?

**Comment by gruzzy** [comment]
Sorry, I am not good in creating proper tickets yet :)

I found that extending the MODELS_INFO lists in tthe class signatures made devices working in HA.

One switch works as a TuyaSingleSwitchDimmerGP devices, another one is running as TuyaDoubleSwitchDimmerGP.

So, there are the only changes in the file **zhaquirks/tuya/ts0601_dimmer.py**:

> class TuyaSingleSwitchDimmerGP(TuyaDimmerSwitch): """Tuya touch switch device."""
> signature = {
>     MODELS_INFO: [
>         ("_TZE200_3p5ydos3", "TS0601"),
>         ("_TZE200_ip2akl4w", "TS0601"),
>         ("_TZE200_vucankjx", "TS0601"),  # Loratap
>         ("_TZE200_y8yjulon", "TS0601"),
>         ("_TZE204_n9ctkb6j", "TS0601"),  # For BSEED switch
>         **("_TZE204_5cuocqty", "TS0601"), #Avattto ZDMS16-1**
>     ],

> class TuyaDoubleSwitchDimmerGP(TuyaDimmerSwitch): """Tuya double channel dimmer device."""
> signature = {
>     MODELS_INFO: [
>         ("_TZE200_fjjbhx9d", "TS0601"),
>         ("_TZE200_gwkapsoq", "TS0601"),  # Loratap
>         ("_TZE204_zenj4lxv", "TS0601"),
>         **("_TZE204_o9gyszw2", "TS0601"), #Avattto ZDMS16-2**
>     ],
>

**Comment by NH-Networks** [comment]
Yeah i figured it out, my bad.. will created a pull request for change, as no one is assigned to this yet.

**Comment by NH-Networks** [comment]
Pull request created. lets see if it will be picked up.

**Comment by vrtsman** [comment]
does not work for me. How can I see the quirk is in place? I can see it in the studio code server environment and edit the py, but does it get loaded correctly?

**Comment by coen1111** [comment]
I see support for the on/off functionality is implemented in [3190](https://github.com/zigpy/zha-device-handlers/pull/3190). However, the Dataopoints in the Tuya manufacturing cluster are not added. Which does not enable changing the External Switch-Type as required by my application. An example implementation is present in Zigbee2MQTT [tuya.ts](https://github.com/RafaelDuncan/zigbee-herdsman-converters/blob/3d43ed3cee2606fd4ab517e215ecf9059b4cc7d8/src/devices/tuya.ts#L1614). I want to extend this support to ZHA. I tried making a custom quirks but did not succeed. Using the zha_toolkit I now try to create the command manually, however I did not succeed yet. I retrieved information on which command and cluster to write to from [823](https://github.com/zigpy/zigpy/discussions/823)

This is my action:

```
action: zha_toolkit.zcl_cmd
data:
  ieee: a4:c1:38:dc:2b:c5:a5:61  # Replace with your device's IEEE address
  endpoint_id: 1                 # The endpoint ID of the device, usually 1 for most devices
  cluster: 61184                 # 0xEF00 in decimal
  cmd: 4                         # The command ID for Send DP
  args:
    - 57                          # DP ID for External Switch-Type (check device specifics)
    - 0                          # Data type (0 for raw/unknown, may vary)
    - 2                          # Data value (set to 2 for Momentary)
```

What am I overlooking?
