### ISSUE TITLE
can ts1201.py send the same command through multiple ieee?

### ISSUE THREAD

**Issue by foice** [zigpy/zha-device-handlers#3350]
I have many of the same IR blasters that work with ts1201.py. each has its own ieee number. I want to send the same command through many ieee devices without creating a new autoamtion/script for each of the devices is it possible to just pass a list to `ieee`? 

I tried to play with the yaml but I did not succeed.

Here is my working yaml
```
- candele_6h:
    alias: Candele6H
    sequence:
    - service: zha.issue_zigbee_cluster_command
      data:
        cluster_type: in
        endpoint_id: 1
        cluster_id: 57348
        ieee: 0c:ae:5f:zz:zz:zz:22:f1
        command_type: server
        command: 2
        params:
          code: BZYjkRE+AuADAQOhBj4C4AcBQBPAA0AB4AcL4AMBQBvgBwFAE8ADQAHAC8AHCdmfliPOCD4C///gAgcCCD4C
    description: ''
    icon: mdi:candle

```
and my attempt to make ieee a list

```
        ieee: 
          - 0c:ae:5f:ff:fe:9z:z2:z1
             zz:we:44:ff:zz:dd:e3
```          
which failed because the interpreter has simpy removed the new line. I am not a master of YAML so maybe I am just missing that, but I suppose the python must be expecting a string not a list of strings ... 

Any idea to use the same command on multiple `ieee`?
