### ISSUE TITLE
[Device Support Request] SOMFY Situo 4 Zigbee

### ISSUE THREAD

**Issue by stephenjust** [zigpy/zha-device-handlers#3372]
### Problem description

The SOMFY Situo 4 Zigbee remote has 4 channels of up/down/stop button press events that can be consumed via zha_event events. It would be great to have these exposed as device events.

### Solution description

Add a device quirk with device_automation_triggers for each of the 12 possible button press events.

### Screenshots/Video

N/A

### Device signature

<details><summary>Device signature</summary>

```json
{
      "node_descriptor": {
        "logical_type": 2,
        "complex_descriptor_available": 0,
        "user_descriptor_available": 0,
        "reserved": 0,
        "aps_flags": 0,
        "frequency_band": 8,
        "mac_capability_flags": 128,
        "manufacturer_code": 4640,
        "maximum_buffer_size": 82,
        "maximum_incoming_transfer_size": 82,
        "server_mask": 11264,
        "maximum_outgoing_transfer_size": 82,
        "descriptor_capability_field": 0
      },
      "endpoints": {
        "1": {
          "profile_id": "0x0104",
          "device_type": "0x0203",
          "input_clusters": [
            "0x0000",
            "0x0003"
          ],
          "output_clusters": [
            "0x0003",
            "0x0005",
            "0x0006",
            "0x0102"
          ]
        },
        "2": {
          "profile_id": "0x0104",
          "device_type": "0x0203",
          "input_clusters": [
            "0x0000",
            "0x0003"
          ],
          "output_clusters": [
            "0x0003",
            "0x0005",
            "0x0006",
            "0x0102"
          ]
        },
        "3": {
          "profile_id": "0x0104",
          "device_type": "0x0203",
          "input_clusters": [
            "0x0000",
            "0x0003"
          ],
          "output_clusters": [
            "0x0003",
            "0x0005",
            "0x0006",
            "0x0102"
          ]
        },
        "4": {
          "profile_id": "0x0104",
          "device_type": "0x0203",
          "input_clusters": [
            "0x0000",
            "0x0003"
          ],
          "output_clusters": [
            "0x0003",
            "0x0005",
            "0x0006",
            "0x0102"
          ]
        },
        "232": {
          "profile_id": "0x0104",
          "device_type": "0x0005",
          "input_clusters": [
            "0x0000",
            "0x0001",
            "0x0003",
            "0x0020"
          ],
          "output_clusters": [
            "0x0003",
            "0x0019"
          ]
        }
      },
      "manufacturer": "SOMFY",
      "model": "Situo 4 Zigbee"
    }
```

</details>

### Diagnostic information

<details><summary>Diagnostic information</summary>

Up Channel 1:
```yml
event_type: zha_event
data:
  device_ieee: 4c:c2:06:ff:fe:20:71:1a
  unique_id: 4c:c2:06:ff:fe:20:71:1a:1:0x0102
  device_id: cf93139cb7546c272b7376b4d77d50b2
  endpoint_id: 1
  cluster_id: 258
  command: up_open
  args: []
  params: {}
```

Down Channel 1:
```yml
event_type: zha_event
data:
  device_ieee: 4c:c2:06:ff:fe:20:71:1a
  unique_id: 4c:c2:06:ff:fe:20:71:1a:1:0x0102
  device_id: cf93139cb7546c272b7376b4d77d50b2
  endpoint_id: 1
  cluster_id: 258
  command: down_close
  args: []
  params: {}
```

Stop Channel 1:
```yml
event_type: zha_event
data:
  device_ieee: 4c:c2:06:ff:fe:20:71:1a
  unique_id: 4c:c2:06:ff:fe:20:71:1a:1:0x0102
  device_id: cf93139cb7546c272b7376b4d77d50b2
  endpoint_id: 1
  cluster_id: 258
  command: stop
  args: []
  params: {}
```

Channels 2, 3, 4 differ only by endpoint_id:

Ex: Stop Channel 4:
```yml
event_type: zha_event
data:
  device_ieee: 4c:c2:06:ff:fe:20:71:1a
  unique_id: 4c:c2:06:ff:fe:20:71:1a:4:0x0102
  device_id: cf93139cb7546c272b7376b4d77d50b2
  endpoint_id: 4
  cluster_id: 258
  command: stop
  args: []
  params: {}
```

There do not appear to be any events reported for combinations of button presses, holding buttons, no event on release, etc. Just four each of Up pressed, Down pressed, Stop pressed.

</details>

### Logs

N/A

### Custom quirk

N/A
