### ISSUE TITLE
Are Tuya MOVE_HUE and MOVE_SATURATION supported?

### ISSUE THREAD

**Issue by SpeedyGoneZales** [zigpy/zha-device-handlers#3893]
I have a [device support request](https://github.com/zigpy/zha-device-handlers/issues/3738) open for a Tuya `_TZ3000_402vrq2i` TS004F Rotary Button.

I have made good progress (see custom quirk section in device support request) except for two actions, which are long press and continuous press:

<details><summary>Long press (release):</summary>    

```    
event_type: zha_event
data:
  device_ieee: a4:c1:38:ec:7a:54:ab:27
  unique_id: a4:c1:38:ec:7a:54:ab:27:1:0x0300
  device_id: 24649a18ec0cb8aade6a1eb621154d0d
  endpoint_id: 1
  cluster_id: 768
  command: move_saturation
  args:
    - 1
    - 200
  params:
    move_mode: 1
    rate: 200
    options_mask: null
    options_override: null
origin: LOCAL
time_fired: "2025-02-18T02:36:11.105878+00:00"
context:
  id: 01JMBEKEF1S2F39S06R9CWG972
  parent_id: null
  user_id: null
```    

</details>

<details><summary>Continuous press (will fire approximately every 0.75 seconds):</summary>    

```
event_type: zha_event
data:
  device_ieee: a4:c1:38:ec:7a:54:ab:27
  unique_id: a4:c1:38:ec:7a:54:ab:27:1:0x0300
  device_id: 24649a18ec0cb8aade6a1eb621154d0d
  endpoint_id: 1
  cluster_id: 768
  command: move_hue
  args:
    - 0
    - 15
  params:
    move_mode: 0
    rate: 15
    options_mask: null
    options_override: null
origin: LOCAL
time_fired: "2025-02-18T02:36:12.720619+00:00"
context:
  id: 01JMBEKG1G0JQEKY034CBD264V
  parent_id: null
  user_id: null
```
</details>

I seem to be unable to access to events.   
I tried `COMMAND_STEP_SATURATION` and `COMMAND_STEP_HUE` from [const.py](https://github.com/zigpy/zha-device-handlers/blob/dev/zhaquirks/const.py), but those do not accept the events sent by the button.   
Is there another way, or can support for `move_hue` and `move_saturation` be added?
