### ISSUE TITLE
[BUG] Philips Hue Motion Sensor (SML003) battery always at 100%

### ISSUE THREAD

**Issue by Sawtaytoes** [zigpy/zha-device-handlers#4128]
### Bug description

The battery reporting for the newer Philips Hue Motion Sensors (SML003) is always showing 100% via ZHA. The device never shows anything lower. I've had devices go offline because their battery depleted with no change to the reported battery remaining.

### Steps to reproduce

1. Pair a newer Philips Hue Motion Sensor (SML003) with ZHA.
2. Open the ZHA device in Home Assistant.
3. Leave it on for a few months.
4. No change in the battery levels. Still shows 100%.

### Expected behavior

I expect that the battery will track with the actual battery available in the two AAA batteries. I wanna know when the device will suddenly stop working.

There's also a point where the device doesn't work with Low sensitivity, but Medium and higher still work. I'd like to know at what point that occurs.

### Screenshots/Video

<details><summary>Screenshots/Video</summary>

![Image](https://github.com/user-attachments/assets/7ed3a9b0-f0a4-4d93-9d2f-114192f3cdc7)

</details>

### Device signature

<details><summary>Device signature</summary>

```json

[Paste the device signature here]

```

</details>

### Diagnostic information

<details><summary>Diagnostic information</summary>

```json

[Paste the diagnostic information here]

```

</details>

### Logs

<details><summary>Logs</summary>

```python

[Paste the logs here]

```

</details>

**Comment by MattWestb** [comment]
Do you have try doing one "reconfigure" from the device card and waking up the device so i can revive the commands and getting all green "lights" ?

By the way calling it one bug is not correct then its the device that is not reporting OK and not  the system that is handling the reported information OK.

I have no experience of the new version but old one was very tricky and buggy but the batteries was working for many years and the reporting was little . . .

**Comment by Sawtaytoes** [comment]
What do you need me to do? Click Reconfigure, get all green? Ah ok! The battery voltage isn't coming in correctly.

![Image](https://github.com/user-attachments/assets/1c1213c5-13ec-4cc2-b615-7739750a7763)

The number for `battery_voltage` is `3600/10800/1`.

**Comment by MattWestb** [comment]
Battery voltage is normally not being used only for bad Aqara devices and some more that is not reporting % and ZHA is calculating % from it.

The reconfigure looks OK and the battery % renaming shall being reported OK if device is doing it right.

Can you reading the attribute `battery_percentage_renaming` by from the device-card the tree dots (`...` ) right of  r`econfigure` and then `manage Zigbee device`,  `cluster`, `PowerConfiguration`, `Attributes` and select the `battery_percentage_remaining` and click `read attribute` and waking up the device so it can getting the command.
PS: The reading is X2 so if getting 120 its the real value 60%.

**Comment by Sawtaytoes** [comment]
![Image](https://github.com/user-attachments/assets/9a40a1e5-6541-448d-b7e3-a00653071c54)

There are 2 batteries, showing numbers 2 and 3.

I tried reading some other values, but this is the only other non-"None":

![Image](https://github.com/user-attachments/assets/7e0346bb-dbaa-482e-b422-6ddfb3ca8012)

**Comment by Sawtaytoes** [comment]
Incase this is helpful:
```yaml
{
  "node_descriptor": {
    "logical_type": 2,
    "complex_descriptor_available": 0,
    "user_descriptor_available": 0,
    "reserved": 0,
    "aps_flags": 0,
    "frequency_band": 8,
    "mac_capability_flags": 128,
    "manufacturer_code": 4107,
    "maximum_buffer_size": 82,
    "maximum_incoming_transfer_size": 128,
    "server_mask": 11264,
    "maximum_outgoing_transfer_size": 128,
    "descriptor_capability_field": 0
  },
  "endpoints": {
    "2": {
      "profile_id": "0x0104",
      "device_type": "0x0107",
      "input_clusters": [
        "0x0000",
        "0x0001",
        "0x0003",
        "0x0400",
        "0x0402",
        "0x0406"
      ],
      "output_clusters": [
        "0x0000",
        "0x0003",
        "0x0006",
        "0x0019"
      ]
    }
  },
  "manufacturer": "Signify Netherlands B.V.",
  "model": "SML003",
  "class": "zhaquirks.philips.motion.SignifyMotion"
}
```
