### ISSUE TITLE
[BUG] triple press don't work WXKG11LM

### ISSUE THREAD

**Issue by Nemesis24** [zigpy/zha-device-handlers#494]
**Describe the bug**
In automation editor triple press don't work ...
quadruple press is not present https://github.com/zigpy/zha-device-handlers/issues/173

in automation this is working
 for triple
```
- event_data:
      args:
        attribute_id: 32768
        value: 3
      command: attribute_updated
      device_ieee: 00:15:8d:00:02:01:60:b9
      unique_id: 00:15:8d:00:02:01:60:b9:1:0x0006
    event_type: zha_event
```

for quadruple

```
- event_data:
      args:
        attribute_id: 32768
        value: 4
      command: attribute_updated
      device_ieee: 00:15:8d:00:02:01:60:b9
      unique_id: 00:15:8d:00:02:01:60:b9:1:0x0006
    event_type: zha_event
```
