### ISSUE TITLE
[BUG] Sonoff ZBMINI classified as light instead of switch

### ISSUE THREAD

**Issue by malfroid** [zigpy/zha-device-handlers#654]
**Describe the bug**
After adding Sonoff ZBMINI = 01MINIZB to ZHA, the entity is classified as a light.
This device is not a light, but a switch.
It does not seem possible to change the domain of an entity from light to switch. See also [my post on the HA forum](https://community.home-assistant.io/t/sonoff-zbmini-added-via-zha-is-incorrectly-classified-as-a-light-should-be-switch/257878).

**To Reproduce**
1. Add Sonoff ZBMINI to Home Assistant via ZHA integration
2. Look at entity ID: shows light.<name>

**Expected behavior**
Entity should be have the domain switch, ID should show switch.<name>

**Screenshots**
<img width="599" alt="Screenshot 2020-12-20 at 17 39 35" src="https://user-images.githubusercontent.com/3715399/102721243-f5057e80-42f9-11eb-8e8a-389f5a9f4c68.png">

**Additional context**
Running Home Assistant 2020.12.1 + ZHA on Raspberry Pi 4 with Conbee II zigbee gateway.

Sonoff ZBMINI device signature:

``` json
{
  "node_descriptor": "NodeDescriptor(byte1=1, byte2=64, mac_capability_flags=142, manufacturer_code=4098, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=0)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0100",
      "in_clusters": [
        "0x0000",
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0006",
        "0x1000"
      ],
      "out_clusters": [
        "0x1000"
      ]
    },
    "242": {
      "profile_id": 41440,
      "device_type": "0x0061",
      "in_clusters": [],
      "out_clusters": [
        "0x0021"
      ]
    }
  },
  "manufacturer": "SONOFF",
  "model": "01MINIZB",
  "class": "zigpy.device.Device"
}
```

**Comment by dmulcahey** [comment]
This can be overridden in configuration.yaml in zha leveraging device config. There are examples on the forum. I don’t have any off hand.

**Comment by Adminiuga** [comment]
the `device_type = 0x0100` and per Zigbee Home Automation Profile, the device with type id 0x0100 is an on/off Light.
![image](https://user-images.githubusercontent.com/5826160/102815897-25e9c000-439b-11eb-8563-ea4ef868bb0e.png)

to override, add to configuration.yaml
```
zha:
  device_config:
    00:0b:57:ff:de:ad:be:ef-1:
       type: 'switch'
```

**Comment by dmulcahey** [comment]
Closing as work around supplied and the device is being treated correctly by ZHA.

**Comment by malfroid** [comment]
I looked up the ZBMINI hardware address in the UI:
<img width="352" alt="Screenshot 2020-12-22 at 12 18 51" src="https://user-images.githubusercontent.com/3715399/102883181-dd400e80-444f-11eb-8e95-9a6fd91dcd90.png">

I then added the proposed configuration by @Adminiuga to my  configuration.yaml. Full configuration.yaml:

``` yaml
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

zha:
  zigpy_config:
    ota:
      ikea_provider: true         # Auto update Trådfri devices
      ledvance_provider: true     # Auto update LEDVANCE devices
  device_config:
    84:71:27:ff:fe:93:17:24:      # Reclassify ZBMINI (kitchen ceiling light) as switch instead of light
      type: 'switch'
    84:71:27:ff:fe:93:10:ce:      # Reclassify ZBMINI (kitchen fan) as switch instead of light
      type: 'switch'
```

After saving configuration.yaml and restarting HA, the entity is still a light: 

<img width="601" alt="Screenshot 2020-12-22 at 12 21 06" src="https://user-images.githubusercontent.com/3715399/102883362-314af300-4450-11eb-9854-303d45eea4c1.png">

I tried clicking the button "Reconfigure device" in the UI, but that didn't help. Any suggestions?
