### ISSUE TITLE
[Device Support Request] Aqara vibration tilt sensor

### ISSUE THREAD

**Issue by thecobra666** [zigpy/zha-device-handlers#876]
**Is your feature request related to a problem? Please describe.**
The Aqara vibration sensor has more sensors then the one vibration sensor that is now available in ZHA.

**Describe the solution you'd like**
Have all the sensors mentioned in ZHA.

**Comment by dmulcahey** [comment]
Everything else is sent as `zha_event`

**Comment by thecobra666** [comment]
> Everything else is sent as `zha_event`

I know, but why? Now I have to manually created the sensors based on input fields.

**Comment by dmulcahey** [comment]
Remotes don’t get sensors per HA architecture

**Comment by martin3000** [comment]
you can convert it to a sensor:


```
- trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: "00:11:22:33:44:55:66:77"
      endpoint_id: 1
      command: "vibration_strength"
  sensor:
  - name: vibration
    state: "{{ trigger.event.data.args[0]['strength'] }}"
    unit_of_measurement: "%"

```
