### ISSUE TITLE
[Device Support Request] _TZE200_iossyxra (Battery Roller Blind Motor)

### ISSUE THREAD

**Issue by VladNord** [zigpy/zha-device-handlers#960]
**Is your feature request related to a problem? Please describe.**
Bought ZigBee Lithium Battery Roller Blind Motor. It does pair, but it does not expose any status, so I can't control it from HA

**Describe the solution you'd like**
Possibility to control it from HA

**Device signature - this can be acquired by removing the device from ZHA and pairing it again from the add devices screen. Be sure to add the entire content of the log panel after pairing the device to a code block below this line.**
```
"NodeDescriptor(byte1=1, byte2=64, mac_capability_flags=142, manufacturer_code=4098, 
maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, 
maximum_outgoing_transfer_size=82, descriptor_capability_field=0, 
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0051",
      "in_clusters": [
        "0x0000",
        "0x0004",
        "0x0005",
        "0xef00"
      ],
      "out_clusters": [
        "0x000a",
        "0x0019"
      ]
    }
  },
  "manufacturer": "_TZE200_iossyxra",
  "model": "TS0601",
  "class": "zigpy.device.Device"
}
```

**Additional context**
Product: https://aliexpress.ru/item/4000764153310.html?spm=a2g39.orderlist.0.0.47ce4aa67PXmvK&_ga=2.58309290.1271432921.1626213995-1279367481.1621973111

**Comment by VladNord** [comment]
After dancing with a tambourine, I found half-working solution with adding such code to  
**__init__.py**      `"_TZE200_iossyxra": {0x0000: 0x0000, 0x0001: 0x0002, 0x0002: 0x0001},`into # TUYA Cover Custom Values block
and **ts0601.py** `("_TZE200_iossyxra", "TS0601"),`into class TuyaMoesCover0601(TuyaWindowCover)

After these device is detected correctly, but blind buttons functionality from HA doesn't working (Error calling service)

But it can works, using this code in dev tools

```
service: zha.issue_zigbee_cluster_command
data:
  ieee: '84:71:27:ff:fe:0e:18:00'
  endpoint_id: 1
  cluster_id: 258
  cluster_type: in
  command_type: server
  command: 6
  args:
    - 0
    - 0
    - 1025
    - 0
    - - 0
      - 0 or 1 or 2
```
